=== lsst-ts/ts_xml/schema/SALCommandSet.xsd
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
        elementFormDefault="unqualified"
        attributeFormDefault="unqualified">

  <xsd:annotation>
    <xsd:documentation xml:lang="en">
     SAL Command data item schema for LSST
    </xsd:documentation>
  </xsd:annotation>

 <xsd:element name="SALCommandSet"   type="commandSetType"/>
 <xsd:element name="SALCommand"      type="commandType"/>
 <xsd:element name="SALCommandItem"  type="commandItemType"/>

 <xsd:complexType name="commandItemType">
   <xsd:choice maxOccurs="unbounded">
        <xsd:element name="EFDB_Name"     type="xsd:string"/>
        <xsd:element name="Description"   type="xsd:string"/>
        <xsd:element name="IDL_Type"      type="xsd:string"/>
        <xsd:element name="IDL_Size"      minOccurs="0"     type="xsd:string"/>
        <xsd:element name="Units"         type="xsd:string"/>
        <xsd:element name="Count"         type="xsd:positiveInteger"/>
        <xsd:element name="Enumeration"   minOccurs="0" maxOccurs="1" type="xsd:string"/>
    </xsd:choice>
 </xsd:complexType>

 <xsd:complexType name="commandType">
   <xsd:choice maxOccurs="unbounded">
      <xsd:element   name="Subsystem"     type="xsd:string"/>
      <xsd:element   name="Version"       type="version"/>
      <xsd:element   name="Author"        type="xsd:string"/>
      <xsd:element   name="EFDB_Topic"    type="xsd:string"/>
      <xsd:element   name="Alias"         type="xsd:string"/>
      <xsd:element   name="Device"        type="xsd:string"/>
      <xsd:element   name="Property"      type="xsd:string"/>
      <xsd:element   name="Action"        type="xsd:string"/>
      <xsd:element   name="Value"         type="xsd:string"/>
      <xsd:element   name="Description"   minOccurs="0" maxOccurs="1"    type="xsd:string"/>
      <xsd:element   name="Explanation"   minOccurs="0" maxOccurs="1"  type="xsd:anyURI"/>
      <xsd:element   name="item"          minOccurs="0" maxOccurs="unbounded" type="commandItemType"/>
   </xsd:choice>
 </xsd:complexType>


 <xsd:complexType name="commandSetType">
 <xsd:sequence>
    <xsd:element name="Enumeration"  minOccurs="0" maxOccurs="unbounded" type="xsd:string"/>
    <xsd:element name="SALCommand"   minOccurs="1" maxOccurs="unbounded" type="commandType"/>
 </xsd:sequence>
 </xsd:complexType>

 <xsd:attribute name="updateDate"    type="xsd:date"/>

 <xsd:simpleType name="version">
    <xsd:restriction base="xsd:token">
      <xsd:pattern value="\d+\.\d+(\.\d+)?"/>
    </xsd:restriction>
 </xsd:simpleType>

</xsd:schema>

=== lsst-ts/ts_xml/sal_interfaces/ATMonochromator/ATMonochromator_Commands.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="http://lsst-sal.tuc.noao.edu/schema/SALCommandSet.xsl"?>
<SALCommandSet xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://lsst-sal.tuc.noao.edu/schema/SALCommandSet.xsd">
  <SALCommand>
    <Subsystem>ATMonochromator</Subsystem>
    <Version>3.5.2</Version>
    <Author/>
    <EFDB_Topic>ATMonochromator_command_changeWavelength</EFDB_Topic>
    <Alias>changeWavelength</Alias>
    <Device/>
    <Property/>
    <Action/>
    <Value/>
    <Description>Command to change the wavelength of the monochromator</Description>
    <item>
      <EFDB_Name>wavelength</EFDB_Name>
      <Description>wavelength</Description>
      <IDL_Type>float</IDL_Type>
      <Units>meter</Units>
      <Count>1</Count>
    </item>
  </SALCommand>
  <SALCommand>
    <Subsystem>ATMonochromator</Subsystem>
    <Version>3.5.2</Version>
    <Author/>
    <EFDB_Topic>ATMonochromator_command_calibrateWavelength</EFDB_Topic>
    <Alias>calibrateWavelength</Alias>
    <Device/>
    <Property/>
    <Action/>
    <Value/>
    <Description>Command to calibrate the wavelength</Description>
    <item>
      <EFDB_Name>wavelength</EFDB_Name>
      <Description>wavelength</Description>
      <IDL_Type>float</IDL_Type>
      <Units>meter</Units>
      <Count>1</Count>
    </item>
  </SALCommand>
  <SALCommand>
    <Subsystem>ATMonochromator</Subsystem>
    <Version>3.5.2</Version>
    <Author/>
    <EFDB_Topic>ATMonochromator_command_power</EFDB_Topic>
    <Alias>power</Alias>
    <Device/>
    <Property/>
    <Action/>
    <Value/>
    <Description>Command to turn the power ON and OFF</Description>
    <item>
      <EFDB_Name>power</EFDB_Name>
      <Description>power</Description>
      <IDL_Type>boolean</IDL_Type>
      <Units>unitless</Units>
      <Count>1</Count>
    </item>
  </SALCommand>
  <SALCommand>
    <Subsystem>ATMonochromator</Subsystem>
    <Version>3.5.2</Version>
    <Author/>
    <EFDB_Topic>ATMonochromator_command_selectGrating</EFDB_Topic>
    <Alias>selectGrating</Alias>
    <Device/>
    <Property/>
    <Action/>
    <Value/>
    <Description>Select the grating (Blue,Red, Mirror) that will be in the path of light</Description>
    <item>
      <EFDB_Name>gratingType</EFDB_Name>
      <Description>grating type</Description>
      <!-- Enumeration: Grating -->
      <IDL_Type>long</IDL_Type>
      <Units>unitless</Units>
      <Count>1</Count>
      <Enumeration>gratingType_Grating_Blue,gratingType_Grating_Red,gratingType_Grating_Mirror</Enumeration>
    </item>
  </SALCommand>
  <SALCommand>
    <Subsystem>ATMonochromator</Subsystem>
    <Version>3.5.2</Version>
    <Author/>
    <EFDB_Topic>ATMonochromator_command_changeSlitWidth</EFDB_Topic>
    <Alias>changeSlitWidth</Alias>
    <Device/>
    <Property/>
    <Action/>
    <Value/>
    <Description>Command to change Front enterance or Front exit slit width to width specified</Description>
    <item>
      <EFDB_Name>slit</EFDB_Name>
      <Description>slit</Description>
      <!-- Enumeration: Slit -->
      <IDL_Type>long</IDL_Type>
      <Units>unitless</Units>
      <Count>1</Count>
      <Enumeration>slit_Slit_FrontEntrance,slit_Slit_FrontExit</Enumeration>
    </item>
    <item>
      <EFDB_Name>slitWidth</EFDB_Name>
      <Description>slitWidth</Description>
      <IDL_Type>float</IDL_Type>
      <Units>unitless</Units>
      <Count>1</Count>
    </item>
  </SALCommand>
  <SALCommand>
    <Subsystem>ATMonochromator</Subsystem>
    <Version>3.5.2</Version>
    <Author/>
    <EFDB_Topic>ATMonochromator_command_updateMonochromatorSetup</EFDB_Topic>
    <Alias>updateMonochromatorSetup</Alias>
    <Device/>
    <Property/>
    <Action/>
    <Value/>
    <Description>Command used to setup monochromator with a single command</Description>
    <item>
      <EFDB_Name>gratingType</EFDB_Name>
      <Description>Grating type</Description>
      <!-- Enumeration: Grating -->
      <IDL_Type>long</IDL_Type>
      <Units>unitless</Units>
      <Count>1</Count>
      <Enumeration>gratingType_Grating_Blue,gratingType_Grating_Red,gratingType_Grating_Mirror</Enumeration>
    </item>
    <item>
      <EFDB_Name>fontExitSlitWidth</EFDB_Name>
      <Description>slitwidth for front exit</Description>
      <IDL_Type>double</IDL_Type>
      <Units>unitless</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>fontEntranceSlitWidth</EFDB_Name>
      <Description>slitwidth for front entrance</Description>
      <IDL_Type>double</IDL_Type>
      <Units>unitless</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>wavelength</EFDB_Name>
      <Description>wavelength</Description>
      <IDL_Type>double</IDL_Type>
      <Units>meter</Units>
      <Count>1</Count>
    </item>
  </SALCommand>
</SALCommandSet>

=== lsst-ts/ts_xml/python/lsst/ts/xml/data/sal_interfaces/Guider/Guider_Commands.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="http://lsst-sal.tuc.noao.edu/schema/SALCommandSet.xsl"?>
<SALCommandSet xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://lsst-sal.tuc.noao.edu/schema/SALCommandSet.xsd">
  <!--- All of the commands defined below are deprecated, and will be removed on the next major update.
        Guiders are controlled by camera via initGuiders command  -->
  <SALCommand>
    <Subsystem>Guider</Subsystem>
    <EFDB_Topic>Guider_command_startGuiding</EFDB_Topic>
    <Description>Start guiding using the input information. The command returns as soon as guiding starts, before the first interation is completed. If it fails to find a guide star in the provided guider region, the CSC will go to fault state.</Description>
    <item>
      <EFDB_Name>roiXLeft</EFDB_Name>
      <Description>Vector with 8 elements specifying the origin of the guider ROI window in the x-axis for each guider sensor.</Description>
      <IDL_Type>long</IDL_Type>
      <Units>pixel</Units>
      <Count>8</Count>
    </item>
    <item>
      <EFDB_Name>roiXRight</EFDB_Name>
      <Description>Vector with 8 elements specifying the end of the guider ROI window in the x-axis for each guider sensor. If roiXLeft=roiXRight=0, for a particular element of both arrays, it assumes no guider region for the equivalent guider sensor. For each valid entry in roiXRight/roiXLeft the width must respect the ROI constrains (see requirement CA-TS-GDR-ICD-0006 in LSE-66).</Description>
      <IDL_Type>long</IDL_Type>
      <Units>pixel</Units>
      <Count>8</Count>
    </item>
    <item>
      <EFDB_Name>roiYBottom</EFDB_Name>
      <Description>Vector with 8 elements specifying the origin of the guider ROI window in the y-axis for each guider sensor.</Description>
      <IDL_Type>long</IDL_Type>
      <Units>pixel</Units>
      <Count>8</Count>
    </item>
    <item>
      <EFDB_Name>roiYTop</EFDB_Name>
      <Description>Vector with 8 elements specifying the end of the guider ROI window in the y-axis for each guider sensor. If roiXBottom=roiXTop=0, for a particular element of both arrays, it assumes no guider region for the equivalent guider sensor. For each valid entry in roiXBottom/roiXTop the width must respect the ROI constrains (see requirement CA-TS-GDR-ICD-0006 in LSE-66).</Description>
      <IDL_Type>long</IDL_Type>
      <Units>pixel</Units>
      <Count>8</Count>
    </item>
    <item>
      <EFDB_Name>expTime</EFDB_Name>
      <Description>Exposure time in milliseconds. All guider sensors will use the same exposure time (CA-TS-GDR-ICD-0034 LSE-66). Limits must respect detector integration time constrains (see requirement CA-TS-GDR-ICD-0034 in LSE-66).</Description>
      <IDL_Type>float</IDL_Type>
      <Units>ms</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>binning</EFDB_Name>
      <Description>Binnig factor. All guider sensors will use the same binning factor. Limits must respect detector binning constrains (see requirement CA-TS-GDR-ICD-0042 in LSE-66).</Description>
      <IDL_Type>long</IDL_Type>
      <Units>pixel</Units>
      <Count>1</Count>
    </item>
  </SALCommand>
  <SALCommand>
    <Subsystem>Guider</Subsystem>
    <EFDB_Topic>Guider_command_stopGuiding</EFDB_Topic>
    <Description>Stop current guider operation.</Description>
  </SALCommand>
  <SALCommand>
    <Subsystem>Guider</Subsystem>
    <EFDB_Topic>Guider_command_resumeGuiding</EFDB_Topic>
    <Description>Resume current guider operation. This command will restart a guider operation with the last values used in startGuiding. If no previous startGuiding command was issued, since the last time the CSC was enabled, the command will be rejected.</Description>
  </SALCommand>
</SALCommandSet>

=== lsst-ts/ts_xml/python/lsst/ts/xml/data/sal_interfaces/MTVMS/MTVMS_Commands.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="http://lsst-sal.tuc.noao.edu/schema/SALCommandSet.xsl"?>
<SALCommandSet xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://lsst-sal.tuc.noao.edu/schema/SALCommandSet.xsd">
  <SALCommand>
    <Subsystem>MTVMS</Subsystem>
    <EFDB_Topic>MTVMS_command_changeSamplePeriod</EFDB_Topic>
    <Description>Change sampling period.</Description>
    <item>
      <EFDB_Name>period</EFDB_Name>
      <Description>New sample period in milliseconds.</Description>
      <IDL_Type>int</IDL_Type>
      <Units>ms</Units>
      <Count>1</Count>
    </item>
  </SALCommand>
</SALCommandSet>

=== lsst-ts/ts_xml/sal_interfaces/m1m3/m1m3_Commands.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="http://lsst-sal.tuc.noao.edu/schema/SALCommandSet.xsl"?>
<SALCommandSet xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="http://lsst-sal.tuc.noao.edu/schema/SALCommandSet.xsd">


<SALCommand>
 <Subsystem>m1m3</Subsystem>
 <Version>2.5.3</Version>
 <Author>salgenerator</Author>
 <EFDB_Topic>m1m3_command_configure</EFDB_Topic>
 <Alias>configure</Alias>
 <Device>configure</Device>
 <Property></Property>
 <Action></Action>
 <Value></Value>
 <Explanation>http://sal.lsst.org/SAL/Commands/m1m3_command_configure.html</Explanation>
    <item>
      <EFDB_Name>spec_id</EFDB_Name>
      <Description> </Description>
       <IDL_Type>string</IDL_Type>
       <IDL_Size>1</IDL_Size>
      <Units> </Units>
      <Count>1</Count>
    </item>
</SALCommand>

<SALCommand>
 <Subsystem>m1m3</Subsystem>
 <Version>2.5.3</Version>
 <Author>salgenerator</Author>
 <EFDB_Topic>m1m3_command_status</EFDB_Topic>
 <Alias>status</Alias>
 <Device>status</Device>
 <Property></Property>
 <Action></Action>
 <Value></Value>
 <Explanation>http://sal.lsst.org/SAL/Commands/m1m3_command_status.html</Explanation>
    <item>
      <EFDB_Name>state</EFDB_Name>
      <Description> </Description>
       <IDL_Type>boolean</IDL_Type>
      <Units> </Units>
      <Count>1</Count>
    </item>
</SALCommand>

<SALCommand>
 <Subsystem>m1m3</Subsystem>
 <Version>2.5.3</Version>
 <Author>salgenerator</Author>
 <EFDB_Topic>m1m3_command_target</EFDB_Topic>
 <Alias>target</Alias>
 <Device>target</Device>
 <Property>position</Property>
 <Action></Action>
 <Value></Value>
 <Explanation>http://sal.lsst.org/SAL/Commands/m1m3_command_target.html</Explanation>
    <item>
      <EFDB_Name>azimuth</EFDB_Name>
      <Description> </Description>
       <IDL_Type>double</IDL_Type>
      <Units> </Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>elevation</EFDB_Name>
      <Description> </Description>
       <IDL_Type>double</IDL_Type>
      <Units> </Units>
      <Count>1</Count>
    </item>
</SALCommand>

<SALCommand>
 <Subsystem>m1m3</Subsystem>
 <Version>2.5.3</Version>
 <Author>salgenerator</Author>
 <EFDB_Topic>m1m3_command_update</EFDB_Topic>
 <Alias>update</Alias>
 <Device>update</Device>
 <Property>lut</Property>
 <Action></Action>
 <Value></Value>
 <Explanation>http://sal.lsst.org/SAL/Commands/m1m3_command_update.html</Explanation>
    <item>
      <EFDB_Name>lut_id</EFDB_Name>
      <Description> </Description>
       <IDL_Type>string</IDL_Type>
       <IDL_Size>1</IDL_Size>
      <Units> </Units>
      <Count>1</Count>
    </item>
</SALCommand>
</SALCommandSet>

=== lsst-ts/ts_xml/sal_interfaces/MTAlignment/MTAlignment_Commands.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="http://lsst-sal.tuc.noao.edu/schema/SALCommandSet.xsl"?>
<SALCommandSet xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://lsst-sal.tuc.noao.edu/schema/SALCommandSet.xsd">
  <Enumeration>Target_M2, Target_M1M3, Target_Camera, Target_Dome</Enumeration>
  <SALCommand>
    <Subsystem>MTAlignment</Subsystem>
    <EFDB_Topic>MTAlignment_command_measureTarget</EFDB_Topic>
    <Description>Measures the specified target</Description>
    <item>
      <EFDB_Name>target</EFDB_Name>
      <Description>target of measurement (M1M3, Camera, etc)</Description>
      <IDL_Type>string</IDL_Type>
      <Units>dimensionless</Units>
      <Count>1</Count>
    </item>
  </SALCommand>
  <SALCommand>
    <Subsystem>MTAlignment</Subsystem>
    <EFDB_Topic>MTAlignment_command_align</EFDB_Topic>
    <Description>Measures the specified target</Description>
    <item>
      <EFDB_Name>target</EFDB_Name>
      <Description>name of target, M2 or CAM</Description>
      <!-- Enumeration: Target -->
      <IDL_Type>long</IDL_Type>
      <Units>dimensionless</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>tolerance</EFDB_Name>
      <Description>relative tolerance threshold after which we will stop the correction loop</Description>
      <IDL_Type>float</IDL_Type>
      <Units>dimensionless</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>maxIter</EFDB_Name>
      <Description>Max iterations before we give up</Description>
      <IDL_Type>int</IDL_Type>
      <Units>dimensionless</Units>
      <Count>1</Count>
    </item>
  </SALCommand>
  <SALCommand>
    <Subsystem>MTAlignment</Subsystem>
    <EFDB_Topic>MTAlignment_command_measurePoint</EFDB_Topic>
    <item>
      <EFDB_Name>pointgroup</EFDB_Name>
      <Description>name of pointgroup containing target point</Description>
      <IDL_Type>string</IDL_Type>
      <Units>dimensionless</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>target</EFDB_Name>
      <Description>name of point to target</Description>
      <IDL_Type>string</IDL_Type>
      <Units>dimensionless</Units>
      <Count>1</Count>
    </item>
  </SALCommand>
  <SALCommand>
    <Subsystem>MTAlignment</Subsystem>
    <EFDB_Topic>MTAlignment_command_laserPower</EFDB_Topic>
    <item>
      <EFDB_Name>power</EFDB_Name>
      <Description>turns laser on and off</Description>
      <IDL_Type>boolean</IDL_Type>
      <Units>dimensionless</Units>
      <Count>1</Count>
    </item>
  </SALCommand>
  <SALCommand>
    <Subsystem>MTAlignment</Subsystem>
    <EFDB_Topic>MTAlignment_command_healthCheck</EFDB_Topic>
    <item>
      <EFDB_Name>healthCheck</EFDB_Name>
      <Description>executes the health check script</Description>
      <IDL_Type>boolean</IDL_Type>
      <Units>dimensionless</Units>
      <Count>1</Count>
    </item>
  </SALCommand>
</SALCommandSet>

=== lsst-ts/ts_xml/python/lsst/ts/xml/data/sal_interfaces/LEDProjector/LEDProjector_Commands.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="http://lsst-sal.tuc.noao.edu/schema/SALCommandSet.xsl"?>
<SALCommandSet xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://lsst-sal.tuc.noao.edu/schema/SALCommandSet.xsd">
  <SALCommand>
    <Subsystem>LEDProjector</Subsystem>
    <EFDB_Topic>LEDProjector_command_switchAllOn</EFDB_Topic>
    <Description>Switch on all LEDs connected to the labjack.</Description>
  </SALCommand>
  <SALCommand>
    <Subsystem>LEDProjector</Subsystem>
    <EFDB_Topic>LEDProjector_command_switchAllOff</EFDB_Topic>
    <Description>Switch off all LEDs connected to the labjack.</Description>
  </SALCommand>
  <SALCommand>
    <Subsystem>LEDProjector</Subsystem>
    <EFDB_Topic>LEDProjector_command_switchOn</EFDB_Topic>
    <Description>Switch on list of LEDs, named by serial number.</Description>
    <item>
      <EFDB_Name>serialNumbers</EFDB_Name>
      <Description>Comma-separated list of LED serial numbers to be turned on.</Description>
      <IDL_Type>string</IDL_Type>
      <IDL_Size>1</IDL_Size>
      <Units>unitless</Units>
      <Count>1</Count>
    </item>
  </SALCommand>
  <SALCommand>
    <Subsystem>LEDProjector</Subsystem>
    <EFDB_Topic>LEDProjector_command_switchOff</EFDB_Topic>
    <Description>Switch off list of LEDs, named by serial number.</Description>
    <item>
      <EFDB_Name>serialNumbers</EFDB_Name>
      <Description>Comma-separated list of LED serial numbers to be turned off.</Description>
      <IDL_Type>string</IDL_Type>
      <IDL_Size>1</IDL_Size>
      <Units>unitless</Units>
      <Count>1</Count>
    </item>
  </SALCommand>
  <SALCommand>
    <Subsystem>LEDProjector</Subsystem>
    <EFDB_Topic>LEDProjector_command_adjustDACPower</EFDB_Topic>
    <Description>adjust DAC power.</Description>
    <item>
      <EFDB_Name>serialNumbers</EFDB_Name>
      <Description>Comma-separated list of LED serial numbers to be adjusted</Description>
      <IDL_Type>string</IDL_Type>
      <IDL_Size>1</IDL_Size>
      <Units>unitless</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>dacValues</EFDB_Name>
      <Description>Comma-separated list of dac values in float or int to be adjusted</Description>
      <IDL_Type>string</IDL_Type>
      <IDL_Size>1</IDL_Size>
      <Units>unitless</Units>
      <Count>1</Count>
    </item>
  </SALCommand>
  <SALCommand>
    <Subsystem>LEDProjector</Subsystem>
    <EFDB_Topic>LEDProjector_command_adjustAllDACPower</EFDB_Topic>
    <Description>adjust All DAC channel power.</Description>
    <item>
      <EFDB_Name>dacValue</EFDB_Name>
      <Description>dac value to be adjusted</Description>
      <IDL_Type>float</IDL_Type>
      <IDL_Size>1</IDL_Size>
      <Units>Volt</Units>
      <Count>1</Count>
    </item>
  </SALCommand>
</SALCommandSet>

=== lsst-ts/ts_xml/sal_interfaces/MTTCS/MTTCS_Commands.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="http://lsst-sal.tuc.noao.edu/schema/SALCommandSet.xsl"?>
<SALCommandSet xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://lsst-sal.tuc.noao.edu/schema/SALCommandSet.xsd">
    <SALCommand>
        <Subsystem>MTTCS</Subsystem>
        <Version>1.0.0</Version>
        <Author>salgenerator</Author>
        <EFDB_Topic>MTTCS_command_stopMotion</EFDB_Topic>
        <Alias>stopMotion</Alias>
        <Device/>
        <Property/>
        <Action/>
        <Value/>
        <Explanation>Stop azimuth, altitude and rotator axes and dome rotation.</Explanation>
        <item>
            <EFDB_Name>ignored</EFDB_Name>
            <Description/>
            <IDL_Type>boolean</IDL_Type>
            <Units/>
            <Count>1</Count>
        </item>
    </SALCommand>
    <SALCommand>
        <Subsystem>MTTCS</Subsystem>
        <Version>1.0.0</Version>
        <Author>salgenerator</Author>
        <EFDB_Topic>MTTCS_command_target</EFDB_Topic>
        <Alias>target</Alias>
        <Device/>
        <Property/>
        <Action/>
        <Value/>
        <Explanation>Acquire a target (slew and track).</Explanation>
        <item>
            <EFDB_Name>targetId</EFDB_Name>
            <Description/>
            <IDL_Type>long</IDL_Type>
            <Units/>
            <Count>1</Count>
        </item>
        <item>
            <EFDB_Name>coordSys</EFDB_Name>
            <Description>Coordinate system for `position`.</Description>
            <IDL_Type>long</IDL_Type>
            <Enumeration>ICRS, Observed, Mount</Enumeration>
            <Units/>
            <Count>1</Count>
        </item>
        <item>
            <EFDB_Name>position</EFDB_Name>
            <Description>Right ascension/azimuth, declination/altitude</Description>
            <IDL_Type>double</IDL_Type>
            <Units>degrees</Units>
            <Count>2</Count>
        </item>
        <item>
            <EFDB_Name>rotType</EFDB_Name>
            <Description>Coordinate system for rotAngle. One of:
    * RotSky: Position angle of focal plane +Y, measured from N through E.
      At 0 degrees, +Y is along N and +X is along E/W depending on handedness.
      At 90 degrees, +Y is along E and +X is along S/N depending on handedness.
    * RotHorizon: Position angle of focal plane +Y, measured from +Alt through +Az.
      At 0 degrees, +Y is along +Alt and +X is along +/-Az, depending on handedness.
      At 90 degrees, +Y is along +Az and +X is along -/+Alt, depending on handedness.
    * RotMount: The position sent to the instrument rotator; the details depend on the rotator.
  </Description>
            <IDL_Type>long</IDL_Type>
            <Enumeration>RotSky, RotHorizon, RotMount</Enumeration>
            <Units/>
            <Count>1</Count>
        </item>
        <item>
            <EFDB_Name>rotAngle</EFDB_Name>
            <Description/>
            <IDL_Type>double</IDL_Type>
            <Units/>
            <Count>1</Count>
        </item>
        <item>
            <EFDB_Name>numExposures</EFDB_Name>
            <Description>Number of exposures</Description>
            <IDL_Type>long</IDL_Type>
            <Units/>
            <Count>1</Count>
        </item>
        <item>
            <EFDB_Name>exposureTime</EFDB_Name>
            <Description>Exposure time per exposure</Description>
            <IDL_Type>float</IDL_Type>
            <Units>seconds</Units>
            <Count>1</Count>
        </item>
        <item>
            <EFDB_Name>domeMode</EFDB_Name>
            <Description>Mode for enclosure rotation; one of:
    * DomeTracking: track the telescope; ignore domeAzimuth.
    * DomeFixed: move to the specified domeAzimuth and stay there.</Description>
            <IDL_Type>long</IDL_Type>
            <Enumeration>DomeTracking, DomeFixed</Enumeration>
            <Units/>
            <Count>1</Count>
        </item>
        <item>
            <EFDB_Name>domeAzimuth</EFDB_Name>
            <Description>Dome azimuth; ignored if domeMode is DomeTracking</Description>
            <IDL_Type>double</IDL_Type>
            <Units/>
            <Count>1</Count>
        </item>
    </SALCommand>
    <SALCommand>
        <Subsystem>MTTCS</Subsystem>
        <Version>1.0.0</Version>
        <Author>salgenerator</Author>
        <EFDB_Topic>MTTCS_command_offset</EFDB_Topic>
        <Alias>offset</Alias>
        <Device/>
        <Property/>
        <Action/>
        <Value/>
        <Explanation>Offset the telescope. All offsets are along the arc of a great circle, whose orientation (angle from axis 0 to axis 1 at the starting point) is given by atan2(amount[1], amount[0]) and the arc length is the norm of amount.</Explanation>
        <item>
            <EFDB_Name>objectOffset</EFDB_Name>
            <Description>Amount of object offset; the axes are position[0], position[1].</Description>
            <IDL_Type>double</IDL_Type>
            <Units>degrees</Units>
            <Count>2</Count>
        </item>
        <item>
            <EFDB_Name>objectAbsolute</EFDB_Name>
            <Description>If True objectOffset is absolute, else it is relative to the current offset.</Description>
            <IDL_Type>boolean</IDL_Type>
            <Units/>
            <Count>1</Count>
        </item>
        <item>
            <EFDB_Name>boresightOffset</EFDB_Name>
            <Description>Amount of boresight offset; the axes are focal plane x, focal plane y.</Description>
            <IDL_Type>double</IDL_Type>
            <Units>degrees</Units>
            <Count>2</Count>
        </item>
        <item>
            <EFDB_Name>boresightAbsolute</EFDB_Name>
            <Description>If True boresightOffset is absolute, else it is relative to the current offset.</Description>
            <IDL_Type>boolean</IDL_Type>
            <Units/>
            <Count>1</Count>
        </item>
    </SALCommand>
</SALCommandSet>
