=== lsst-ts/ts_xml/schema/SALCommandSet.xsd
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
        elementFormDefault="unqualified"
        attributeFormDefault="unqualified">

  <xsd:annotation>
    <xsd:documentation xml:lang="en">
     SAL Command data item schema for LSST
    </xsd:documentation>
  </xsd:annotation>

 <xsd:element name="SALCommandSet"   type="commandSetType"/>
 <xsd:element name="SALCommand"      type="commandType"/>
 <xsd:element name="SALCommandItem"  type="commandItemType"/>

 <xsd:complexType name="commandItemType">
   <xsd:choice maxOccurs="unbounded">
        <xsd:element name="EFDB_Name"     type="xsd:string"/>
        <xsd:element name="Description"   type="xsd:string"/>
        <xsd:element name="IDL_Type"      type="xsd:string"/>
        <xsd:element name="IDL_Size"      minOccurs="0"     type="xsd:string"/>
        <xsd:element name="Units"         type="xsd:string"/>
        <xsd:element name="Count"         type="xsd:positiveInteger"/>
        <xsd:element name="Enumeration"   minOccurs="0" maxOccurs="1" type="xsd:string"/>
    </xsd:choice>
 </xsd:complexType>

 <xsd:complexType name="commandType">
   <xsd:choice maxOccurs="unbounded">
      <xsd:element   name="Subsystem"     type="xsd:string"/>
      <xsd:element   name="Version"       type="version"/>
      <xsd:element   name="Author"        type="xsd:string"/>
      <xsd:element   name="EFDB_Topic"    type="xsd:string"/>
      <xsd:element   name="Alias"         type="xsd:string"/>
      <xsd:element   name="Device"        type="xsd:string"/>
      <xsd:element   name="Property"      type="xsd:string"/>
      <xsd:element   name="Action"        type="xsd:string"/>
      <xsd:element   name="Value"         type="xsd:string"/>
      <xsd:element   name="Description"   minOccurs="0" maxOccurs="1"    type="xsd:string"/>
      <xsd:element   name="Explanation"   minOccurs="0" maxOccurs="1"  type="xsd:anyURI"/>
      <xsd:element   name="item"          minOccurs="0" maxOccurs="unbounded" type="commandItemType"/>
   </xsd:choice>
 </xsd:complexType>


 <xsd:complexType name="commandSetType">
 <xsd:sequence>
    <xsd:element name="Enumeration"  minOccurs="0" maxOccurs="unbounded" type="xsd:string"/>
    <xsd:element name="SALCommand"   minOccurs="1" maxOccurs="unbounded" type="commandType"/>
 </xsd:sequence>
 </xsd:complexType>

 <xsd:attribute name="updateDate"    type="xsd:date"/>

 <xsd:simpleType name="version">
    <xsd:restriction base="xsd:token">
      <xsd:pattern value="\d+\.\d+(\.\d+)?"/>
    </xsd:restriction>
 </xsd:simpleType>

</xsd:schema>

=== lsst-ts/ts_xml/sal_interfaces/CCCamera/CCCamera_Commands.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="http://project.lsst.org/ts/sal_objects/schema/SALCommandSet.xsl"?>
<SALCommandSet xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="http://project.lsst.org/ts/sal_objects/schema/SALCommandSet.xsd">
<SALCommand>
    <Subsystem>CCCamera</Subsystem>
    <Version>3.7.1</Version>
    <Author></Author>
    <EFDB_Topic>CCCamera_command_discardRows</EFDB_Topic>
    <Alias>discardRows</Alias>
    <Device></Device>
    <Property></Property>
    <Action></Action>
    <Value></Value>
    <Explanation>http://project.lsst.org/ts/sal_objects/help</Explanation>
    <item>
        <EFDB_Name>nRows</EFDB_Name>
        <Description>Number of rows to discard</Description>
        <IDL_Type>long</IDL_Type>
        <Units>unitless</Units>
        <Count>1</Count>
    </item>
</SALCommand>
<SALCommand>
    <Subsystem>CCCamera</Subsystem>
    <Version>3.7.1</Version>
    <Author></Author>
    <EFDB_Topic>CCCamera_command_startImage</EFDB_Topic>
    <Alias>startImage</Alias>
    <Device></Device>
    <Property></Property>
    <Action></Action>
    <Value></Value>
    <Explanation>http://project.lsst.org/ts/sal_objects/help</Explanation>
    <item>
        <EFDB_Name>shutter</EFDB_Name>
        <Description>True if the shutter should be opened/closed</Description>
        <IDL_Type>boolean</IDL_Type>
        <Units>unitless</Units>
        <Count>1</Count>
    </item>
    <item>
        <EFDB_Name>sensors</EFDB_Name>
        <Description>Sensors to be read out, if blank all configured sensors will be read out</Description>
        <IDL_Type>string</IDL_Type>
        <Units>unitless</Units>
        <Count>1</Count>
    </item>
    <item>
        <EFDB_Name>keyValueMap</EFDB_Name>
        <Description>Map of additional key value pairs, e.g. imageType: XYZ, groupId: ABC</Description>
        <IDL_Type>string</IDL_Type>
        <Units>unitless</Units>
        <Count>1</Count>
    </item>
    <item>
        <EFDB_Name>obsNote</EFDB_Name>
        <Description>An arbitrary operator provided string, useful for informally flagging images</Description>
        <IDL_Type>string</IDL_Type>
        <Units>unitless</Units>
        <Count>1</Count>
    </item>
    <item>
        <EFDB_Name>timeout</EFDB_Name>
        <Description>Timeout after which imaging will be abandoned if no endImage command received</Description>
        <IDL_Type>double</IDL_Type>
        <Units>second</Units>
        <Count>1</Count>
    </item>
</SALCommand>
<SALCommand>
    <Subsystem>CCCamera</Subsystem>
    <Version>3.7.1</Version>
    <Author></Author>
    <EFDB_Topic>CCCamera_command_disableCalibration</EFDB_Topic>
    <Alias>disableCalibration</Alias>
    <Device></Device>
    <Property></Property>
    <Action></Action>
    <Value></Value>
    <Explanation>http://project.lsst.org/ts/sal_objects/help</Explanation>
    <item>
        <EFDB_Name>value</EFDB_Name>
        <Description>Attribute required by the API, but is unused.</Description>
        <IDL_Type>boolean</IDL_Type>
        <Units>unitless</Units>
        <Count>1</Count>
    </item>
</SALCommand>
<SALCommand>
    <Subsystem>CCCamera</Subsystem>
    <Version>3.7.1</Version>
    <Author></Author>
    <EFDB_Topic>CCCamera_command_initGuiders</EFDB_Topic>
    <Alias>initGuiders</Alias>
    <Device></Device>
    <Property></Property>
    <Action></Action>
    <Value></Value>
    <Explanation>http://project.lsst.org/ts/sal_objects/help</Explanation>
    <item>
        <EFDB_Name>roiSpec</EFDB_Name>
        <Description>TBD specification for region of interest</Description>
        <IDL_Type>string</IDL_Type>
        <IDL_Size>256</IDL_Size>
        <Units>unitless</Units>
        <Count>1</Count>
    </item>
</SALCommand>
<SALCommand>
    <Subsystem>CCCamera</Subsystem>
    <Version>3.7.1</Version>
    <Author></Author>
    <EFDB_Topic>CCCamera_command_enableCalibration</EFDB_Topic>
    <Alias>enableCalibration</Alias>
    <Device></Device>
    <Property></Property>
    <Action></Action>
    <Value></Value>
    <Explanation>http://project.lsst.org/ts/sal_objects/help</Explanation>
    <item>
        <EFDB_Name>value</EFDB_Name>
        <Description>Attribute required by the API, but is unused.</Description>
        <IDL_Type>boolean</IDL_Type>
        <Units>unitless</Units>
        <Count>1</Count>
    </item>
</SALCommand>
<SALCommand>
    <Subsystem>CCCamera</Subsystem>
    <Version>3.7.1</Version>
    <Author></Author>
    <EFDB_Topic>CCCamera_command_initImage</EFDB_Topic>
    <Alias>initImage</Alias>
    <Device></Device>
    <Property></Property>
    <Action></Action>
    <Value></Value>
    <Explanation>http://project.lsst.org/ts/sal_objects/help</Explanation>
    <item>
        <EFDB_Name>deltaT</EFDB_Name>
        <Description>Estimate of time period before takeImages will be issued</Description>
        <IDL_Type>double</IDL_Type>
        <Units>second</Units>
        <Count>1</Count>
    </item>
</SALCommand>
<SALCommand>
    <Subsystem>CCCamera</Subsystem>
    <Version>3.7.1</Version>
    <Author></Author>
    <EFDB_Topic>CCCamera_command_endImage</EFDB_Topic>
    <Alias>endImage</Alias>
    <Device></Device>
    <Property></Property>
    <Action></Action>
    <Value></Value>
    <Explanation>http://project.lsst.org/ts/sal_objects/help</Explanation>
    <item>
        <EFDB_Name>value</EFDB_Name>
        <Description>Attribute required by the API, but is unused.</Description>
        <IDL_Type>boolean</IDL_Type>
        <Units>unitless</Units>
        <Count>1</Count>
    </item>
</SALCommand>
<SALCommand>
    <Subsystem>CCCamera</Subsystem>
    <Version>3.7.1</Version>
    <Author></Author>
    <EFDB_Topic>CCCamera_command_setFilter</EFDB_Topic>
    <Alias>setFilter</Alias>
    <Device></Device>
    <Property></Property>
    <Action></Action>
    <Value></Value>
    <Explanation>http://project.lsst.org/ts/sal_objects/help</Explanation>
    <item>
        <EFDB_Name>name</EFDB_Name>
        <Description>The filter name to install</Description>
        <IDL_Type>string</IDL_Type>
        <IDL_Size>256</IDL_Size>
        <Units>unitless</Units>
        <Count>1</Count>
    </item>
</SALCommand>
<SALCommand>
    <Subsystem>CCCamera</Subsystem>
    <Version>3.7.1</Version>
    <Author></Author>
    <EFDB_Topic>CCCamera_command_clear</EFDB_Topic>
    <Alias>clear</Alias>
    <Device></Device>
    <Property></Property>
    <Action></Action>
    <Value></Value>
    <Explanation>http://project.lsst.org/ts/sal_objects/help</Explanation>
    <item>
        <EFDB_Name>nClears</EFDB_Name>
        <Description>Number of consecutive clear operations to perform</Description>
        <IDL_Type>long</IDL_Type>
        <Units>unitless</Units>
        <Count>1</Count>
    </item>
</SALCommand>
<SALCommand>
    <Subsystem>CCCamera</Subsystem>
    <Version>3.7.1</Version>
    <Author></Author>
    <EFDB_Topic>CCCamera_command_takeImages</EFDB_Topic>
    <Alias>takeImages</Alias>
    <Device></Device>
    <Property></Property>
    <Action></Action>
    <Value></Value>
    <Explanation>http://project.lsst.org/ts/sal_objects/help</Explanation>
    <item>
        <EFDB_Name>numImages</EFDB_Name>
        <Description>Number of consecutive images to take</Description>
        <IDL_Type>long</IDL_Type>
        <Units>unitless</Units>
        <Count>1</Count>
    </item>
    <item>
        <EFDB_Name>expTime</EFDB_Name>
        <Description>Exposure time</Description>
        <IDL_Type>double</IDL_Type>
        <Units>second</Units>
        <Count>1</Count>
    </item>
    <item>
        <EFDB_Name>shutter</EFDB_Name>
        <Description>True if the shutter should be opened/closed</Description>
        <IDL_Type>boolean</IDL_Type>
        <Units>unitless</Units>
        <Count>1</Count>
    </item>
    <item>
        <EFDB_Name>sensors</EFDB_Name>
        <Description>Sensors to be read out, if blank all configured sensors will be read out</Description>
        <IDL_Type>string</IDL_Type>
        <Units>unitless</Units>
        <Count>1</Count>
    </item>
    <item>
        <EFDB_Name>keyValueMap</EFDB_Name>
        <Description>Map of additional key value pairs, e.g. imageType: XYZ, groupId: ABC</Description>
        <IDL_Type>string</IDL_Type>
        <Units>unitless</Units>
        <Count>1</Count>
    </item>
    <item>
        <EFDB_Name>obsNote</EFDB_Name>
        <Description>An arbitrary operator provided string, useful for informally flagging images</Description>
        <IDL_Type>string</IDL_Type>
        <Units>unitless</Units>
        <Count>1</Count>
    </item>    
</SALCommand>
<SALCommand>
    <Subsystem>CCCamera</Subsystem>
    <Version>3.7.1</Version>
    <Author></Author>
    <EFDB_Topic>CCCamera_command_stop</EFDB_Topic>
    <Alias>stop</Alias>
    <Device></Device>
    <Property></Property>
    <Action></Action>
    <Value></Value>
    <Explanation>http://project.lsst.org/ts/sal_objects/help</Explanation>
    <item>
        <EFDB_Name>value</EFDB_Name>
        <Description>Attribute required by the API, but is unused.</Description>
        <IDL_Type>boolean</IDL_Type>
        <Units>unitless</Units>
        <Count>1</Count>
    </item>
</SALCommand>
</SALCommandSet>

=== lsst-ts/ts_xml/sal_interfaces/Dome/Dome_Commands.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="http://lsst-sal.tuc.noao.edu/schema/SALCommandSet.xsl"?>
<SALCommandSet xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="http://lsst-sal.tuc.noao.edu/schema/SALCommandSet.xsd">
<SALCommand>
    <Subsystem>Dome</Subsystem>
    <Version>3.7.1</Version>
    <Author></Author>
    <EFDB_Topic>Dome_command_crawlAz</EFDB_Topic>
    <Alias>crawlAz</Alias>
    <Device></Device>
    <Property></Property>
    <Action></Action>
    <Value></Value>
    <Explanation>http://sal.lsst.org</Explanation>
    <item>
        <EFDB_Name>azRate</EFDB_Name>
        <Description>Specifies the velocity of crawl motion in degrees per second. Positive means in the direction of increasing azimuth, negative in the direction of decreasing azimuth.</Description>
        <IDL_Type>double</IDL_Type>
        <Units>deg/second</Units>
        <Count>1</Count>
    </item>
</SALCommand>
<SALCommand>
    <Subsystem>Dome</Subsystem>
    <Version>3.7.1</Version>
    <Author></Author>
    <EFDB_Topic>Dome_command_crawlEl</EFDB_Topic>
    <Alias>crawlEl</Alias>
    <Device></Device>
    <Property></Property>
    <Action></Action>
    <Value></Value>
    <Explanation>http://sal.lsst.org</Explanation>
    <item>
        <EFDB_Name>elRate</EFDB_Name>
        <Description>Specifies the velocity of crawl motion in degrees per second. Positive means in the direction of increasing elevation, negative in the direction of decreasing elevation.</Description>
        <IDL_Type>double</IDL_Type>
        <Units>deg/second</Units>
        <Count>1</Count>
    </item>
</SALCommand>
<SALCommand>
    <Subsystem>Dome</Subsystem>
    <Version>3.7.1</Version>
    <Author></Author>
    <EFDB_Topic>Dome_command_moveAz</EFDB_Topic>
    <Alias>moveAz</Alias>
    <Device></Device>
    <Property></Property>
    <Action></Action>
    <Value></Value>
    <Explanation>http://sal.lsst.org</Explanation>
    <item>
        <EFDB_Name>azimuth</EFDB_Name>
        <Description>Absolute positon angle for azimuth rotation in degrees</Description>
        <IDL_Type>double</IDL_Type>
        <Units>deg</Units>
        <Count>1</Count>
    </item>
    <item>
        <EFDB_Name>azRate</EFDB_Name>
        <Description>Specifies the velocity of crawl motion in degrees per second at which the motion should continue once the commanded azimuth has been reached. Positive means in the direction of increasing azimuth, negative in the direction of decreasing azimuth.</Description>
        <IDL_Type>double</IDL_Type>
        <Units>deg/second</Units>
        <Count>1</Count>
    </item>
</SALCommand>
<SALCommand>
    <Subsystem>Dome</Subsystem>
    <Version>3.7.1</Version>
    <Author></Author>
    <EFDB_Topic>Dome_command_moveEl</EFDB_Topic>
    <Alias>moveEl</Alias>
    <Device></Device>
    <Property></Property>
    <Action></Action>
    <Value></Value>
    <Explanation>http://sal.lsst.org</Explanation>
    <item>
        <EFDB_Name>elevation</EFDB_Name>
        <Description>Absolute position angle for elevation motion in degrees</Description>
        <IDL_Type>double</IDL_Type>
        <Units>deg</Units>
        <Count>1</Count>
    </item>
</SALCommand>
<SALCommand>
    <Subsystem>Dome</Subsystem>
    <Version>3.7.1</Version>
    <Author></Author>
    <EFDB_Topic>Dome_command_park</EFDB_Topic>
    <Alias>park</Alias>
    <Device></Device>
    <Property></Property>
    <Action></Action>
    <Value></Value>
    <Explanation>http://sal.lsst.org</Explanation>
</SALCommand>
<SALCommand>
    <Subsystem>Dome</Subsystem>
    <Version>3.7.1</Version>
    <Author></Author>
    <EFDB_Topic>Dome_command_setLouver</EFDB_Topic>
    <Alias>setLouver</Alias>
    <Device></Device>
    <Property></Property>
    <Action></Action>
    <Value></Value>
    <Explanation>http://sal.lsst.org</Explanation>
    <item>
        <EFDB_Name>id</EFDB_Name>
        <Description>Identification of louver to move</Description>
        <IDL_Type>int</IDL_Type>
        <Units>unitless</Units>
        <Count>1</Count>
    </item>
    <item>
        <EFDB_Name>position</EFDB_Name>
        <Description>The position to set the louver</Description>
        <IDL_Type>int</IDL_Type>
        <Units>unitless</Units>
        <Count>1</Count>
    </item>
</SALCommand>
<SALCommand>
    <Subsystem>Dome</Subsystem>
    <Version>3.7.1</Version>
    <Author></Author>
    <EFDB_Topic>Dome_command_closeLouvers</EFDB_Topic>
    <Alias>closeLouvers</Alias>
    <Device></Device>
    <Property></Property>
    <Action></Action>
    <Value></Value>
    <Explanation>http://sal.lsst.org</Explanation>
</SALCommand>
<SALCommand>
    <Subsystem>Dome</Subsystem>
    <Version>3.7.1</Version>
    <Author></Author>
    <EFDB_Topic>Dome_command_stopLouvers</EFDB_Topic>
    <Alias>stopLouvers</Alias>
    <Device></Device>
    <Property></Property>
    <Action></Action>
    <Value></Value>
    <Explanation>http://sal.lsst.org</Explanation>
</SALCommand>
<SALCommand>
    <Subsystem>Dome</Subsystem>
    <Version>3.7.1</Version>
    <Author></Author>
    <EFDB_Topic>Dome_command_closeShutter</EFDB_Topic>
    <Alias>closeShutter</Alias>
    <Device></Device>
    <Property></Property>
    <Action></Action>
    <Value></Value>
    <Explanation>http://sal.lsst.org</Explanation>
</SALCommand>
<SALCommand>
    <Subsystem>Dome</Subsystem>
    <Version>3.7.1</Version>
    <Author></Author>
    <EFDB_Topic>Dome_command_openShutter</EFDB_Topic>
    <Alias>openShutter</Alias>
    <Device></Device>
    <Property></Property>
    <Action></Action>
    <Value></Value>
    <Explanation>http://sal.lsst.org</Explanation>
</SALCommand>
<SALCommand>
    <Subsystem>Dome</Subsystem>
    <Version>3.7.1</Version>
    <Author></Author>
    <EFDB_Topic>Dome_command_stopShutter</EFDB_Topic>
    <Alias>stopShutter</Alias>
    <Device></Device>
    <Property></Property>
    <Action></Action>
    <Value></Value>
    <Explanation>http://sal.lsst.org</Explanation>
</SALCommand>
<SALCommand>
    <Subsystem>Dome</Subsystem>
    <Version>3.7.1</Version>
    <Author></Author>
    <EFDB_Topic>Dome_command_stopAz</EFDB_Topic>
    <Alias>stopAz</Alias>
    <Device></Device>
    <Property></Property>
    <Action></Action>
    <Value></Value>
    <Explanation>http://sal.lsst.org</Explanation>
</SALCommand>
<SALCommand>
    <Subsystem>Dome</Subsystem>
    <Version>3.7.1</Version>
    <Author></Author>
    <EFDB_Topic>Dome_command_stopEl</EFDB_Topic>
    <Alias>stopEl</Alias>
    <Device></Device>
    <Property></Property>
    <Action></Action>
    <Value></Value>
    <Explanation>http://sal.lsst.org</Explanation>
</SALCommand>
<SALCommand>
    <Subsystem>Dome</Subsystem>
    <Version>3.7.1</Version>
    <Author></Author>
    <EFDB_Topic>Dome_command_stop</EFDB_Topic>
    <Alias>stop</Alias>
    <Device></Device>
    <Property></Property>
    <Action></Action>
    <Value></Value>
    <Explanation>http://sal.lsst.org</Explanation>
</SALCommand>
<SALCommand>
    <Subsystem>Dome</Subsystem>
    <Version>3.7.1</Version>
    <Author></Author>
    <EFDB_Topic>Dome_command_setTemperature</EFDB_Topic>
    <Alias>setTemperature</Alias>
    <Device></Device>
    <Property></Property>
    <Action></Action>
    <Value></Value>
    <Explanation>http://sal.lsst.org</Explanation>
    <item>
        <EFDB_Name>temperature</EFDB_Name>
        <Description>Set the temperature to maintain in the dome heat sources</Description>
        <IDL_Type>double</IDL_Type>
        <Units>Celsius</Units>
        <Count>1</Count>
    </item>
</SALCommand>
</SALCommandSet>

=== lsst-ts/ts_xml/python/lsst/ts/xml/data/sal_interfaces/Test/Test_Commands.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="http://lsst-sal.tuc.noao.edu/schema/SALCommandSet.xsl"?>
<SALCommandSet xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://lsst-sal.tuc.noao.edu/schema/SALCommandSet.xsd">
  <SALCommand>
    <Subsystem>Test</Subsystem>
    <EFDB_Topic>Test_command_setScalars</EFDB_Topic>
    <Description>Set scalar values.</Description>
    <item>
      <EFDB_Name>boolean0</EFDB_Name>
      <Description>A boolean.</Description>
      <IDL_Type>boolean</IDL_Type>
      <Units>unitless</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>byte0</EFDB_Name>
      <Description>A byte.</Description>
      <IDL_Type>byte</IDL_Type>
      <Units>unitless</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>short0</EFDB_Name>
      <Description>A short.</Description>
      <IDL_Type>short</IDL_Type>
      <Units>unitless</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>int0</EFDB_Name>
      <Description>An int.</Description>
      <IDL_Type>int</IDL_Type>
      <Units>unitless</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>long0</EFDB_Name>
      <Description>A long.</Description>
      <IDL_Type>long</IDL_Type>
      <Units>unitless</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>longLong0</EFDB_Name>
      <Description>A long long.</Description>
      <IDL_Type>long long</IDL_Type>
      <Units>unitless</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>unsignedShort0</EFDB_Name>
      <Description>An unsigned short.</Description>
      <IDL_Type>unsigned short</IDL_Type>
      <Units>unitless</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>unsignedInt0</EFDB_Name>
      <Description>An unsigned int.</Description>
      <IDL_Type>unsigned int</IDL_Type>
      <Units>unitless</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>float0</EFDB_Name>
      <Description>A float.</Description>
      <IDL_Type>float</IDL_Type>
      <Units>unitless</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>double0</EFDB_Name>
      <Description>A double.</Description>
      <IDL_Type>double</IDL_Type>
      <Units>unitless</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>string0</EFDB_Name>
      <Description>A string.</Description>
      <IDL_Type>string</IDL_Type>
      <IDL_Size>20</IDL_Size>
      <Units>unitless</Units>
      <Count>1</Count>
    </item>
  </SALCommand>
  <SALCommand>
    <Subsystem>Test</Subsystem>
    <EFDB_Topic>Test_command_setArrays</EFDB_Topic>
    <Description>Set array values.</Description>
    <item>
      <EFDB_Name>boolean0</EFDB_Name>
      <Description>Array of boolean.</Description>
      <IDL_Type>boolean</IDL_Type>
      <Units>unitless</Units>
      <Count>5</Count>
    </item>
    <item>
      <EFDB_Name>byte0</EFDB_Name>
      <Description>Array of byte.</Description>
      <IDL_Type>byte</IDL_Type>
      <Units>unitless</Units>
      <Count>5</Count>
    </item>
    <item>
      <EFDB_Name>short0</EFDB_Name>
      <Description>Array of short.</Description>
      <IDL_Type>short</IDL_Type>
      <Units>unitless</Units>
      <Count>5</Count>
    </item>
    <item>
      <EFDB_Name>int0</EFDB_Name>
      <Description>Array of int.</Description>
      <IDL_Type>int</IDL_Type>
      <Units>unitless</Units>
      <Count>5</Count>
    </item>
    <item>
      <EFDB_Name>long0</EFDB_Name>
      <Description>Array of long.</Description>
      <IDL_Type>long</IDL_Type>
      <Units>unitless</Units>
      <Count>5</Count>
    </item>
    <item>
      <EFDB_Name>longLong0</EFDB_Name>
      <Description>Array of long long.</Description>
      <IDL_Type>long long</IDL_Type>
      <Units>unitless</Units>
      <Count>5</Count>
    </item>
    <item>
      <EFDB_Name>unsignedShort0</EFDB_Name>
      <Description>Array of unsigned short.</Description>
      <IDL_Type>unsigned short</IDL_Type>
      <Units>unitless</Units>
      <Count>5</Count>
    </item>
    <item>
      <EFDB_Name>unsignedInt0</EFDB_Name>
      <Description>Array of unsigned int.</Description>
      <IDL_Type>unsigned int</IDL_Type>
      <Units>unitless</Units>
      <Count>5</Count>
    </item>
    <item>
      <EFDB_Name>float0</EFDB_Name>
      <Description>Array of float.</Description>
      <IDL_Type>float</IDL_Type>
      <Units>unitless</Units>
      <Count>5</Count>
    </item>
    <item>
      <EFDB_Name>double0</EFDB_Name>
      <Description>Array of double.</Description>
      <IDL_Type>double</IDL_Type>
      <Units>unitless</Units>
      <Count>5</Count>
    </item>
  </SALCommand>
  <SALCommand>
    <Subsystem>Test</Subsystem>
    <EFDB_Topic>Test_command_fault</EFDB_Topic>
    <Description>Enter the Fault summary state.</Description>
  </SALCommand>
  <SALCommand>
    <Subsystem>Test</Subsystem>
    <EFDB_Topic>Test_command_wait</EFDB_Topic>
    <Description>Wait for the specified period.</Description>
    <item>
      <EFDB_Name>ack</EFDB_Name>
      <Description>Final ack code, typically a SAL__CMD constant.</Description>
      <IDL_Type>int</IDL_Type>
      <Units>unitless</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>duration</EFDB_Name>
      <Description>Desired command duration.</Description>
      <IDL_Type>double</IDL_Type>
      <Units>second</Units>
      <Count>1</Count>
    </item>
  </SALCommand>
</SALCommandSet>
