=== lsst-ts/ts_xml/schema/SALCommandSet.xsd
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
        elementFormDefault="unqualified"
        attributeFormDefault="unqualified">

  <xsd:annotation>
    <xsd:documentation xml:lang="en">
     SAL Command data item schema for LSST
    </xsd:documentation>
  </xsd:annotation>

 <xsd:element name="SALCommandSet"   type="commandSetType"/>
 <xsd:element name="SALCommand"      type="commandType"/>
 <xsd:element name="SALCommandItem"  type="commandItemType"/>

 <xsd:complexType name="commandItemType">
   <xsd:choice maxOccurs="unbounded">
        <xsd:element name="EFDB_Name"     type="xsd:string"/>
        <xsd:element name="Description"   type="xsd:string"/>
        <xsd:element name="IDL_Type"      type="xsd:string"/>
        <xsd:element name="IDL_Size"      minOccurs="0"     type="xsd:string"/>
        <xsd:element name="Units"         type="xsd:string"/>
        <xsd:element name="Count"         type="xsd:positiveInteger"/>
        <xsd:element name="Enumeration"   minOccurs="0" maxOccurs="1" type="xsd:string"/>
    </xsd:choice>
 </xsd:complexType>

 <xsd:complexType name="commandType">
   <xsd:choice maxOccurs="unbounded">
      <xsd:element   name="Subsystem"     type="xsd:string"/>
      <xsd:element   name="Version"       type="version"/>
      <xsd:element   name="Author"        type="xsd:string"/>
      <xsd:element   name="EFDB_Topic"    type="xsd:string"/>
      <xsd:element   name="Alias"         type="xsd:string"/>
      <xsd:element   name="Device"        type="xsd:string"/>
      <xsd:element   name="Property"      type="xsd:string"/>
      <xsd:element   name="Action"        type="xsd:string"/>
      <xsd:element   name="Value"         type="xsd:string"/>
      <xsd:element   name="Description"   minOccurs="0" maxOccurs="1"    type="xsd:string"/>
      <xsd:element   name="Explanation"   minOccurs="0" maxOccurs="1"  type="xsd:anyURI"/>
      <xsd:element   name="item"          minOccurs="0" maxOccurs="unbounded" type="commandItemType"/>
   </xsd:choice>
 </xsd:complexType>


 <xsd:complexType name="commandSetType">
 <xsd:sequence>
    <xsd:element name="Enumeration"  minOccurs="0" maxOccurs="unbounded" type="xsd:string"/>
    <xsd:element name="SALCommand"   minOccurs="1" maxOccurs="unbounded" type="commandType"/>
 </xsd:sequence>
 </xsd:complexType>

 <xsd:attribute name="updateDate"    type="xsd:date"/>

 <xsd:simpleType name="version">
    <xsd:restriction base="xsd:token">
      <xsd:pattern value="\d+\.\d+(\.\d+)?"/>
    </xsd:restriction>
 </xsd:simpleType>

</xsd:schema>

=== lsst-ts/ts_xml/sal_interfaces/GenericCamera/GenericCamera_Commands.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="http://lsst-sal.tuc.noao.edu/schema/SALCommandSet.xsl"?>
<SALCommandSet xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://lsst-sal.tuc.noao.edu/schema/SALCommandSet.xsd">
  <SALCommand>
    <Subsystem>GenericCamera</Subsystem>
    <EFDB_Topic>GenericCamera_command_setROI</EFDB_Topic>
    <item>
      <EFDB_Name>topPixel</EFDB_Name>
      <Description>This is the regions top most pixel number (base 0).</Description>
      <IDL_Type>int</IDL_Type>
      <Units>pixel</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>leftPixel</EFDB_Name>
      <Description>This is the regions left most pixel number (base 0).</Description>
      <IDL_Type>int</IDL_Type>
      <Units>pixel</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>width</EFDB_Name>
      <Description>This is the regions width in pixels.</Description>
      <IDL_Type>int</IDL_Type>
      <Units>pixel</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>height</EFDB_Name>
      <Description>This is the regions height in pixels.</Description>
      <IDL_Type>int</IDL_Type>
      <Units>pixel</Units>
      <Count>1</Count>
    </item>
  </SALCommand>
  <SALCommand>
    <Subsystem>GenericCamera</Subsystem>
    <EFDB_Topic>GenericCamera_command_setFullFrame</EFDB_Topic>
    <item>
      <EFDB_Name>ignored</EFDB_Name>
      <Description>This value is ignored.</Description>
      <IDL_Type>boolean</IDL_Type>
      <Units>unitless</Units>
      <Count>1</Count>
    </item>
  </SALCommand>
  <SALCommand>
    <Subsystem>GenericCamera</Subsystem>
    <EFDB_Topic>GenericCamera_command_startLiveView</EFDB_Topic>
    <item>
      <EFDB_Name>expTime</EFDB_Name>
      <Description>Exposure time.</Description>
      <IDL_Type>double</IDL_Type>
      <Units>second</Units>
      <Count>1</Count>
    </item>
  </SALCommand>
  <SALCommand>
    <Subsystem>GenericCamera</Subsystem>
    <EFDB_Topic>GenericCamera_command_stopLiveView</EFDB_Topic>
    <item>
      <EFDB_Name>ignored</EFDB_Name>
      <Description>This value is ignored.</Description>
      <IDL_Type>boolean</IDL_Type>
      <Units>unitless</Units>
      <Count>1</Count>
    </item>
  </SALCommand>
  <SALCommand>
    <Subsystem>GenericCamera</Subsystem>
    <EFDB_Topic>GenericCamera_command_takeImages</EFDB_Topic>
    <item>
      <EFDB_Name>numImages</EFDB_Name>
      <Description>Number of consecutive images to take</Description>
      <IDL_Type>long</IDL_Type>
      <Units>unitless</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>expTime</EFDB_Name>
      <Description>Exposure time</Description>
      <IDL_Type>double</IDL_Type>
      <Units>second</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>shutter</EFDB_Name>
      <Description>True if the shutter should be opened/closed</Description>
      <IDL_Type>boolean</IDL_Type>
      <Units>unitless</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>sensors</EFDB_Name>
      <Description>Sensors to be read out, if blank all configured sensors will be read out</Description>
      <IDL_Type>string</IDL_Type>
      <IDL_Size>1</IDL_Size>
      <Units>unitless</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>keyValueMap</EFDB_Name>
      <Description>Map of additional key value pairs to associate extra data with the image(s), e.g. imageType: XYZ, groupId: ABC</Description>
      <IDL_Type>string</IDL_Type>
      <IDL_Size>1</IDL_Size>
      <Units>unitless</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>obsNote</EFDB_Name>
      <Description>An arbitrary operator provided string, useful for informally flagging images</Description>
      <IDL_Type>string</IDL_Type>
      <IDL_Size>1</IDL_Size>
      <Units>unitless</Units>
      <Count>1</Count>
    </item>
  </SALCommand>
</SALCommandSet>

=== lsst-ts/ts_xml/sal_interfaces/dome/domeTHCS_Commands.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="http://lsst-sal.tuc.noao.edu/schema/SALCommandSet.xsl"?>
<SALCommandSet xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="http://lsst-sal.tuc.noao.edu/schema/SALCommandSet.xsd">

<SALCommand>
 <Subsystem>domeTHCS</Subsystem>
 <Version>1.0.0</Version>
 <Author>ebragante</Author>
 <EFDB_Topic>domeTHCS_command_Echo</EFDB_Topic>
 <Alias>Echo</Alias>
 <Device>adb</Device>
 <Property></Property>
 <Action></Action>
 <Value></Value>
 <Explanation></Explanation>
    <item>
      <EFDB_Name>status</EFDB_Name>
      <Description> </Description>
       <IDL_Type>int</IDL_Type>
      <Units> </Units>
      <Count>1</Count>
    </item>
</SALCommand>

</SALCommandSet>

=== lsst-ts/ts_xml/sal_interfaces/Sequencer/Sequencer_Commands.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="http://lsst-sal.tuc.noao.edu/schema/SALCommandSet.xsl"?>
<SALCommandSet xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="http://lsst-sal.tuc.noao.edu/schema/SALCommandSet.xsd">

 <SALCommand>
  <Subsystem>Sequencer</Subsystem>
  <Version>3.8.0</Version>
  <Author>salgenerator</Author>
  <EFDB_Topic>Sequencer_command_sequence</EFDB_Topic>
  <Alias>sequence</Alias>
  <Device>sequence</Device>
  <Property></Property>
  <Action></Action>
  <Value></Value>
  <Explanation>http://sal.lsst.org/SAL/Commands/Sequencer_command_sequence.html</Explanation>
   <item>
    <EFDB_Name>command</EFDB_Name>
    <Description></Description>
    <IDL_Type>string</IDL_Type>
    <IDL_Size>256</IDL_Size>
    <Units></Units>
    <Count>1</Count>
   </item>
 </SALCommand>

 <SALCommand>
  <Subsystem>Sequencer</Subsystem>
  <Version>3.8.0</Version>
  <Author>salgenerator</Author>
  <EFDB_Topic>Sequencer_command_script</EFDB_Topic>
  <Alias>script</Alias>
  <Device>script</Device>
  <Property></Property>
  <Action></Action>
  <Value></Value>
  <Explanation>http://sal.lsst.org/SAL/Commands/Sequencer_command_script.html</Explanation>
   <item>
    <EFDB_Name>location</EFDB_Name>
    <Description></Description>
    <IDL_Type>string</IDL_Type>
    <IDL_Size>256</IDL_Size>
    <Units></Units>
    <Count>1</Count>
   </item>
 </SALCommand>
</SALCommandSet>

=== lsst-ts/ts_xml/sal_interfaces/Watcher/Watcher_Commands.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="http://lsst-sal.tuc.noao.edu/schema/SALCommandSet.xsl"?>
<SALCommandSet xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="http://lsst-sal.tuc.noao.edu/schema/SALCommandSet.xsd">

<SALCommand>
    <Subsystem>Watcher</Subsystem>
    <Version>1.0.0</Version>
    <Author></Author>
    <EFDB_Topic>Watcher_command_acknowledge</EFDB_Topic>
    <Alias>acknowledge</Alias>
    <Device></Device>
    <Property></Property>
    <Action></Action>
    <Value></Value>
    <Description>Acknowledge an alarm.</Description>
    <item>
        <EFDB_Name>name</EFDB_Name>
        <Description>Name of alarm or alarms to acknowledge. Specify a regular expression to acknowledge multiple alarms.</Description>
        <IDL_Type>string</IDL_Type>
        <IDL_Size>1</IDL_Size>
        <Units>unitless</Units>
        <Count>1</Count>
    </item>
    <item>
        <EFDB_Name>severity</EFDB_Name>
        <Description>Severity level being acknowledged. An AlarmSeverity enum.</Description>
        <IDL_Type>int</IDL_Type>
        <Units>unitless</Units>
        <Count>1</Count>
    </item>
    <item>
        <EFDB_Name>acknowledgedBy</EFDB_Name>
        <Description>User who acknowledged the alarm.</Description>
        <IDL_Type>string</IDL_Type>
        <IDL_Size>1</IDL_Size>
        <Units>unitless</Units>
        <Count>1</Count>
    </item>
</SALCommand>

<SALCommand>
    <Subsystem>Watcher</Subsystem>
    <Version>1.0.0</Version>
    <Author></Author>
    <EFDB_Topic>Watcher_command_mute</EFDB_Topic>
    <Alias>mute</Alias>
    <Device></Device>
    <Property></Property>
    <Action></Action>
    <Value></Value>
    <Description>Mute an alarm.</Description>
    <item>
        <EFDB_Name>name</EFDB_Name>
        <Description>Name of alarm or alarms to mute.</Description>
        <IDL_Type>string</IDL_Type>
        <IDL_Size>1</IDL_Size>
        <Units>unitless</Units>
        <Count>1</Count>
    </item>
    <item>
        <EFDB_Name>duration</EFDB_Name>
        <Description>Duration of mute.</Description>
        <IDL_Type>float</IDL_Type>
        <Units>second</Units>
        <Count>1</Count>
    </item>
    <item>
        <EFDB_Name>severity</EFDB_Name>
        <Description>Severity level being muted. An AlarmSeverity enum.</Description>
        <IDL_Type>int</IDL_Type>
        <Units>unitless</Units>
        <Count>1</Count>
    </item>
    <item>
        <EFDB_Name>mutedBy</EFDB_Name>
        <Description>User who muted the alarm.</Description>
        <IDL_Type>string</IDL_Type>
        <IDL_Size>1</IDL_Size>
        <Units>unitless</Units>
        <Count>1</Count>
    </item>
</SALCommand>

</SALCommandSet>

=== lsst-ts/ts_xml/sal_interfaces/MTHexapod/MTHexapod_Commands.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="http://lsst-sal.tuc.noao.edu/schema/SALCommandSet.xsl"?>
<SALCommandSet xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://lsst-sal.tuc.noao.edu/schema/SALCommandSet.xsd">
  <SALCommand>
    <Subsystem>MTHexapod</Subsystem>
    <EFDB_Topic>MTHexapod_command_clearError</EFDB_Topic>
    <Description>Clear the fault state.</Description>
  </SALCommand>
  <SALCommand>
    <Subsystem>MTHexapod</Subsystem>
    <EFDB_Topic>MTHexapod_command_configureAcceleration</EFDB_Topic>
    <Description>Set the acceleration for all struts.</Description>
    <item>
      <EFDB_Name>acceleration</EFDB_Name>
      <Description>Strut acceleration.</Description>
      <IDL_Type>double</IDL_Type>
      <Units>um/s2</Units>
      <Count>1</Count>
    </item>
  </SALCommand>
  <SALCommand>
    <Subsystem>MTHexapod</Subsystem>
    <EFDB_Topic>MTHexapod_command_configureLimits</EFDB_Topic>
    <Description>Set position and orientation limits.</Description>
    <item>
      <EFDB_Name>maxXY</EFDB_Name>
      <Description>Maximum |X| and |Y|</Description>
      <IDL_Type>double</IDL_Type>
      <Units>um</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>minZ</EFDB_Name>
      <Description>Minimum Z</Description>
      <IDL_Type>double</IDL_Type>
      <Units>um</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>maxZ</EFDB_Name>
      <Description>Maximum Z</Description>
      <IDL_Type>double</IDL_Type>
      <Units>um</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>maxUV</EFDB_Name>
      <Description>Maximum |U| and |V|</Description>
      <IDL_Type>double</IDL_Type>
      <Units>deg</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>minW</EFDB_Name>
      <Description>Minimum W</Description>
      <IDL_Type>double</IDL_Type>
      <Units>deg</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>maxW</EFDB_Name>
      <Description>Maximum W</Description>
      <IDL_Type>double</IDL_Type>
      <Units>deg</Units>
      <Count>1</Count>
    </item>
  </SALCommand>
  <SALCommand>
    <Subsystem>MTHexapod</Subsystem>
    <EFDB_Topic>MTHexapod_command_configureVelocity</EFDB_Topic>
    <Description>Set velocity limits for position and orientation.</Description>
    <item>
      <EFDB_Name>xy</EFDB_Name>
      <Description>Maximum velocity for X and Y</Description>
      <IDL_Type>double</IDL_Type>
      <Units>um/s</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>z</EFDB_Name>
      <Description>Maximum velocity for Z</Description>
      <IDL_Type>double</IDL_Type>
      <Units>um/s</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>uv</EFDB_Name>
      <Description>Maximum velocity for U and V</Description>
      <IDL_Type>double</IDL_Type>
      <Units>deg/s</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>w</EFDB_Name>
      <Description>Maximum velocity for W</Description>
      <IDL_Type>double</IDL_Type>
      <Units>deg/s</Units>
      <Count>1</Count>
    </item>
  </SALCommand>
  <SALCommand>
    <Subsystem>MTHexapod</Subsystem>
    <EFDB_Topic>MTHexapod_command_move</EFDB_Topic>
    <Description>Move the Hexapod to a specified position and orientation. This sets the uncompensated position; if compensation is enabled, the actual position will be slightly different.</Description>
    <item>
      <EFDB_Name>x</EFDB_Name>
      <Description>x position</Description>
      <IDL_Type>double</IDL_Type>
      <Units>um</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>y</EFDB_Name>
      <Description>y position</Description>
      <IDL_Type>double</IDL_Type>
      <Units>um</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>z</EFDB_Name>
      <Description>z position</Description>
      <IDL_Type>double</IDL_Type>
      <Units>um</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>u</EFDB_Name>
      <Description>Rotation about x</Description>
      <IDL_Type>double</IDL_Type>
      <Units>deg</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>v</EFDB_Name>
      <Description>Rotation about y</Description>
      <IDL_Type>double</IDL_Type>
      <Units>deg</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>w</EFDB_Name>
      <Description>Rotation about z</Description>
      <IDL_Type>double</IDL_Type>
      <Units>deg</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>sync</EFDB_Name>
      <Description>Synchronize motion so that all actuators start and stop moving at the same time? Synchronize motion is our normal operating mode.</Description>
      <IDL_Type>boolean</IDL_Type>
      <Units>dimensionless</Units>
      <Count>1</Count>
    </item>
  </SALCommand>
  <SALCommand>
    <Subsystem>MTHexapod</Subsystem>
    <EFDB_Topic>MTHexapod_command_offset</EFDB_Topic>
    <Description>Offset the Hexapod by a specified change in position and orientation.</Description>
    <item>
      <EFDB_Name>x</EFDB_Name>
      <Description>Offset in x</Description>
      <IDL_Type>double</IDL_Type>
      <Units>um</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>y</EFDB_Name>
      <Description>Offset in y</Description>
      <IDL_Type>double</IDL_Type>
      <Units>um</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>z</EFDB_Name>
      <Description>Offset in z</Description>
      <IDL_Type>double</IDL_Type>
      <Units>um</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>u</EFDB_Name>
      <Description>Offset of rotation about x</Description>
      <IDL_Type>double</IDL_Type>
      <Units>deg</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>v</EFDB_Name>
      <Description>Offset of rotation about y</Description>
      <IDL_Type>double</IDL_Type>
      <Units>deg</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>w</EFDB_Name>
      <Description>Offset of rotation about z</Description>
      <IDL_Type>double</IDL_Type>
      <Units>deg</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>sync</EFDB_Name>
      <Description>Synchronize motion so that all actuators start and stop moving at the same time? Synchronize motion is our normal operating mode.</Description>
      <IDL_Type>boolean</IDL_Type>
      <Units>dimensionless</Units>
      <Count>1</Count>
    </item>
  </SALCommand>
  <SALCommand>
    <Subsystem>MTHexapod</Subsystem>
    <EFDB_Topic>MTHexapod_command_setCompensationMode</EFDB_Topic>
    <Description>Enable or disable automatic compensation for telescope elevation, etc.</Description>
    <item>
      <EFDB_Name>enable</EFDB_Name>
      <Description>Enable or disable automatic compensation?</Description>
      <IDL_Type>boolean</IDL_Type>
      <Units>dimensionless</Units>
      <Count>1</Count>
    </item>
  </SALCommand>
  <SALCommand>
    <Subsystem>MTHexapod</Subsystem>
    <EFDB_Topic>MTHexapod_command_setPivot</EFDB_Topic>
    <Description>Specify the location of pivot point (the reference point whose position and orientation are specified by the move and offset commands). The origin is the center of the base plate interface plane and +Z points away from the motion plate (see LTS-206 section 2.2).</Description>
    <item>
      <EFDB_Name>x</EFDB_Name>
      <Description>x</Description>
      <IDL_Type>double</IDL_Type>
      <Units>um</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>y</EFDB_Name>
      <Description>y</Description>
      <IDL_Type>double</IDL_Type>
      <Units>um</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>z</EFDB_Name>
      <Description>z</Description>
      <IDL_Type>double</IDL_Type>
      <Units>um</Units>
      <Count>1</Count>
    </item>
  </SALCommand>
  <SALCommand>
    <Subsystem>MTHexapod</Subsystem>
    <EFDB_Topic>MTHexapod_command_stop</EFDB_Topic>
    <Description>Stop motion.</Description>
  </SALCommand>
</SALCommandSet>

=== lsst-ts/ts_xml/sal_interfaces/atArchiver/atArchiver_Commands.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="http://project.lsst.org/ts/sal_objects/schema/SALCommandSet.xsl"?>
<SALCommandSet xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="http://project.lsst.org/ts/sal_objects/schema/SALCommandSet.xsd">
<SALCommand>
    <Subsystem>atArchiver</Subsystem>
    <Version>3.7.1</Version>
    <Author>Htut Khine Win(hwin16@illinois.edu)</Author>
    <EFDB_Topic>atArchiver_command_abort</EFDB_Topic>
    <Alias>abort</Alias>
    <Device></Device>
    <Property></Property>
    <Action></Action>
    <Value></Value>
    <Explanation>http://project.lsst.org/ts/sal_objects/help</Explanation>
    <item>
        <EFDB_Name>state</EFDB_Name>
        <Description></Description>
        <IDL_Type>boolean</IDL_Type>
        <Units></Units>
        <Count>1</Count>
    </item>
</SALCommand>
<SALCommand>
    <Subsystem>atArchiver</Subsystem>
    <Version>3.7.1</Version>
    <Author></Author>
    <EFDB_Topic>atArchiver_command_enable</EFDB_Topic>
    <Alias>enable</Alias>
    <Device></Device>
    <Property></Property>
    <Action></Action>
    <Value></Value>
    <Explanation>http://project.lsst.org/ts/sal_objects/help</Explanation>
    <item>
        <EFDB_Name>state</EFDB_Name>
        <Description></Description>
        <IDL_Type>boolean</IDL_Type>
        <Units></Units>
        <Count>1</Count>
    </item>
</SALCommand>
<SALCommand>
    <Subsystem>atArchiver</Subsystem>
    <Version>3.7.1</Version>
    <Author></Author>
    <EFDB_Topic>atArchiver_command_disable</EFDB_Topic>
    <Alias>disable</Alias>
    <Device></Device>
    <Property></Property>
    <Action></Action>
    <Value></Value>
    <Explanation>http://project.lsst.org/ts/sal_objects/help</Explanation>
    <item>
        <EFDB_Name>state</EFDB_Name>
        <Description></Description>
        <IDL_Type>boolean</IDL_Type>
        <Units></Units>
        <Count>1</Count>
    </item>
</SALCommand>
<SALCommand>
    <Subsystem>atArchiver</Subsystem>
    <Version>3.7.1</Version>
    <Author></Author>
    <EFDB_Topic>atArchiver_command_standby</EFDB_Topic>
    <Alias>standby</Alias>
    <Device></Device>
    <Property></Property>
    <Action></Action>
    <Value></Value>
    <Explanation>http://project.lsst.org/ts/sal_objects/help</Explanation>
    <item>
        <EFDB_Name>state</EFDB_Name>
        <Description></Description>
        <IDL_Type>boolean</IDL_Type>
        <Units></Units>
        <Count>1</Count>
    </item>
</SALCommand>
<SALCommand>
    <Subsystem>atArchiver</Subsystem>
    <Version>3.7.1</Version>
    <Author></Author>
    <EFDB_Topic>atArchiver_command_exitControl</EFDB_Topic>
    <Alias>exitControl</Alias>
    <Device></Device>
    <Property></Property>
    <Action></Action>
    <Value></Value>
    <Explanation>http://project.lsst.org/ts/sal_objects/help</Explanation>
    <item>
        <EFDB_Name>state</EFDB_Name>
        <Description></Description>
        <IDL_Type>boolean</IDL_Type>
        <Units></Units>
        <Count>1</Count>
    </item>
</SALCommand>
<SALCommand>
    <Subsystem>atArchiver</Subsystem>
    <Version>3.7.1</Version>
    <Author></Author>
    <EFDB_Topic>atArchiver_command_start</EFDB_Topic>
    <Alias>start</Alias>
    <Device></Device>
    <Property></Property>
    <Action></Action>
    <Value></Value>
    <Explanation>http://project.lsst.org/ts/sal_objects/help</Explanation>
    <item>
        <EFDB_Name>configuration</EFDB_Name>
        <Description></Description>
        <IDL_Type>string</IDL_Type>
        <IDL_Size>256</IDL_Size>
        <Units></Units>
        <Count>1</Count>
    </item>
</SALCommand>
<SALCommand>
    <Subsystem>atArchiver</Subsystem>
    <Version>3.7.1</Version>
    <Author>Htut Khine Win(hwin16@illinois.edu)</Author>
    <EFDB_Topic>atArchiver_command_enterControl</EFDB_Topic>
    <Alias>enterControl</Alias>
    <Device></Device>
    <Property></Property>
    <Action></Action>
    <Value></Value>
    <Explanation>http://project.lsst.org/ts/sal_objects/help</Explanation>
    <item>
        <EFDB_Name>state</EFDB_Name>
        <Description></Description>
        <IDL_Type>boolean</IDL_Type>
        <Units></Units>
        <Count>1</Count>
    </item>
</SALCommand>
<SALCommand>
    <Subsystem>atArchiver</Subsystem>
    <Version>3.7.1</Version>
    <Author></Author>
    <EFDB_Topic>atArchiver_command_setValue</EFDB_Topic>
    <Alias>setValue</Alias>
    <Device></Device>
    <Property></Property>
    <Action></Action>
    <Value></Value>
    <Explanation>http://project.lsst.org/ts/sal_objects/help</Explanation>
    <item>
        <EFDB_Name>json_parameters</EFDB_Name>
        <Description></Description>
        <IDL_Type>string</IDL_Type>
        <IDL_Size>256</IDL_Size>
        <Units></Units>
        <Count>1</Count>
    </item>
</SALCommand>
<SALCommand>
    <Subsystem>atArchiver</Subsystem>
    <Version>3.7.1</Version>
    <Author></Author>
    <EFDB_Topic>atArchiver_command_resetFromFault</EFDB_Topic>
    <Alias>resetFromFault</Alias>
    <Device></Device>
    <Property></Property>
    <Action></Action>
    <Value></Value>
    <Explanation>http://project.lsst.org/ts/sal_objects/help</Explanation>
</SALCommand></SALCommandSet>

=== lsst-ts/ts_xml/sal_interfaces/LinearStage/LinearStage_Commands.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="http://lsst-sal.tuc.noao.edu/schema/SALCommandSet.xsl"?>
<SALCommandSet xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://lsst-sal.tuc.noao.edu/schema/SALCommandSet.xsd">
  <SALCommand>
    <Subsystem>LinearStage</Subsystem>
    <Version>3.7.1</Version>
    <Author>ecoughlin</Author>
    <EFDB_Topic>LinearStage_command_moveRelative</EFDB_Topic>
    <Alias>moveRelative</Alias>
    <Device/>
    <Property/>
    <Action/>
    <Value/>
    <Explanation>http://sal.lsst.org</Explanation>
    <item>
      <EFDB_Name>distance</EFDB_Name>
      <Description>The amount of millimeters to move the stage.</Description>
      <IDL_Type>float</IDL_Type>
      <Units>millimeter</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>timestamp</EFDB_Name>
      <Description>The timestamp for when the event occurred.</Description>
      <IDL_Type>double</IDL_Type>
      <Units>second</Units>
      <Count>1</Count>
    </item>
  </SALCommand>
  <SALCommand>
    <Subsystem>LinearStage</Subsystem>
    <Version>3.7.1</Version>
    <Author>ecoughlin</Author>
    <EFDB_Topic>LinearStage_command_moveAbsolute</EFDB_Topic>
    <Alias>moveAbsolute</Alias>
    <Device/>
    <Property/>
    <Action/>
    <Value/>
    <Explanation>http://sal.lsst.org</Explanation>
    <item>
      <EFDB_Name>distance</EFDB_Name>
      <Description>The amount to move the device</Description>
      <IDL_Type>float</IDL_Type>
      <Units>millimeter</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>timestamp</EFDB_Name>
      <Description>The timestamp for when the event occurred.</Description>
      <IDL_Type>double</IDL_Type>
      <Units>second</Units>
      <Count>1</Count>
    </item>
  </SALCommand>
  <SALCommand>
    <Subsystem>LinearStage</Subsystem>
    <Version>3.7.1</Version>
    <Author>ecoughlin</Author>
    <EFDB_Topic>LinearStage_command_getHome</EFDB_Topic>
    <Alias>getHome</Alias>
    <Device/>
    <Property/>
    <Action/>
    <Value/>
    <Explanation>http://sal.lsst.org</Explanation>
    <item>
      <EFDB_Name>value</EFDB_Name>
      <Description>Attribute required by the SAL API, but is unused.</Description>
      <IDL_Type>boolean</IDL_Type>
      <Units>unitless</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>timestamp</EFDB_Name>
      <Description>The timestamp for when the event occurred.</Description>
      <IDL_Type>double</IDL_Type>
      <Units>second</Units>
      <Count>1</Count>
    </item>
  </SALCommand>
  <SALCommand>
    <Subsystem>LinearStage</Subsystem>
    <Version>3.7.1</Version>
    <Author>ecoughlin</Author>
    <EFDB_Topic>LinearStage_command_stop</EFDB_Topic>
    <Alias>stop</Alias>
    <Device/>
    <Property/>
    <Action/>
    <Value/>
    <Explanation>http://sal.lsst.org</Explanation>
    <item>
      <EFDB_Name>value</EFDB_Name>
      <Description>Attribute required by SAL API, but is unused.</Description>
      <IDL_Type>boolean</IDL_Type>
      <Units>unitless</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>timestamp</EFDB_Name>
      <Description>The timestamp for when the event occurred.</Description>
      <IDL_Type>double</IDL_Type>
      <Units>second</Units>
      <Count>1</Count>
    </item>
  </SALCommand>
</SALCommandSet>
