=== lsst-ts/ts_xml/schema/SALEventSet.xsd
<xsd:schema attributeFormDefault="unqualified" elementFormDefault="unqualified" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <xsd:annotation>
        <xsd:documentation xml:lang="en">SAL Event data item schema for LSST
    </xsd:documentation>
    </xsd:annotation>
    <xsd:element name="SALEventSet" type="eventSetType"/>
    <xsd:element name="SALEvent" type="eventType"/>
    <xsd:element name="SALEventItem" type="eventItemType"/>
    <xsd:element name="SALEventFileRef" type="eventFileRefType"/>
    <xsd:complexType name="eventItemType">
        <xsd:choice maxOccurs="unbounded">
            <xsd:element name="EFDB_Name" type="xsd:string"/>
            <xsd:element name="Description" type="xsd:string"/>
            <xsd:element name="IDL_Type" type="xsd:string"/>
            <xsd:element minOccurs="0" name="IDL_Size" type="xsd:string"/>
            <xsd:element name="Units" type="xsd:string"/>
            <xsd:element name="Count" type="xsd:positiveInteger"/>
            <xsd:element maxOccurs="1" minOccurs="0" name="Explanation" type="xsd:anyURI"/>
            <xsd:element maxOccurs="1" minOccurs="0" name="Enumeration" type="xsd:string"/>
        </xsd:choice>
    </xsd:complexType>
    <xsd:complexType name="eventType">
        <xsd:sequence>
            <xsd:element maxOccurs="1" minOccurs="1" name="Subsystem" type="xsd:string"/>
            <xsd:element maxOccurs="1" minOccurs="0" name="Version" type="version"/>
            <xsd:element maxOccurs="1" minOccurs="0" name="Author" type="xsd:string"/>
            <xsd:element maxOccurs="1" minOccurs="1" name="EFDB_Topic" type="xsd:string"/>
            <xsd:element maxOccurs="1" minOccurs="0" name="Alias" type="xsd:string"/>
            <xsd:element maxOccurs="1" minOccurs="0" name="Enumeration" type="xsd:string"/>
            <xsd:element maxOccurs="1" minOccurs="0" name="Description" type="xsd:string"/>
            <xsd:element maxOccurs="1" minOccurs="0" name="Explanation" type="xsd:anyURI"/>
            <xsd:element maxOccurs="unbounded" minOccurs="0" name="item" type="eventItemType"/>
            <xsd:element maxOccurs="1" minOccurs="0" name="File_Reference" type="eventFileRefType"/>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="eventSetType">
        <xsd:sequence>
            <xsd:element maxOccurs="unbounded" minOccurs="0" name="Enumeration" type="xsd:string"/>
            <xsd:element maxOccurs="unbounded" minOccurs="1" name="SALEvent" type="eventType"/>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="eventFileRefType">
        <xsd:choice maxOccurs="unbounded">
            <xsd:element maxOccurs="1" minOccurs="1" name="EFDB_Name" type="xsd:string"/>
            <xsd:element name="Description" type="xsd:string"/>
            <xsd:element maxOccurs="1" minOccurs="1" name="URL" type="xsd:anyURI"/>
            <xsd:element maxOccurs="1" minOccurs="1" name="Generator" type="xsd:string"/>
            <xsd:element maxOccurs="1" minOccurs="1" name="Version" type="version"/>
            <xsd:element maxOccurs="1" minOccurs="1" name="Checksum" type="xsd:string"/>
            <xsd:element name="Mime_Type" type="xsd:string"/>
            <xsd:element name="Byte_Size" type="xsd:positiveInteger"/>
            <xsd:element maxOccurs="1" minOccurs="1" name="ID" type="xsd:string"/>
            <xsd:element maxOccurs="1" minOccurs="0" name="Explanation" type="xsd:anyURI"/>
        </xsd:choice>
    </xsd:complexType>
    <xsd:simpleType name="version">
        <xsd:restriction base="xsd:token">
            <xsd:pattern value="\d+\.\d+(\.\d+)?"/>
        </xsd:restriction>
    </xsd:simpleType>
    <xsd:attribute name="updateDate" type="xsd:date"/>
</xsd:schema>

=== lsst-ts/ts_xml/sal_interfaces/IOTA/IOTA_Events.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="http://lsst-sal.tuc.noao.edu/schema/SALEventSet.xsl"?>
<SALEventSet xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://lsst-sal.tuc.noao.edu/schema/SALEventSet.xsd">
  <Enumeration>DetailedState_DisabledState,DetailedState_EnabledState,DetailedState_FaultState,DetailedState_OfflineState,DetailedState_StandbyState</Enumeration>
  <SALEvent>
    <Subsystem>IOTA</Subsystem>
    <Version>3.8.31</Version>
    <Author/>
    <EFDB_Topic>IOTA_logevent_detailedState</EFDB_Topic>
    <Alias>detailedState</Alias>
    <Explanation>http://sal.lsst.org</Explanation>
    <item>
      <EFDB_Name>detailedState</EFDB_Name>
      <Description>Detailed state.</Description>
      <!-- Enumeration: DetailedState -->
      <IDL_Type>long</IDL_Type>
      <Units>unitless</Units>
      <Count>1</Count>
    </item>
  </SALEvent>
  <SALEvent>
    <Subsystem>IOTA</Subsystem>
    <Version>3.8.31</Version>
    <Author/>
    <EFDB_Topic>IOTA_logevent_internalCommand</EFDB_Topic>
    <Alias>internalCommand</Alias>
    <Explanation>http://sal.lsst.org</Explanation>
    <item>
      <EFDB_Name>commandObject</EFDB_Name>
      <Description>The error code being published.</Description>
      <IDL_Type>byte</IDL_Type>
      <Units>unitless</Units>
      <Count>800</Count>
    </item>
  </SALEvent>
  <SALEvent>
    <Subsystem>IOTA</Subsystem>
    <Version>3.8.31</Version>
    <Author/>
    <EFDB_Topic>IOTA_logevent_loopTimeOutOfRange</EFDB_Topic>
    <Alias>loopTimeOutOfRange</Alias>
    <Explanation>http://sal.lsst.org</Explanation>
    <item>
      <EFDB_Name>loopTimeOutOfRange</EFDB_Name>
      <Description>Loop out of range.</Description>
      <IDL_Type>boolean</IDL_Type>
      <Units>unitless</Units>
      <Count>1</Count>
    </item>
  </SALEvent>
  <SALEvent>
    <Subsystem>IOTA</Subsystem>
    <Version>3.8.31</Version>
    <Author/>
    <EFDB_Topic>IOTA_logevent_rejectedCommand</EFDB_Topic>
    <Alias>rejectedCommand</Alias>
    <Explanation>http://sal.lsst.org</Explanation>
    <item>
      <EFDB_Name>command</EFDB_Name>
      <Description>Rejected command.</Description>
      <IDL_Type>string</IDL_Type>
      <IDL_Size>1</IDL_Size>
      <Units>unitless</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>state</EFDB_Name>
      <Description>Current state.</Description>
      <IDL_Type>string</IDL_Type>
      <IDL_Size>1</IDL_Size>
      <Units>unitless</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>timestamp</EFDB_Name>
      <Description>Timestamp for when the command was rejected.</Description>
      <IDL_Type>double</IDL_Type>
      <Units>unitless</Units>
      <Count>1</Count>
    </item>
  </SALEvent>
</SALEventSet>

=== lsst-ts/ts_xml/sal_interfaces/MTAirCompressor/MTAirCompressor_Events.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="http://lsst-sal.tuc.noao.edu/schema/SALEventSet.xsl"?>
<SALEventSet xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://lsst-sal.tuc.noao.edu/schema/SALEventSet.xsd">
  <Enumeration>
    SummaryStates_DisabledState=1,
    SummaryStates_EnabledState=2,
    SummaryStates_FaultState=3,
    SummaryStates_OfflineState=4,
    SummaryStates_StandbyState=5
  </Enumeration>
  <SALEvent>
    <Subsystem>MTAirCompressor</Subsystem>
    <EFDB_Topic>MTAirCompressor_logevent_status</EFDB_Topic>
    <item>
      <EFDB_Name>readyToStart</EFDB_Name>
      <Description>Compressor can be started.</Description>
      <IDL_Type>boolean</IDL_Type>
      <Units>unitless</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>operating</EFDB_Name>
      <Description>Compressor is operating.</Description>
      <IDL_Type>boolean</IDL_Type>
      <Units>unitless</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>startInhibit</EFDB_Name>
      <Description>Start is inhibited.</Description>
      <IDL_Type>boolean</IDL_Type>
      <Units>unitless</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>motorStartPhase</EFDB_Name>
      <Description>Motor is being started.</Description>
      <IDL_Type>boolean</IDL_Type>
      <Units>unitless</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>offLoad</EFDB_Name>
      <Description>??</Description>
      <IDL_Type>boolean</IDL_Type>
      <Units>unitless</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>onLoad</EFDB_Name>
      <Description>??</Description>
      <IDL_Type>boolean</IDL_Type>
      <Units>unitless</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>softStop</EFDB_Name>
      <Description>Soft stop was initiated.</Description>
      <IDL_Type>boolean</IDL_Type>
      <Units>unitless</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>runOnTimer</EFDB_Name>
      <Description>Compressor power on/off is being managed by timer.</Description>
      <IDL_Type>boolean</IDL_Type>
      <Units>unitless</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>fault</EFDB_Name>
      <Description>Fault detected</Description>
      <IDL_Type>boolean</IDL_Type>
      <Units>unitless</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>warning</EFDB_Name>
      <Description>Warning detected.</Description>
      <IDL_Type>boolean</IDL_Type>
      <Units>unitless</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>serviceRequired</EFDB_Name>
      <Description>Compressor service is required.</Description>
      <IDL_Type>boolean</IDL_Type>
      <Units>unitless</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>minAllowedSpeedAchieved</EFDB_Name>
      <Description>Minimal allowed speed achieved.</Description>
      <IDL_Type>boolean</IDL_Type>
      <Units>unitless</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>maxAllowedSpeedAchieved</EFDB_Name>
      <Description>Maximal allowed speed achieved.</Description>
      <IDL_Type>boolean</IDL_Type>
      <Units>unitless</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>startByRemote</EFDB_Name>
      <Description>Started by remote operation.</Description>
      <IDL_Type>boolean</IDL_Type>
      <Units>unitless</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>startWithTimerControl</EFDB_Name>
      <Description>Started with timer control.</Description>
      <IDL_Type>boolean</IDL_Type>
      <Units>unitless</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>startWithPressureRequirement</EFDB_Name>
      <Description>Started with pressure requirement.</Description>
      <IDL_Type>boolean</IDL_Type>
      <Units>unitless</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>startAfterDePressurise</EFDB_Name>
      <Description>Started after de-pressurise.</Description>
      <IDL_Type>boolean</IDL_Type>
      <Units>unitless</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>startAfterPowerLoss</EFDB_Name>
      <Description>Started after power loss.</Description>
      <IDL_Type>boolean</IDL_Type>
      <Units>unitless</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>startAfterDryerPreRun</EFDB_Name>
      <Description>Started after dryer per-run.</Description>
      <IDL_Type>boolean</IDL_Type>
      <Units>unitless</Units>
      <Count>1</Count>
    </item>
  </SALEvent>
  <SALEvent>
    <Subsystem>MTAirCompressor</Subsystem>
    <EFDB_Topic>MTAirCompressor_logevent_compressorInfo</EFDB_Topic>
    <item>
      <EFDB_Name>softwareVersion</EFDB_Name>
      <Description>Compressor's software version.</Description>
      <IDL_Type>string</IDL_Type>
      <IDL_Size>14</IDL_Size>
      <Units>unitless</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>serialNumber</EFDB_Name>
      <Description>Compressor's serial number.</Description>
      <IDL_Type>string</IDL_Type>
      <IDL_Size>9</IDL_Size>
      <Units>unitless</Units>
      <Count>1</Count>
    </item>
  </SALEvent>
  <SALEvent>
    <Subsystem>MTAirCompressor</Subsystem>
    <EFDB_Topic>MTAirCompressor_logevent_timerInfo</EFDB_Topic>
    <item>
      <EFDB_Name>runningHours</EFDB_Name>
      <Description>How many hours compressor was run.</Description>
      <IDL_Type>int</IDL_Type>
      <Units>hour</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>loadedHours</EFDB_Name>
      <Description>How many hours compressor was loaded.</Description>
      <IDL_Type>int</IDL_Type>
      <Units>hour</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>lowestServiceCounter</EFDB_Name>
      <Description>Lowest service counter.</Description>
      <IDL_Type>int</IDL_Type>
      <Units>hour</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>runOnTimer</EFDB_Name>
      <Description>Run-on timer.</Description>
      <IDL_Type>int</IDL_Type>
      <Units>hour</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>loadedHours50Percent</EFDB_Name>
      <Description>Loaded hours 50%.</Description>
      <IDL_Type>int</IDL_Type>
      <Units>hour</Units>
      <Count>1</Count>
    </item>
  </SALEvent>
</SALEventSet>

=== lsst-ts/ts_xml/sal_interfaces/m2ms/m2ms_Events.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="http://lsst-sal.tuc.noao.edu/schema/SALEventSet.xsl"?>
<SALEventSet xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="http://lsst-sal.tuc.noao.edu/schema/SALEventSet.xsd">

<SALEvent>
 <Subsystem>m2ms</Subsystem>
 <Version>3.0</Version>
 <Author>salgenerator</Author>
 <EFDB_Topic>m2ms_logevent_M2SummaryState</EFDB_Topic>
 <Alias>M2SummaryState</Alias>
 <Explanation>http://sal.lsst.org/SAL/Events/m2ms_logevent_M2SummaryState.html</Explanation>
    <item>
      <EFDB_Name>state</EFDB_Name>
      <Description> </Description>
       <IDL_Type>short</IDL_Type>
      <Units> </Units>
      <Count>1</Count>
    </item>
</SALEvent>
<SALEvent>
 <Subsystem>m2ms</Subsystem>
 <Version>3.0</Version>
 <Author>salgenerator</Author>
 <EFDB_Topic>m2ms_logevent_M2DetailedState</EFDB_Topic>
 <Alias>M2DetailedState</Alias>
 <Explanation>http://sal.lsst.org/SAL/Events/m2ms_logevent_M2DetailedState.html</Explanation>
    <item>
      <EFDB_Name>state</EFDB_Name>
      <Description> </Description>
       <IDL_Type>short</IDL_Type>
      <Units> </Units>
      <Count>1</Count>
    </item>
</SALEvent>
<SALEvent>
 <Subsystem>m2ms</Subsystem>
 <Version>3.0</Version>
 <Author>salgenerator</Author>
 <EFDB_Topic>m2ms_logevent_M2FaultState</EFDB_Topic>
 <Alias>M2FaultState</Alias>
 <Explanation>http://sal.lsst.org/SAL/Events/m2ms_logevent_M2FaultState.html</Explanation>
    <item>
      <EFDB_Name>state</EFDB_Name>
      <Description> </Description>
       <IDL_Type>short</IDL_Type>
      <Units> </Units>
      <Enumeration>         ActuatorPlusLimit,ActuatorMinusLimit,ActuatorPlusForceLimit,ActuatorMinusForceLimit,ActuatorCommTimeout,FollowingError,ConfigurationError,UnresponsiveActuator,TangentLinkStrainFault,cRIOCommFailure,cRIOHeartbeatFailure,CurrentError,VoltageError,PowrRelayFault,owerSupplyFault,TemperatureFault, TempSensorFailure,TelescopeElevationault,GravitySensorFailure,ILCFault,CelRBPositionError,DisplacementSensor,ActuatorPlusSoftLimit,ActuatorMinusSoftLimit,CelTemperatureWarning
      </Enumeration>
      <Count>1</Count>
    </item>
</SALEvent>
<SALEvent>
 <Subsystem>m2ms</Subsystem>
 <Version>3.0</Version>
 <Author>salgenerator</Author>
 <EFDB_Topic>m2ms_logevent_M2AssemblyInPosition</EFDB_Topic>
 <Alias>M2AssemblyInPosition</Alias>
 <Explanation>http://sal.lsst.org/SAL/Events/m2ms_logevent_M2AssemblyInPosition.html</Explanation>
    <item>
      <EFDB_Name>inPosition</EFDB_Name>
      <Description> </Description>
       <IDL_Type>boolean</IDL_Type>
      <Units> </Units>
      <Count>1</Count>
    </item>
</SALEvent>
</SALEventSet>

=== lsst-ts/ts_xml/sal_interfaces/ESS/ESS_Events.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="http://lsst-sal.tuc.noao.edu/schema/SALEventSet.xsl"?>
<SALEventSet xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://lsst-sal.tuc.noao.edu/schema/SALEventSet.xsd">
  <SALEvent>
    <Subsystem>ESS</Subsystem>
    <EFDB_Topic>ESS_logevent_lightningStrike</EFDB_Topic>
    <Description>Lightning strikes and high electrical field warnings.</Description>
    <item>
      <EFDB_Name>sensorName</EFDB_Name>
      <Description>The name of the sensor.</Description>
      <IDL_Type>string</IDL_Type>
      <Units>unitless</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>strike</EFDB_Name>
      <Description>Lighting strike alarms, as a mask with numStrikeBits bits. 1 means an alarm is active. Higher-order bits are for strikes that are closer, and thus more worrisome. Each alarm will eventually reset itself if no further activity in that alarm range is detected.</Description>
      <IDL_Type>unsigned short</IDL_Type>
      <IDL_Size>1</IDL_Size>
      <Units>unitless</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>highField</EFDB_Name>
      <Description>High electrical field alarms, as a mask with numHighFieldBits bits. 1 means an alarm is active. Higher-order bits are for larger electrical fields, and thus are more worrisome. Each alarm will eventually reset itself if no further activity in that alarm range is detected</Description>
      <IDL_Type>unsigned short</IDL_Type>
      <IDL_Size>1</IDL_Size>
      <Units>unitless</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>numStrikeBits</EFDB_Name>
      <Description>The maximum number of strike bits.</Description>
      <IDL_Type>unsigned short</IDL_Type>
      <IDL_Size>1</IDL_Size>
      <Units>unitless</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>numHighFieldBits</EFDB_Name>
      <Description>The maximum number of high field bits.</Description>
      <IDL_Type>unsigned short</IDL_Type>
      <IDL_Size>1</IDL_Size>
      <Units>unitless</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>status</EFDB_Name>
      <Description>Device status. The details depend on the device, but 0 always means that no problems have been detected.</Description>
      <IDL_Type>short</IDL_Type>
      <IDL_Size>1</IDL_Size>
      <Units>unitless</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>location</EFDB_Name>
      <Description>The location of the sensor.</Description>
      <IDL_Type>string</IDL_Type>
      <Units>unitless</Units>
      <Count>1</Count>
    </item>
  </SALEvent>
  <SALEvent>
    <Subsystem>ESS</Subsystem>
    <EFDB_Topic>ESS_logevent_precipitation</EFDB_Topic>
    <Description>Is it raining or snowing?</Description>
    <item>
      <EFDB_Name>sensorName</EFDB_Name>
      <Description>The name of the sensor.</Description>
      <IDL_Type>string</IDL_Type>
      <Units>unitless</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>raining</EFDB_Name>
      <Description>Is it raining? (true=yes)</Description>
      <IDL_Type>boolean</IDL_Type>
      <IDL_Size>1</IDL_Size>
      <Units>unitless</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>snowing</EFDB_Name>
      <Description>Is it snowing? (true=yes)</Description>
      <IDL_Type>boolean</IDL_Type>
      <IDL_Size>1</IDL_Size>
      <Units>unitless</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>location</EFDB_Name>
      <Description>The location of the sensor.</Description>
      <IDL_Type>string</IDL_Type>
      <Units>unitless</Units>
      <Count>1</Count>
    </item>
  </SALEvent>
</SALEventSet>

=== lsst-ts/ts_xml/sal_interfaces/MTLaserTracker/MTLaserTracker_Events.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="http://lsst-sal.tuc.noao.edu/schema/SALEventSet.xsl"?>
<SALEventSet xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="http://lsst-sal.tuc.noao.edu/schema/SALEventSet.xsd">
<Enumeration>DetailedState_DisabledState,DetailedState_EnabledState,DetailedState_FaultState,DetailedState_OfflineState,DetailedState_StandbyState</Enumeration>

<SALEvent>
    <Subsystem>MTLaserTracker</Subsystem>
    <Version>3.8.31</Version>
    <Author></Author>
    <EFDB_Topic>MTLaserTracker_logevent_detailedState</EFDB_Topic>
    <Alias>detailedState</Alias>
    <Explanation>http://sal.lsst.org</Explanation>
            <item>
                <EFDB_Name>detailedState</EFDB_Name>
                <Description>Detailed state</Description>
                <!-- Enumeration: DetailedState -->
                <IDL_Type>long</IDL_Type>
                <Units>unitless</Units>
                <Count>1</Count>
            </item>
</SALEvent>
<SALEvent>
    <Subsystem>MTLaserTracker</Subsystem>
    <Version>3.8.31</Version>
    <Author></Author>
    <EFDB_Topic>MTLaserTracker_logevent_heartbeat</EFDB_Topic>
    <Alias>heartbeat</Alias>
    <Explanation>http://sal.lsst.org</Explanation>
    <item>
        <EFDB_Name>heartbeat</EFDB_Name>
        <Description>Heartbeat</Description>
        <IDL_Type>boolean</IDL_Type>
        <Units>unitless</Units>
        <Count>1</Count>
    </item>
</SALEvent>
</SALEventSet>

=== lsst-ts/ts_xml/sal_interfaces/MTEEC/MTEEC_Events.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="http://lsst-sal.tuc.noao.edu/schema/SALEventSet.xsl"?>
<SALEventSet xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="http://lsst-sal.tuc.noao.edu/schema/SALEventSet.xsd">

<SALEvent>
    <Subsystem>MTEEC</Subsystem>
    <Version>3.8</Version>
    <Author></Author>
    <EFDB_Topic>MTEEC_logevent_detailedState</EFDB_Topic>
    <Alias>detailedState</Alias>
    <Explanation>http://sal.lsst.org</Explanation>
            <item>
                <EFDB_Name>detailedState</EFDB_Name>
    	        <Enumeration>NotSetState,DaySetState,NightSetState</Enumeration>    
                <Description>Detailed state.</Description>
                <!-- Enumeration: DetailedState -->
                <IDL_Type>long</IDL_Type>
                <Units>unitless</Units>
                <Count>1</Count>
            </item>
</SALEvent>
<SALEvent>
    <Subsystem>MTEEC</Subsystem>
    <Version>3.8</Version>
    <Author></Author>
    <EFDB_Topic>MTEEC_logevent_heartbeat</EFDB_Topic>
    <Alias>heartbeat</Alias>
    <Explanation>http://sal.lsst.org</Explanation>
    <item>
        <EFDB_Name>heartbeat</EFDB_Name>
        <Description>Heartbeat.</Description>
        <IDL_Type>boolean</IDL_Type>
        <Units>unitless</Units>
        <Count>1</Count>
    </item>
</SALEvent></SALEventSet>

=== lsst-ts/ts_xml/sal_interfaces/MTM1M3TS/MTM1M3TS_Events.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="http://lsst-sal.tuc.noao.edu/schema/SALEventSet.xsl"?>
<SALEventSet xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://lsst-sal.tuc.noao.edu/schema/SALEventSet.xsd">
    <Enumeration>DetailedStates_DisabledState,DetailedStates_EnabledState,DetailedStates_FaultState,DetailedStates_OfflineState,DetailedStates_StandbyState</Enumeration>

    <SALEvent>
        <Subsystem>MTM1M3TS</Subsystem>
        <Version>3.8.35</Version>
        <Author></Author>
        <EFDB_Topic>MTM1M3TS_logevent_appliedSetpoint</EFDB_Topic>
        <Alias>appliedSetpoint</Alias>
        <Explanation>http://sal.lsst.org</Explanation>
        <item>
            <EFDB_Name>setpoint</EFDB_Name>
            <Description>Applied setpoint.</Description>
            <IDL_Type>float</IDL_Type>
            <Units>deg_C</Units>
            <Count>1</Count>
        </item>
    </SALEvent>
    <SALEvent>
        <Subsystem>MTM1M3TS</Subsystem>
        <Version>3.8.35</Version>
        <Author></Author>
        <EFDB_Topic>MTM1M3TS_logevent_detailedState</EFDB_Topic>
        <Alias>detailedState</Alias>
        <Explanation>http://sal.lsst.org</Explanation>
        <item>
            <EFDB_Name>detailedState</EFDB_Name>
            <Description>Detailed state of the CSC</Description>
            <IDL_Type>long</IDL_Type>
            <Units>unitless</Units>
            <Count>1</Count>
        </item>
    </SALEvent>
</SALEventSet>

=== lsst-ts/ts_xml/sal_interfaces/MTM2/MTM2_Events.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="http://lsst-sal.tuc.noao.edu/schema/SALEventSet.xsl"?>
<SALEventSet xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="http://lsst-sal.tuc.noao.edu/schema/SALEventSet.xsd">

<SALEvent>
    <Subsystem>MTM2</Subsystem>
    <EFDB_Topic>MTM2_logevent_m2AssemblyInPosition</EFDB_Topic>
    <Alias>m2AssemblyInPosition</Alias>
    <Description>Indicates when all of the M2 axes are within tolerance of the target positions.</Description>
    <item>
        <EFDB_Name>inPosition</EFDB_Name>
        <Description>True if the M2 assembly is in position.</Description>
        <IDL_Type>boolean</IDL_Type>
        <Units>unitless</Units>
        <Count>1</Count>
    </item>
</SALEvent>

<SALEvent>
    <Subsystem>MTM2</Subsystem>
    <EFDB_Topic>MTM2_logevent_cellTemperatureHiWarning</EFDB_Topic>
    <Alias>cellTemperatureHiWarning</Alias>
    <Description>Indicates if the measured cell temperature is more than the specified value above the conditioned supply air temperature.</Description>
    <item>
        <EFDB_Name>hiWarning</EFDB_Name>
        <Description>True if the cell temperature is high.</Description>
        <IDL_Type>boolean</IDL_Type>
        <Units>unitless</Units>
        <Count>1</Count>
    </item>
</SALEvent>

<SALEvent>
    <Subsystem>MTM2</Subsystem>
    <EFDB_Topic>MTM2_logevent_detailedState</EFDB_Topic>
    <Alias>detailedState</Alias>
    <Description>New detailed state on each summary state transition.</Description>
    <item>
        <EFDB_Name>detailedState</EFDB_Name>
        <Description>M2 detailed state.</Description>
        <IDL_Type>long</IDL_Type>
        <Units>unitless</Units>
        <Count>1</Count>
    </item>
</SALEvent>

<SALEvent>
    <Subsystem>MTM2</Subsystem>
    <EFDB_Topic>MTM2_logevent_commandableByDDS</EFDB_Topic>
    <Alias>commandableByDDS</Alias>
    <Description>Can the commandable SAL component (CSC) control the MTM2?</Description>
    <item>
        <EFDB_Name>state</EFDB_Name>
        <Description>If true the CSC can control the MTM2; else the Engineering User Interface has control.</Description>
        <IDL_Type>boolean</IDL_Type>
        <Units>unitless</Units>
        <Count>1</Count>
    </item>
</SALEvent>

<SALEvent>
    <Subsystem>MTM2</Subsystem>
    <EFDB_Topic>MTM2_logevent_interlock</EFDB_Topic>
    <Alias>interlock</Alias>
    <Description>MTM2 interlock: This event is generated when safety interlock is engaged or disengaged</Description>
    <item>
        <EFDB_Name>state</EFDB_Name>
        <Description>True if the interlock is engaged. False if it is cleared.</Description>
        <IDL_Type>boolean</IDL_Type>
        <Units>unitless</Units>
        <Count>1</Count>
    </item>
</SALEvent>

<SALEvent>
    <Subsystem>MTM2</Subsystem>
    <EFDB_Topic>MTM2_logevent_tcpIpConnected</EFDB_Topic>
    <Alias>tcpIpConnected</Alias>
    <Description>State of TCP/IP connection between the server and the low level controller.</Description>
    <item>
        <EFDB_Name>isConnected</EFDB_Name>
        <Description>Is the socket connected (true=yes, false=no)?</Description>
        <IDL_Type>boolean</IDL_Type>
        <Units>unitless</Units>
        <Count>1</Count>
    </item>
</SALEvent>

<SALEvent>
    <Subsystem>MTM2</Subsystem>
    <EFDB_Topic>MTM2_logevent_hardpointList</EFDB_Topic>
    <Alias>hardpointList</Alias>
    <Description>Hardpoint list in the low-level controller.</Description>
    <item>
        <EFDB_Name>actuators</EFDB_Name>
        <Description>Actuator Ids to be the hardpoint.</Description>
        <IDL_Type>unsigned short</IDL_Type>
        <Units>unitless</Units>
        <Count>6</Count>
    </item>
</SALEvent>

</SALEventSet>
