=== lsst-ts/ts_xml/schema/SALEventSet.xsd
<xsd:schema attributeFormDefault="unqualified" elementFormDefault="unqualified" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <xsd:annotation>
        <xsd:documentation xml:lang="en">SAL Event data item schema for LSST
    </xsd:documentation>
    </xsd:annotation>
    <xsd:element name="SALEventSet" type="eventSetType"/>
    <xsd:element name="SALEvent" type="eventType"/>
    <xsd:element name="SALEventItem" type="eventItemType"/>
    <xsd:element name="SALEventFileRef" type="eventFileRefType"/>
    <xsd:complexType name="eventItemType">
        <xsd:choice maxOccurs="unbounded">
            <xsd:element name="EFDB_Name" type="xsd:string"/>
            <xsd:element name="Description" type="xsd:string"/>
            <xsd:element name="IDL_Type" type="xsd:string"/>
            <xsd:element minOccurs="0" name="IDL_Size" type="xsd:string"/>
            <xsd:element name="Units" type="xsd:string"/>
            <xsd:element name="Count" type="xsd:positiveInteger"/>
            <xsd:element maxOccurs="1" minOccurs="0" name="Explanation" type="xsd:anyURI"/>
            <xsd:element maxOccurs="1" minOccurs="0" name="Enumeration" type="xsd:string"/>
        </xsd:choice>
    </xsd:complexType>
    <xsd:complexType name="eventType">
        <xsd:sequence>
            <xsd:element maxOccurs="1" minOccurs="1" name="Subsystem" type="xsd:string"/>
            <xsd:element maxOccurs="1" minOccurs="0" name="Version" type="version"/>
            <xsd:element maxOccurs="1" minOccurs="0" name="Author" type="xsd:string"/>
            <xsd:element maxOccurs="1" minOccurs="1" name="EFDB_Topic" type="xsd:string"/>
            <xsd:element maxOccurs="1" minOccurs="0" name="Alias" type="xsd:string"/>
            <xsd:element maxOccurs="1" minOccurs="0" name="Enumeration" type="xsd:string"/>
            <xsd:element maxOccurs="1" minOccurs="0" name="Description" type="xsd:string"/>
            <xsd:element maxOccurs="1" minOccurs="0" name="Explanation" type="xsd:anyURI"/>
            <xsd:element maxOccurs="unbounded" minOccurs="0" name="item" type="eventItemType"/>
            <xsd:element maxOccurs="1" minOccurs="0" name="File_Reference" type="eventFileRefType"/>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="eventSetType">
        <xsd:sequence>
            <xsd:element maxOccurs="unbounded" minOccurs="0" name="Enumeration" type="xsd:string"/>
            <xsd:element maxOccurs="unbounded" minOccurs="1" name="SALEvent" type="eventType"/>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="eventFileRefType">
        <xsd:choice maxOccurs="unbounded">
            <xsd:element maxOccurs="1" minOccurs="1" name="EFDB_Name" type="xsd:string"/>
            <xsd:element name="Description" type="xsd:string"/>
            <xsd:element maxOccurs="1" minOccurs="1" name="URL" type="xsd:anyURI"/>
            <xsd:element maxOccurs="1" minOccurs="1" name="Generator" type="xsd:string"/>
            <xsd:element maxOccurs="1" minOccurs="1" name="Version" type="version"/>
            <xsd:element maxOccurs="1" minOccurs="1" name="Checksum" type="xsd:string"/>
            <xsd:element name="Mime_Type" type="xsd:string"/>
            <xsd:element name="Byte_Size" type="xsd:positiveInteger"/>
            <xsd:element maxOccurs="1" minOccurs="1" name="ID" type="xsd:string"/>
            <xsd:element maxOccurs="1" minOccurs="0" name="Explanation" type="xsd:anyURI"/>
        </xsd:choice>
    </xsd:complexType>
    <xsd:simpleType name="version">
        <xsd:restriction base="xsd:token">
            <xsd:pattern value="\d+\.\d+(\.\d+)?"/>
        </xsd:restriction>
    </xsd:simpleType>
    <xsd:attribute name="updateDate" type="xsd:date"/>
</xsd:schema>

=== lsst-ts/ts_xml/sal_interfaces/tcs/tcs_Events.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="http://lsst-sal.tuc.noao.edu/schema/SALEventSet.xsl"?>
<SALEventSet xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="http://lsst-sal.tuc.noao.edu/schema/SALEventSet.xsd">

<SALEvent>
 <Subsystem>tcs</Subsystem>
 <Version>2.5.3</Version>
 <Author>salgenerator</Author>
 <EFDB_Topic>tcs_logevent_wfpDataReady</EFDB_Topic>
 <Alias>wfpDataReady</Alias>
 <Explanation>http://sal.lsst.org/SAL/Events/tcs_logevent_wfpDataReady.html</Explanation>
    <item>
      <EFDB_Name>priority</EFDB_Name>
      <Description>Severity of the event</Description>
      <IDL_Type>long</IDL_Type>
      <Units>NA</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>images_location_URI</EFDB_Name>
      <Description> </Description>
       <IDL_Type>string</IDL_Type>
       <IDL_Size>256</IDL_Size>
      <Units> </Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>images_match_URI</EFDB_Name>
      <Description> </Description>
       <IDL_Type>string</IDL_Type>
       <IDL_Size>64</IDL_Size>
      <Units> </Units>
      <Count>1</Count>
    </item>
</SALEvent>

<SALEvent>
 <Subsystem>tcs</Subsystem>
 <Version>2.5.3</Version>
 <Author>salgenerator</Author>
 <EFDB_Topic>tcs_logevent_zemaxError</EFDB_Topic>
 <Alias>zemaxError</Alias>
 <Explanation>http://sal.lsst.org/SAL/Events/tcs_logevent_zemaxError.html</Explanation>
    <item>
      <EFDB_Name>priority</EFDB_Name>
      <Description>Severity of the event</Description>
      <IDL_Type>long</IDL_Type>
      <Units>NA</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>details</EFDB_Name>
      <Description> </Description>
       <IDL_Type>string</IDL_Type>
       <IDL_Size>128</IDL_Size>
      <Units> </Units>
      <Count>1</Count>
    </item>
</SALEvent>
</SALEventSet>

=== lsst-ts/ts_xml/sal_interfaces/OCPS/OCPS_Events.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="http://project.lsst.org/ts/sal_objects/schema/SALEventSet.xsl"?>
<SALEventSet xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://project.lsst.org/ts/sal_objects/schema/SALEventSet.xsd">
  <SALEvent>
    <Subsystem>OCPS</Subsystem>
    <EFDB_Topic>OCPS_logevent_job_result</EFDB_Topic>
    <item>
      <EFDB_Name>job_id</EFDB_Name>
      <Description>Job identifier for async pipeline execution.</Description>
      <IDL_Type>string</IDL_Type>
      <IDL_Size>1</IDL_Size>
      <Units>unitless</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>exit_code</EFDB_Name>
      <Description>Process exit code.</Description>
      <IDL_Type>int</IDL_Type>
      <Units>unitless</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>result</EFDB_Name>
      <Description>Pipeline result as JSON.</Description>
      <IDL_Type>string</IDL_Type>
      <IDL_Size>1</IDL_Size>
      <Units>unitless</Units>
      <Count>1</Count>
    </item>
  </SALEvent>
  <SALEvent>
    <Subsystem>OCPS</Subsystem>
    <EFDB_Topic>OCPS_logevent_job_id</EFDB_Topic>
    <item>
      <EFDB_Name>event_name</EFDB_Name>
      <Description>Triggering event name ("cmd_execute" if from a command).</Description>
      <IDL_Type>string</IDL_Type>
      <IDL_Size>1</IDL_Size>
      <Units>unitless</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>seqNum</EFDB_Name>
      <Description>Sequence number of the event (for linkage).</Description>
      <IDL_Type>int</IDL_Type>
      <Units>unitless</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>job_id</EFDB_Name>
      <Description>Job identifier for async pipeline execution.</Description>
      <IDL_Type>string</IDL_Type>
      <IDL_Size>1</IDL_Size>
      <Units>unitless</Units>
      <Count>1</Count>
    </item>
  </SALEvent>
</SALEventSet>

=== lsst-ts/ts_xml/sal_interfaces/LOVE/LOVE_Events.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="http://lsst-sal.tuc.noao.edu/schema/SALEventSet.xsl"?>
<SALEventSet xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="http://lsst-sal.tuc.noao.edu/schema/SALEventSet.xsd">

<SALEvent>
    <Subsystem>LOVE</Subsystem>
    <EFDB_Topic>LOVE_logevent_observingLog</EFDB_Topic>
    <Alias>observingLog</Alias>
    <Description>A message for the observing log.</Description>
    <item>
        <EFDB_Name>message</EFDB_Name>
        <Description>The message.</Description>
        <IDL_Type>string</IDL_Type>
        <IDL_Size>1</IDL_Size>
        <Units>unitless</Units>
        <Count>1</Count>
    </item>
    <item>
        <EFDB_Name>user</EFDB_Name>
        <Description>Who is the message from?</Description>
        <IDL_Type>string</IDL_Type>
        <IDL_Size>1</IDL_Size>
        <Units>unitless</Units>
        <Count>1</Count>
    </item>
</SALEvent>

</SALEventSet>

=== lsst-ts/ts_xml/sal_interfaces/camera/camera_Events.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="http://lsst-sal.tuc.noao.edu/schema/SALEventSet.xsl"?>
<SALEventSet xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="http://lsst-sal.tuc.noao.edu/schema/SALEventSet.xsd">

<SALEvent>
 <Subsystem>camera</Subsystem>
 <Version>2.5.2</Version>
 <Author>salgenerator</Author>
 <EFDB_Topic>camera_logevent_ccsConfigured</EFDB_Topic>
 <Alias>ccsConfigured</Alias>
 <Explanation>http://sal.lsst.org/SAL/Events/camera_logevent_ccsConfigured.html</Explanation>
</SALEvent>

<SALEvent>
 <Subsystem>camera</Subsystem>
 <Version>2.5.2</Version>
 <Author>salgenerator</Author>
 <EFDB_Topic>camera_logevent_endInitializeGuider</EFDB_Topic>
 <Alias>endInitializeGuider</Alias>
 <Explanation>http://sal.lsst.org/SAL/Events/camera_logevent_endInitializeGuider.html</Explanation>
</SALEvent>

<SALEvent>
 <Subsystem>camera</Subsystem>
 <Version>2.5.2</Version>
 <Author>salgenerator</Author>
 <EFDB_Topic>camera_logevent_endInitializeImage</EFDB_Topic>
 <Alias>endInitializeImage</Alias>
 <Explanation>http://sal.lsst.org/SAL/Events/camera_logevent_endInitializeImage.html</Explanation>
</SALEvent>

<SALEvent>
 <Subsystem>camera</Subsystem>
 <Version>2.5.2</Version>
 <Author>salgenerator</Author>
 <EFDB_Topic>camera_logevent_endLoadFilter</EFDB_Topic>
 <Alias>endLoadFilter</Alias>
 <Explanation>http://sal.lsst.org/SAL/Events/camera_logevent_endLoadFilter.html</Explanation>
</SALEvent>

<SALEvent>
 <Subsystem>camera</Subsystem>
 <Version>2.5.2</Version>
 <Author>salgenerator</Author>
 <EFDB_Topic>camera_logevent_endReadout</EFDB_Topic>
 <Alias>endReadout</Alias>
 <Explanation>http://sal.lsst.org/SAL/Events/camera_logevent_endReadout.html</Explanation>
</SALEvent>

<SALEvent>
 <Subsystem>camera</Subsystem>
 <Version>2.5.2</Version>
 <Author>salgenerator</Author>
 <EFDB_Topic>camera_logevent_endRotateCarousel</EFDB_Topic>
 <Alias>endRotateCarousel</Alias>
 <Explanation>http://sal.lsst.org/SAL/Events/camera_logevent_endRotateCarousel.html</Explanation>
</SALEvent>

<SALEvent>
 <Subsystem>camera</Subsystem>
 <Version>2.5.2</Version>
 <Author>salgenerator</Author>
 <EFDB_Topic>camera_logevent_endSetFilter</EFDB_Topic>
 <Alias>endSetFilter</Alias>
 <Explanation>http://sal.lsst.org/SAL/Events/camera_logevent_endSetFilter.html</Explanation>
</SALEvent>

<SALEvent>
 <Subsystem>camera</Subsystem>
 <Version>2.5.2</Version>
 <Author>salgenerator</Author>
 <EFDB_Topic>camera_logevent_endShutterClose</EFDB_Topic>
 <Alias>endShutterClose</Alias>
 <Explanation>http://sal.lsst.org/SAL/Events/camera_logevent_endShutterClose.html</Explanation>
</SALEvent>

<SALEvent>
 <Subsystem>camera</Subsystem>
 <Version>2.5.2</Version>
 <Author>salgenerator</Author>
 <EFDB_Topic>camera_logevent_endShutterOpen</EFDB_Topic>
 <Alias>endShutterOpen</Alias>
 <Explanation>http://sal.lsst.org/SAL/Events/camera_logevent_endShutterOpen.html</Explanation>
</SALEvent>

<SALEvent>
 <Subsystem>camera</Subsystem>
 <Version>2.5.2</Version>
 <Author>salgenerator</Author>
 <EFDB_Topic>camera_logevent_endTakeImage</EFDB_Topic>
 <Alias>endTakeImage</Alias>
 <Explanation>http://sal.lsst.org/SAL/Events/camera_logevent_endTakeImage.html</Explanation>
</SALEvent>

<SALEvent>
 <Subsystem>camera</Subsystem>
 <Version>2.5.2</Version>
 <Author>salgenerator</Author>
 <EFDB_Topic>camera_logevent_endUnloadFilter</EFDB_Topic>
 <Alias>endUnloadFilter</Alias>
 <Explanation>http://sal.lsst.org/SAL/Events/camera_logevent_endUnloadFilter.html</Explanation>
</SALEvent>

<SALEvent>
 <Subsystem>camera</Subsystem>
 <Version>2.5.2</Version>
 <Author>salgenerator</Author>
 <EFDB_Topic>camera_logevent_notReadyToTakeImage</EFDB_Topic>
 <Alias>notReadyToTakeImage</Alias>
 <Explanation>http://sal.lsst.org/SAL/Events/camera_logevent_notReadyToTakeImage.html</Explanation>
</SALEvent>

<SALEvent>
 <Subsystem>camera</Subsystem>
 <Version>2.5.2</Version>
 <Author>salgenerator</Author>
 <EFDB_Topic>camera_logevent_prepareToTakeImage</EFDB_Topic>
 <Alias>prepareToTakeImage</Alias>
 <Explanation>http://sal.lsst.org/SAL/Events/camera_logevent_prepareToTakeImage.html</Explanation>
</SALEvent>

<SALEvent>
 <Subsystem>camera</Subsystem>
 <Version>2.5.2</Version>
 <Author>salgenerator</Author>
 <EFDB_Topic>camera_logevent_readyToTakeImage</EFDB_Topic>
 <Alias>readyToTakeImage</Alias>
 <Explanation>http://sal.lsst.org/SAL/Events/camera_logevent_readyToTakeImage.html</Explanation>
</SALEvent>

<SALEvent>
 <Subsystem>camera</Subsystem>
 <Version>2.5.2</Version>
 <Author>salgenerator</Author>
 <EFDB_Topic>camera_logevent_startIntegration</EFDB_Topic>
 <Alias>startIntegration</Alias>
 <Explanation>http://sal.lsst.org/SAL/Events/camera_logevent_startIntegration.html</Explanation>
    <item>
      <EFDB_Name>priority</EFDB_Name>
      <Description>Severity of the event</Description>
      <IDL_Type>long</IDL_Type>
      <Units>NA</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>imageName</EFDB_Name>
      <Description> </Description>
       <IDL_Type>string</IDL_Type>
      <Units> </Units>
      <Count>1</Count>
    </item>
</SALEvent>

<SALEvent>
 <Subsystem>camera</Subsystem>
 <Version>2.5.2</Version>
 <Author>salgenerator</Author>
 <EFDB_Topic>camera_logevent_startLoadFilter</EFDB_Topic>
 <Alias>startLoadFilter</Alias>
 <Explanation>http://sal.lsst.org/SAL/Events/camera_logevent_startLoadFilter.html</Explanation>
</SALEvent>

<SALEvent>
 <Subsystem>camera</Subsystem>
 <Version>2.5.2</Version>
 <Author>salgenerator</Author>
 <EFDB_Topic>camera_logevent_startReadout</EFDB_Topic>
 <Alias>startReadout</Alias>
 <Explanation>http://sal.lsst.org/SAL/Events/camera_logevent_startReadout.html</Explanation>
</SALEvent>

<SALEvent>
 <Subsystem>camera</Subsystem>
 <Version>2.5.2</Version>
 <Author>salgenerator</Author>
 <EFDB_Topic>camera_logevent_startRotateCarousel</EFDB_Topic>
 <Alias>startRotateCarousel</Alias>
 <Explanation>http://sal.lsst.org/SAL/Events/camera_logevent_startRotateCarousel.html</Explanation>
</SALEvent>

<SALEvent>
 <Subsystem>camera</Subsystem>
 <Version>2.5.2</Version>
 <Author>salgenerator</Author>
 <EFDB_Topic>camera_logevent_startSetFilter</EFDB_Topic>
 <Alias>startSetFilter</Alias>
 <Explanation>http://sal.lsst.org/SAL/Events/camera_logevent_startSetFilter.html</Explanation>
</SALEvent>

<SALEvent>
 <Subsystem>camera</Subsystem>
 <Version>2.5.2</Version>
 <Author>salgenerator</Author>
 <EFDB_Topic>camera_logevent_startShutterClose</EFDB_Topic>
 <Alias>startShutterClose</Alias>
 <Explanation>http://sal.lsst.org/SAL/Events/camera_logevent_startShutterClose.html</Explanation>
</SALEvent>

<SALEvent>
 <Subsystem>camera</Subsystem>
 <Version>2.5.2</Version>
 <Author>salgenerator</Author>
 <EFDB_Topic>camera_logevent_startShutterOpen</EFDB_Topic>
 <Alias>startShutterOpen</Alias>
 <Explanation>http://sal.lsst.org/SAL/Events/camera_logevent_startShutterOpen.html</Explanation>
</SALEvent>

<SALEvent>
 <Subsystem>camera</Subsystem>
 <Version>2.5.2</Version>
 <Author>salgenerator</Author>
 <EFDB_Topic>camera_logevent_startUnloadFilter</EFDB_Topic>
 <Alias>startUnloadFilter</Alias>
 <Explanation>http://sal.lsst.org/SAL/Events/camera_logevent_startUnloadFilter.html</Explanation>
</SALEvent>
</SALEventSet>

=== lsst-ts/ts_xml/python/lsst/ts/xml/data/sal_interfaces/Test/Test_Events.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="http://lsst-sal.tuc.noao.edu/schema/SALEventSet.xsl"?>
<SALEventSet xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://lsst-sal.tuc.noao.edu/schema/SALEventSet.xsd">
  <Enumeration>Enum_One, Enum_Two, Enum_Three</Enumeration>
  <Enumeration>ValueEnum_Zero=0, ValueEnum_Two=2, ValueEnum_Four=04, ValueEnum_Five=0x05</Enumeration>
  <SALEvent>
    <Subsystem>Test</Subsystem>
    <EFDB_Topic>Test_logevent_scalars</EFDB_Topic>
    <Description>Scalar values.</Description>
    <item>
      <EFDB_Name>boolean0</EFDB_Name>
      <Description>A boolean.</Description>
      <IDL_Type>boolean</IDL_Type>
      <Units>unitless</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>byte0</EFDB_Name>
      <Description>A byte.</Description>
      <IDL_Type>byte</IDL_Type>
      <Units>unitless</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>short0</EFDB_Name>
      <Description>A short.</Description>
      <IDL_Type>short</IDL_Type>
      <Units>unitless</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>int0</EFDB_Name>
      <Description>An int.</Description>
      <IDL_Type>int</IDL_Type>
      <Units>unitless</Units>
      <Count>1</Count>
      <Enumeration>Int0Enum_One, Int0Enum_Two, Int0Enum_Three</Enumeration>
    </item>
    <item>
      <EFDB_Name>long0</EFDB_Name>
      <Description>A long.</Description>
      <IDL_Type>long</IDL_Type>
      <Units>unitless</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>longLong0</EFDB_Name>
      <Description>A long long.</Description>
      <IDL_Type>long long</IDL_Type>
      <Units>unitless</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>unsignedShort0</EFDB_Name>
      <Description>An unsigned short.</Description>
      <IDL_Type>unsigned short</IDL_Type>
      <Units>unitless</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>unsignedInt0</EFDB_Name>
      <Description>An unsigned int.</Description>
      <IDL_Type>unsigned int</IDL_Type>
      <Units>unitless</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>float0</EFDB_Name>
      <Description>A float.</Description>
      <IDL_Type>float</IDL_Type>
      <Units>unitless</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>double0</EFDB_Name>
      <Description>A double.</Description>
      <IDL_Type>double</IDL_Type>
      <Units>unitless</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>string0</EFDB_Name>
      <Description>A string.</Description>
      <IDL_Type>string</IDL_Type>
      <IDL_Size>20</IDL_Size>
      <Units>unitless</Units>
      <Count>1</Count>
    </item>
  </SALEvent>
  <SALEvent>
    <Subsystem>Test</Subsystem>
    <EFDB_Topic>Test_logevent_arrays</EFDB_Topic>
    <Description>Array values.</Description>
    <item>
      <EFDB_Name>boolean0</EFDB_Name>
      <Description>Array of boolean.</Description>
      <IDL_Type>boolean</IDL_Type>
      <Units>unitless</Units>
      <Count>5</Count>
    </item>
    <item>
      <EFDB_Name>byte0</EFDB_Name>
      <Description>Array of byte.</Description>
      <IDL_Type>byte</IDL_Type>
      <Units>unitless</Units>
      <Count>5</Count>
    </item>
    <item>
      <EFDB_Name>short0</EFDB_Name>
      <Description>Array of short.</Description>
      <IDL_Type>short</IDL_Type>
      <Units>unitless</Units>
      <Count>5</Count>
    </item>
    <item>
      <EFDB_Name>int0</EFDB_Name>
      <Description>Array of int.</Description>
      <IDL_Type>int</IDL_Type>
      <Units>unitless</Units>
      <Count>5</Count>
      <Enumeration>Int0ValueEnum_Zero=0, Int0ValueEnum_Two=2, Int0ValueEnum_Four=04, Int0ValueEnum_Five=0x05</Enumeration>
    </item>
    <item>
      <EFDB_Name>long0</EFDB_Name>
      <Description>Array of long.</Description>
      <IDL_Type>long</IDL_Type>
      <Units>unitless</Units>
      <Count>5</Count>
    </item>
    <item>
      <EFDB_Name>longLong0</EFDB_Name>
      <Description>Array of long long.</Description>
      <IDL_Type>long long</IDL_Type>
      <Units>unitless</Units>
      <Count>5</Count>
    </item>
    <item>
      <EFDB_Name>unsignedShort0</EFDB_Name>
      <Description>Array of unsigned short.</Description>
      <IDL_Type>unsigned short</IDL_Type>
      <Units>unitless</Units>
      <Count>5</Count>
    </item>
    <item>
      <EFDB_Name>unsignedInt0</EFDB_Name>
      <Description>Array of unsigned int.</Description>
      <IDL_Type>unsigned int</IDL_Type>
      <Units>unitless</Units>
      <Count>5</Count>
    </item>
    <item>
      <EFDB_Name>float0</EFDB_Name>
      <Description>Array of float.</Description>
      <IDL_Type>float</IDL_Type>
      <Units>unitless</Units>
      <Count>5</Count>
    </item>
    <item>
      <EFDB_Name>double0</EFDB_Name>
      <Description>Array of double.</Description>
      <IDL_Type>double</IDL_Type>
      <Units>unitless</Units>
      <Count>5</Count>
    </item>
  </SALEvent>
</SALEventSet>

=== lsst-ts/ts_xml/sal_interfaces/MTHeaderService/MTHeaderService_Events.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="http://lsst-sal.tuc.noao.edu/schema/SALEventSet.xsl"?>
<SALEventSet xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://lsst-sal.tuc.noao.edu/schema/SALEventSet.xsd">
  <Enumeration>SummaryState_DisabledState,SummaryState_EnabledState,SummaryState_FaultState,SummaryState_OfflineState,SummaryState_StandbyState</Enumeration>
  <Enumeration>DetailedState_DisabledState,DetailedState_EnabledState,DetailedState_FaultState,DetailedState_OfflineState,DetailedState_StandbyState</Enumeration>
  <SALEvent>
    <Subsystem>MTHeaderService</Subsystem>
    <Version>3.8</Version>
    <Author/>
    <EFDB_Topic>MTHeaderService_logevent_largeFileObjectAvailable</EFDB_Topic>
    <Alias>largeFileObjectAvailable</Alias>
    <Explanation>http://sal.lsst.org</Explanation>
    <item>
      <EFDB_Name>url</EFDB_Name>
      <Description>The URL for the Large File Object (LFO)</Description>
      <IDL_Type>string</IDL_Type>
      <IDL_Size>256</IDL_Size>
      <Units>unitless</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>generator</EFDB_Name>
      <Description>The CSCs that Generated the Large File Object (LFO)</Description>
      <IDL_Type>string</IDL_Type>
      <IDL_Size>256</IDL_Size>
      <Units>unitless</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>version</EFDB_Name>
      <Description>The Version of the Large File Object</Description>
      <IDL_Type>float</IDL_Type>
      <Units>unitless</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>checkSum</EFDB_Name>
      <Description>The Checksum of the Large File Object</Description>
      <IDL_Type>string</IDL_Type>
      <IDL_Size>256</IDL_Size>
      <Units>unitless</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>mimeType</EFDB_Name>
      <Description>The MIME Type of the Large File Object (FITS/yaml/etc)</Description>
      <IDL_Type>string</IDL_Type>
      <IDL_Size>256</IDL_Size>
      <Units>unitless</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>byteSize</EFDB_Name>
      <Description>The size of the Large File Object in Bytes</Description>
      <IDL_Type>long</IDL_Type>
      <Units>byte</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>id</EFDB_Name>
      <Description>The Unique ID for the Large File Object</Description>
      <IDL_Type>string</IDL_Type>
      <IDL_Size>256</IDL_Size>
      <Units>unitless</Units>
      <Count>1</Count>
    </item>
  </SALEvent>
</SALEventSet>

=== lsst-ts/ts_xml/sal_interfaces/SummitFacility/SummitFacility_Events.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="http://lsst-sal.tuc.noao.edu/schema/SALEventSet.xsl"?>
<SALEventSet xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="http://lsst-sal.tuc.noao.edu/schema/SALEventSet.xsd">
<Enumeration>SummaryState_DisabledState,SummaryState_EnabledState,SummaryState_FaultState,SummaryState_OfflineState,SummaryState_StandbyState</Enumeration>
<Enumeration>DetailedState_DisabledState,DetailedState_EnabledState,DetailedState_FaultState,DetailedState_OfflineState,DetailedState_StandbyState</Enumeration>
<SALEvent>
    <Subsystem>SummitFacility</Subsystem>
    <Version>3.7.1</Version>
    <Author></Author>
    <EFDB_Topic>SummitFacility_logevent_heartbeat</EFDB_Topic>
    <Alias>heartbeat</Alias>
    <Explanation>http://sal.lsst.org</Explanation>
    <item>
        <EFDB_Name>heartbeat</EFDB_Name>
        <Description>Component heartbeat</Description>
        <IDL_Type>boolean</IDL_Type>
        <Units>unitless</Units>
        <Count>1</Count>
    </item>
</SALEvent>
</SALEventSet>
