=== lsst-ts/ts_xml/schema/SALEventSet.xsd
<xsd:schema attributeFormDefault="unqualified" elementFormDefault="unqualified" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <xsd:annotation>
        <xsd:documentation xml:lang="en">SAL Event data item schema for LSST
    </xsd:documentation>
    </xsd:annotation>
    <xsd:element name="SALEventSet" type="eventSetType"/>
    <xsd:element name="SALEvent" type="eventType"/>
    <xsd:element name="SALEventItem" type="eventItemType"/>
    <xsd:element name="SALEventFileRef" type="eventFileRefType"/>
    <xsd:complexType name="eventItemType">
        <xsd:choice maxOccurs="unbounded">
            <xsd:element name="EFDB_Name" type="xsd:string"/>
            <xsd:element name="Description" type="xsd:string"/>
            <xsd:element name="IDL_Type" type="xsd:string"/>
            <xsd:element minOccurs="0" name="IDL_Size" type="xsd:string"/>
            <xsd:element name="Units" type="xsd:string"/>
            <xsd:element name="Count" type="xsd:positiveInteger"/>
            <xsd:element maxOccurs="1" minOccurs="0" name="Explanation" type="xsd:anyURI"/>
            <xsd:element maxOccurs="1" minOccurs="0" name="Enumeration" type="xsd:string"/>
        </xsd:choice>
    </xsd:complexType>
    <xsd:complexType name="eventType">
        <xsd:sequence>
            <xsd:element maxOccurs="1" minOccurs="1" name="Subsystem" type="xsd:string"/>
            <xsd:element maxOccurs="1" minOccurs="0" name="Version" type="version"/>
            <xsd:element maxOccurs="1" minOccurs="0" name="Author" type="xsd:string"/>
            <xsd:element maxOccurs="1" minOccurs="1" name="EFDB_Topic" type="xsd:string"/>
            <xsd:element maxOccurs="1" minOccurs="0" name="Alias" type="xsd:string"/>
            <xsd:element maxOccurs="1" minOccurs="0" name="Enumeration" type="xsd:string"/>
            <xsd:element maxOccurs="1" minOccurs="0" name="Description" type="xsd:string"/>
            <xsd:element maxOccurs="1" minOccurs="0" name="Explanation" type="xsd:anyURI"/>
            <xsd:element maxOccurs="unbounded" minOccurs="0" name="item" type="eventItemType"/>
            <xsd:element maxOccurs="1" minOccurs="0" name="File_Reference" type="eventFileRefType"/>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="eventSetType">
        <xsd:sequence>
            <xsd:element maxOccurs="unbounded" minOccurs="0" name="Enumeration" type="xsd:string"/>
            <xsd:element maxOccurs="unbounded" minOccurs="1" name="SALEvent" type="eventType"/>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="eventFileRefType">
        <xsd:choice maxOccurs="unbounded">
            <xsd:element maxOccurs="1" minOccurs="1" name="EFDB_Name" type="xsd:string"/>
            <xsd:element name="Description" type="xsd:string"/>
            <xsd:element maxOccurs="1" minOccurs="1" name="URL" type="xsd:anyURI"/>
            <xsd:element maxOccurs="1" minOccurs="1" name="Generator" type="xsd:string"/>
            <xsd:element maxOccurs="1" minOccurs="1" name="Version" type="version"/>
            <xsd:element maxOccurs="1" minOccurs="1" name="Checksum" type="xsd:string"/>
            <xsd:element name="Mime_Type" type="xsd:string"/>
            <xsd:element name="Byte_Size" type="xsd:positiveInteger"/>
            <xsd:element maxOccurs="1" minOccurs="1" name="ID" type="xsd:string"/>
            <xsd:element maxOccurs="1" minOccurs="0" name="Explanation" type="xsd:anyURI"/>
        </xsd:choice>
    </xsd:complexType>
    <xsd:simpleType name="version">
        <xsd:restriction base="xsd:token">
            <xsd:pattern value="\d+\.\d+(\.\d+)?"/>
        </xsd:restriction>
    </xsd:simpleType>
    <xsd:attribute name="updateDate" type="xsd:date"/>
</xsd:schema>

=== lsst-ts/ts_xml/python/lsst/ts/xml/data/sal_interfaces/LaserTracker/LaserTracker_Events.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="http://lsst-sal.tuc.noao.edu/schema/SALEventSet.xsl"?>
<SALEventSet xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://lsst-sal.tuc.noao.edu/schema/SALEventSet.xsd">
  <Enumeration>T2SAStatus_READY,T2SAStatus_2FACE,T2SAStatus_DRIFT,T2SAStatus_BUSY</Enumeration>
  <Enumeration>LaserStatus_NOTCONNECTED,LaserStatus_OFF,LaserStatus_WARMING,LaserStatus_ON</Enumeration>
  <Enumeration>AlignComponent_M2,AlignComponent_Camera</Enumeration>
  <SALEvent>
    <Subsystem>LaserTracker</Subsystem>
    <EFDB_Topic>LaserTracker_logevent_offsetsPublish</EFDB_Topic>
    <item>
      <EFDB_Name>target</EFDB_Name>
      <Description>name of the object these offsets belong to (M2, Camera, etc)</Description>
      <IDL_Type>string</IDL_Type>
      <Units>unitless</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>dX</EFDB_Name>
      <Description>Measured object offset in the x-axis relative to nominal.</Description>
      <IDL_Type>float</IDL_Type>
      <Units>mm</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>dY</EFDB_Name>
      <Description>Measured object offset in the y-axis relative to nominal.</Description>
      <IDL_Type>float</IDL_Type>
      <Units>mm</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>dZ</EFDB_Name>
      <Description>Measured object offset in the z-axis relative to nominal.</Description>
      <IDL_Type>float</IDL_Type>
      <Units>mm</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>dRX</EFDB_Name>
      <Description>Measured object rotation with respect to the x-axis relative to nominal</Description>
      <IDL_Type>float</IDL_Type>
      <Units>degree</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>dRY</EFDB_Name>
      <Description>Measured object rotation with respect to the y-axis relative to nominal</Description>
      <IDL_Type>float</IDL_Type>
      <Units>degree</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>dRZ</EFDB_Name>
      <Description>Measured object rotation with respect to the z-axis relative to nominal</Description>
      <IDL_Type>float</IDL_Type>
      <Units>degree</Units>
      <Count>1</Count>
    </item>
  </SALEvent>
  <SALEvent>
    <Subsystem>LaserTracker</Subsystem>
    <EFDB_Topic>LaserTracker_logevent_positionPublish</EFDB_Topic>
    <item>
      <EFDB_Name>target</EFDB_Name>
      <Description>name of the object these positions belong to (M2, Camera, etc)</Description>
      <IDL_Type>string</IDL_Type>
      <Units>unitless</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>dX</EFDB_Name>
      <Description>x positions of the measured object</Description>
      <IDL_Type>float</IDL_Type>
      <Units>mm</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>dY</EFDB_Name>
      <Description>y positions of the measured object</Description>
      <IDL_Type>float</IDL_Type>
      <Units>mm</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>dZ</EFDB_Name>
      <Description>z positions of the measured object</Description>
      <IDL_Type>float</IDL_Type>
      <Units>mm</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>dRX</EFDB_Name>
      <Description>x rotation positions of the measured object</Description>
      <IDL_Type>float</IDL_Type>
      <Units>degree</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>dRY</EFDB_Name>
      <Description>y rotation positions of the measured object</Description>
      <IDL_Type>float</IDL_Type>
      <Units>degree</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>dRZ</EFDB_Name>
      <Description>z rotation positions of the measured object</Description>
      <IDL_Type>float</IDL_Type>
      <Units>degree</Units>
      <Count>1</Count>
    </item>
  </SALEvent>
  <SALEvent>
    <Subsystem>LaserTracker</Subsystem>
    <EFDB_Topic>LaserTracker_logevent_t2saError</EFDB_Topic>
    <item>
      <EFDB_Name>t2saError</EFDB_Name>
      <Description>Error code received from T2SA</Description>
      <IDL_Type>int</IDL_Type>
      <Units>unitless</Units>
      <Count>1</Count>
    </item>
  </SALEvent>
  <SALEvent>
    <Subsystem>LaserTracker</Subsystem>
    <EFDB_Topic>LaserTracker_logevent_t2saStatus</EFDB_Topic>
    <Description>Status of the T2SA system.</Description>
    <item>
      <EFDB_Name>status</EFDB_Name>
      <Description>T2SAStatus enumeration.</Description>
      <IDL_Type>int</IDL_Type>
      <Units>unitless</Units>
      <Count>1</Count>
    </item>
  </SALEvent>
  <SALEvent>
    <Subsystem>LaserTracker</Subsystem>
    <EFDB_Topic>LaserTracker_logevent_laserStatus</EFDB_Topic>
    <Description>Status of the laser.</Description>
    <item>
      <EFDB_Name>status</EFDB_Name>
      <Description>LaserStatus enumeration.</Description>
      <IDL_Type>int</IDL_Type>
      <Units>unitless</Units>
      <Count>1</Count>
    </item>
  </SALEvent>
</SALEventSet>

=== lsst-ts/ts_xml/sal_interfaces/GenericCamera/GenericCamera_Events.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="http://lsst-sal.tuc.noao.edu/schema/SALEventSet.xsl"?>
<SALEventSet xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://lsst-sal.tuc.noao.edu/schema/SALEventSet.xsd">
    <SALEvent>
        <Subsystem>GenericCamera</Subsystem>
        <Version>3.8.41</Version>
        <Author></Author>
        <EFDB_Topic>GenericCamera_logevent_heartbeat</EFDB_Topic>
        <Alias>heartbeat</Alias>
        <Explanation>http://sal.lsst.org</Explanation>
        <item>
            <EFDB_Name>heartbeat</EFDB_Name>
            <Description></Description>
            <IDL_Type>boolean</IDL_Type>
            <Units></Units>
            <Count>1</Count>
        </item>
    </SALEvent>
    <SALEvent>
        <Subsystem>GenericCamera</Subsystem>
        <Version>3.8.41</Version>
        <Author></Author>
        <EFDB_Topic>GenericCamera_logevent_exposureTime</EFDB_Topic>
        <Alias>exposureTime</Alias>
        <Explanation>http://sal.lsst.org</Explanation>
        <item>
            <EFDB_Name>exposureTimeInSec</EFDB_Name>
            <Description>This is the current configured exposure time in seconds.</Description>
            <IDL_Type>double</IDL_Type>
            <Units>seconds</Units>
            <Count>1</Count>
        </item>
    </SALEvent>
    <SALEvent>
        <Subsystem>GenericCamera</Subsystem>
        <Version>3.8.41</Version>
        <Author></Author>
        <EFDB_Topic>GenericCamera_logevent_roi</EFDB_Topic>
        <Alias>roi</Alias>
        <Explanation>http://sal.lsst.org</Explanation>
        <item>
            <EFDB_Name>topPixel</EFDB_Name>
            <Description>This is the regions top most pixel number (base 0).</Description>
            <IDL_Type>int</IDL_Type>
            <Units>pixels</Units>
            <Count>1</Count>
        </item>
        <item>
            <EFDB_Name>leftPixel</EFDB_Name>
            <Description>This is the regions left most pixel number (base 0).</Description>
            <IDL_Type>int</IDL_Type>
            <Units>pixels</Units>
            <Count>1</Count>
        </item>
        <item>
            <EFDB_Name>width</EFDB_Name>
            <Description>This is the regions width in pixels.</Description>
            <IDL_Type>int</IDL_Type>
            <Units>pixels</Units>
            <Count>1</Count>
        </item>
        <item>
            <EFDB_Name>height</EFDB_Name>
            <Description>This is the regions height in pixels.</Description>
            <IDL_Type>int</IDL_Type>
            <Units>pixels</Units>
            <Count>1</Count>
        </item>
    </SALEvent>
    <SALEvent>
        <Subsystem>GenericCamera</Subsystem>
        <Version>3.8.41</Version>
        <Author></Author>
        <EFDB_Topic>GenericCamera_logevent_liveView</EFDB_Topic>
        <Alias>liveView</Alias>
        <Explanation>http://sal.lsst.org</Explanation>
        <item>
            <EFDB_Name>ip</EFDB_Name>
            <Description>This is the ip address for the live view data.</Description>
            <IDL_Type>string</IDL_Type>
            <IDL_Size>1</IDL_Size>
            <Units></Units>
            <Count>1</Count>
        </item>
        <item>
            <EFDB_Name>port</EFDB_Name>
            <Description>This is the TCP port for the live view data.</Description>
            <IDL_Type>int</IDL_Type>
            <Units></Units>
            <Count>1</Count>
        </item>
    </SALEvent>
    <SALEvent>
        <Subsystem>GenericCamera</Subsystem>
        <Version>3.8.41</Version>
        <Author></Author>
        <EFDB_Topic>GenericCamera_logevent_cameraInfo</EFDB_Topic>
        <Alias>cameraInfo</Alias>
        <Explanation>http://sal.lsst.org</Explanation>
        <item>
            <EFDB_Name>cameraMakeAndModel</EFDB_Name>
            <Description>This is the make and model of the current camera.</Description>
            <IDL_Type>string</IDL_Type>
            <IDL_Size>1</IDL_Size>
            <Units></Units>
            <Count>1</Count>
        </item>
    </SALEvent>
    <SALEvent>
        <Subsystem>GenericCamera</Subsystem>
        <Version>3.8.41</Version>
        <Author></Author>
        <EFDB_Topic>GenericCamera_logevent_cameraSpecificProperty</EFDB_Topic>
        <Alias>cameraSpecificProperty</Alias>
        <Explanation>http://sal.lsst.org</Explanation>
        <item>
            <EFDB_Name>propertyName</EFDB_Name>
            <Description>This is the name of the property specific to this camera.</Description>
            <IDL_Type>string</IDL_Type>
            <IDL_Size>1</IDL_Size>
            <Units></Units>
            <Count>1</Count>
        </item>
        <item>
            <EFDB_Name>propertyValue</EFDB_Name>
            <Description>This is the value of the property specific to this camera.</Description>
            <IDL_Type>string</IDL_Type>
            <IDL_Size>1</IDL_Size>
            <Units></Units>
            <Count>1</Count>
        </item>
    </SALEvent>
</SALEventSet>

=== lsst-ts/ts_xml/sal_interfaces/EAS/EAS_Events.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="http://lsst-sal.tuc.noao.edu/schema/SALEventSet.xsl"?>
<SALEventSet xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="http://lsst-sal.tuc.noao.edu/schema/SALEventSet.xsd">
<Enumeration>DetailedState_DisabledState,DetailedState_EnabledState,DetailedState_FaultState,DetailedState_OfflineState,DetailedState_StandbyState</Enumeration>

<SALEvent>
    <Subsystem>EAS</Subsystem>
    <Version>3.8.31</Version>
    <Author></Author>
    <EFDB_Topic>EAS_logevent_detailedState</EFDB_Topic>
    <Alias>detailedState</Alias>
    <Explanation>http://sal.lsst.org</Explanation>
            <item>
                <EFDB_Name>detailedState</EFDB_Name>
                <Description>Detailed state</Description>
                <!-- Enumeration: DetailedState -->
                <IDL_Type>long</IDL_Type>
                <Units>unitless</Units>
                <Count>1</Count>
            </item>
</SALEvent>
<SALEvent>
    <Subsystem>EAS</Subsystem>
    <Version>3.8.31</Version>
    <Author></Author>
    <EFDB_Topic>EAS_logevent_internalCommand</EFDB_Topic>
    <Alias>internalCommand</Alias>
    <Explanation>http://sal.lsst.org</Explanation>
    <item>
        <EFDB_Name>commandObject</EFDB_Name>
        <Description>The error code being published.</Description>
        <IDL_Type>byte</IDL_Type>
        <Units>unitless</Units>
        <Count>800</Count>
    </item>
</SALEvent>
<SALEvent>
    <Subsystem>EAS</Subsystem>
    <Version>3.8.31</Version>
    <Author></Author>
    <EFDB_Topic>EAS_logevent_heartbeat</EFDB_Topic>
    <Alias>heartbeat</Alias>
    <Explanation>http://sal.lsst.org</Explanation>
    <item>
        <EFDB_Name>heartbeat</EFDB_Name>
        <Description>Heartbeat</Description>
        <IDL_Type>boolean</IDL_Type>
        <Units>unitless</Units>
        <Count>1</Count>
    </item>
</SALEvent>
<SALEvent>
    <Subsystem>EAS</Subsystem>
    <Version>3.8.31</Version>
    <Author></Author>
    <EFDB_Topic>EAS_logevent_loopTimeOutOfRange</EFDB_Topic>
    <Alias>loopTimeOutOfRange</Alias>
    <Explanation>http://sal.lsst.org</Explanation>
    <item>
        <EFDB_Name>loopTimeOutOfRange</EFDB_Name>
        <Description>Loop timeout out of range.</Description>
        <IDL_Type>boolean</IDL_Type>
        <Units>unitless</Units>
        <Count>1</Count>
    </item>
</SALEvent>
<SALEvent>
    <Subsystem>EAS</Subsystem>
    <Version>3.8.31</Version>
    <Author></Author>
    <EFDB_Topic>EAS_logevent_rejectedCommand</EFDB_Topic>
    <Alias>rejectedCommand</Alias>
    <Explanation>http://sal.lsst.org</Explanation>
    <item>
        <EFDB_Name>command</EFDB_Name>
        <Description>Name of the rejected command.</Description>
        <IDL_Type>string</IDL_Type>
        <IDL_Size>1</IDL_Size>
        <Units>unitless</Units>
        <Count>1</Count>
    </item>
    <item>
        <EFDB_Name>state</EFDB_Name>
        <Description>Current CSC state.</Description>
        <IDL_Type>string</IDL_Type>
        <IDL_Size>1</IDL_Size>
        <Units>unitless</Units>
        <Count>1</Count>
    </item>
    <item>
        <EFDB_Name>timestamp</EFDB_Name>
        <Description>Timestamp when the command was rejected.</Description>
        <IDL_Type>double</IDL_Type>
        <Units>unitless</Units>
        <Count>1</Count>
    </item>
</SALEvent></SALEventSet>

=== lsst-ts/ts_xml/sal_interfaces/MTDomeTrajectory/MTDomeTrajectory_Events.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="http://lsst-sal.tuc.noao.edu/schema/SALEventSet.xsl"?>
<SALEventSet xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="http://lsst-sal.tuc.noao.edu/schema/SALEventSet.xsd">
<Enumeration>DetailedState_DisabledState,DetailedState_EnabledState,DetailedState_FaultState,DetailedState_OfflineState,DetailedState_StandbyState</Enumeration>

<SALEvent>
    <Subsystem>MTDomeTrajectory</Subsystem>
    <Version>3.8.31</Version>
    <Author></Author>
    <EFDB_Topic>MTDomeTrajectory_logevent_detailedState</EFDB_Topic>
    <Alias>detailedState</Alias>
    <Explanation>http://sal.lsst.org</Explanation>
            <item>
                <EFDB_Name>detailedState</EFDB_Name>
                <Description>Detailed state</Description>
                <!-- Enumeration: DetailedState -->
                <IDL_Type>long</IDL_Type>
                <Units>unitless</Units>
                <Count>1</Count>
            </item>
</SALEvent>
<SALEvent>
    <Subsystem>MTDomeTrajectory</Subsystem>
    <Version>3.8.31</Version>
    <Author></Author>
    <EFDB_Topic>MTDomeTrajectory_logevent_internalCommand</EFDB_Topic>
    <Alias>internalCommand</Alias>
    <Explanation>http://sal.lsst.org</Explanation>
    <item>
        <EFDB_Name>commandObject</EFDB_Name>
        <Description>The error code being published.</Description>
        <IDL_Type>byte</IDL_Type>
        <Units>unitless</Units>
        <Count>800</Count>
    </item>
</SALEvent>
<SALEvent>
    <Subsystem>MTDomeTrajectory</Subsystem>
    <Version>3.8.31</Version>
    <Author></Author>
    <EFDB_Topic>MTDomeTrajectory_logevent_loopTimeOutOfRange</EFDB_Topic>
    <Alias>loopTimeOutOfRange</Alias>
    <Explanation>http://sal.lsst.org</Explanation>
    <item>
        <EFDB_Name>loopTimeOutOfRange</EFDB_Name>
        <Description>Internal loop timedout.</Description>
        <IDL_Type>boolean</IDL_Type>
        <Units>unitless</Units>
        <Count>1</Count>
    </item>
</SALEvent>
<SALEvent>
    <Subsystem>MTDomeTrajectory</Subsystem>
    <Version>3.8.31</Version>
    <Author></Author>
    <EFDB_Topic>MTDomeTrajectory_logevent_rejectedCommand</EFDB_Topic>
    <Alias>rejectedCommand</Alias>
    <Explanation>http://sal.lsst.org</Explanation>
    <item>
        <EFDB_Name>command</EFDB_Name>
        <Description>Name of the rejected command</Description>
        <IDL_Type>string</IDL_Type>
        <IDL_Size>1</IDL_Size>
        <Units>unitless</Units>
        <Count>1</Count>
    </item>
    <item>
        <EFDB_Name>state</EFDB_Name>
        <Description>State of the CSC.</Description>
        <IDL_Type>string</IDL_Type>
        <IDL_Size>1</IDL_Size>
        <Units>unitless</Units>
        <Count>1</Count>
    </item>
    <item>
        <EFDB_Name>timestamp</EFDB_Name>
        <Description>Timestamp when the command was rejected.</Description>
        <IDL_Type>double</IDL_Type>
        <Units>unitless</Units>
        <Count>1</Count>
    </item>
</SALEvent>
<SALEvent>
    <Subsystem>MTDomeTrajectory</Subsystem>
    <Version>3.8.31</Version>
    <Author></Author>
    <EFDB_Topic>MTDomeTrajectory_logevent_allClear</EFDB_Topic>
    <Alias>allClear</Alias>
    <Explanation>http://sal.lsst.org</Explanation>
    <item>
        <EFDB_Name>allClear</EFDB_Name>
        <Description>Is the telescope clear of the dome?</Description>
        <IDL_Type>boolean</IDL_Type>
        <IDL_Size>1</IDL_Size>
        <Units>unitless</Units>
        <Count>1</Count>
    </item>
    <item>
        <EFDB_Name>timestamp</EFDB_Name>
        <Description>Timestamp when the condition changed.</Description>
        <IDL_Type>double</IDL_Type>
        <Units>unitless</Units>
        <Count>1</Count>
    </item>
</SALEvent></SALEventSet>

=== lsst-ts/ts_xml/python/lsst/ts/xml/data/sal_interfaces/AlarmRule/AlarmRule_Events.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="http://lsst-sal.tuc.noao.edu/schema/SALEventSet.xsl"?>
<SALEventSet xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://lsst-sal.tuc.noao.edu/schema/SALEventSet.xsd">
  <Enumeration>AlarmRuleState_Unconfigured,AlarmRuleState_Configuring,AlarmRuleState_Configured,AlarmRuleState_Running,AlarmRuleState_Ending,AlarmRuleState_Stopping,AlarmRuleState_Failing,AlarmRuleState_Stopped,AlarmRuleState_Failed,AlarmRuleState_ConfigureFailed</Enumeration>
  <SALEvent>
    <Subsystem>AlarmRule</Subsystem>
    <EFDB_Topic>AlarmRule_logevent_description</EFDB_Topic>
    <Description>Class name, description, and a list of the remotes it uses -- basically metadata that does not usually depend on configuration.</Description>
    <item>
      <EFDB_Name>classname</EFDB_Name>
      <Description>Name of alarm rule class.</Description>
      <IDL_Type>string</IDL_Type>
      <IDL_Size>1</IDL_Size>
      <Units>unitless</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>description</EFDB_Name>
      <Description>Brief description of the alarm rule.</Description>
      <IDL_Type>string</IDL_Type>
      <IDL_Size>1</IDL_Size>
      <Units>unitless</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>remotes</EFDB_Name>
      <Description>Names of remote SAL components used by the alarm rule as a comma-separated list. Each name is appended with :&lt;index&gt; if the component is indexed (and possibly with :0 if not indexed).</Description>
      <IDL_Type>string</IDL_Type>
      <IDL_Size>1</IDL_Size>
      <Units>unitless</Units>
      <Count>1</Count>
    </item>
  </SALEvent>
  <SALEvent>
    <Subsystem>AlarmRule</Subsystem>
    <EFDB_Topic>AlarmRule_logevent_state</EFDB_Topic>
    <Description>AlarmRule state.</Description>
    <item>
      <EFDB_Name>classname</EFDB_Name>
      <Description>Name of alarm rule class.</Description>
      <IDL_Type>string</IDL_Type>
      <IDL_Size>1</IDL_Size>
      <Units>unitless</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>state</EFDB_Name>
      <Description>An AlarmRuleState enum indicating the alarm rule state.</Description>
      <IDL_Type>byte</IDL_Type>
      <Units>unitless</Units>
      <Count>1</Count>
      <Enumeration>Unconfigured,Configured,Running,Paused,Ending,Stopping,Failing,Stopped,Failed,ConfigureFailed</Enumeration>
    </item>
    <item>
      <EFDB_Name>reason</EFDB_Name>
      <Description>More information about the state change; typically a reason for failure if the state is FAILED.</Description>
      <IDL_Type>string</IDL_Type>
      <IDL_Size>1</IDL_Size>
      <Units>unitless</Units>
      <Count>1</Count>
    </item>
  </SALEvent>
  <SALEvent>
    <Subsystem>AlarmRule</Subsystem>
    <EFDB_Topic>AlarmRule_logevent_alarm</EFDB_Topic>
    <Description>AlarmRule alarm.</Description>
    <item>
      <EFDB_Name>classname</EFDB_Name>
      <Description>Name of alarm rule class.</Description>
      <IDL_Type>string</IDL_Type>
      <IDL_Size>1</IDL_Size>
      <Units>unitless</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>severity</EFDB_Name>
      <Description>An AlarmSeverity enum indicating the alarm rule severity.</Description>
      <IDL_Type>byte</IDL_Type>
      <Units>unitless</Units>
      <Count>1</Count>
      <Enumeration>NONE,WARNING,SERIOUS,CRITICAL</Enumeration>
    </item>
    <item>
      <EFDB_Name>reason</EFDB_Name>
      <Description>The reason for the alarm.</Description>
      <IDL_Type>string</IDL_Type>
      <IDL_Size>1</IDL_Size>
      <Units>unitless</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>muted</EFDB_Name>
      <Description>Was the alarm muted or not?</Description>
      <IDL_Type>boolean</IDL_Type>
      <IDL_Size>1</IDL_Size>
      <Units>unitless</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>acknowledged</EFDB_Name>
      <Description>Was the alarm acknowledged or not?</Description>
      <IDL_Type>boolean</IDL_Type>
      <IDL_Size>1</IDL_Size>
      <Units>unitless</Units>
      <Count>1</Count>
    </item>
  </SALEvent>
</SALEventSet>

=== lsst-ts/ts_xml/sal_interfaces/Guider/Guider_Events.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="http://lsst-sal.tuc.noao.edu/schema/SALEventSet.xsl"?>
<SALEventSet xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://lsst-sal.tuc.noao.edu/schema/SALEventSet.xsd">
  <Enumeration>GuiderStatus_Stopped,GuiderStatus_Starting,GuiderStatus_Guiding,GuiderStatus_Error</Enumeration>
  <SALEvent>
    <Subsystem>Guider</Subsystem>
    <EFDB_Topic>Guider_logevent_guidingStatus</EFDB_Topic>
    <Description>Event published when a guiding operatation starts, stops or resumes. It contains the parameters used to configure the guider (see startGuiding command) and the current status.</Description>
    <item>
      <EFDB_Name>roiX</EFDB_Name>
      <Description>Vector with 8 elements specifying the center of the guider ROI window in the x-axis for each guider sensor. If an element of the array is zero, that guider will be ignored.</Description>
      <IDL_Type>long</IDL_Type>
      <Units>pixel</Units>
      <Count>8</Count>
    </item>
    <item>
      <EFDB_Name>roiY</EFDB_Name>
      <Description>Vector with 8 elements specifying the center of the guider ROI window in the y-axis for each guider sensor. If an element of the array is zero, that guider will be ignored.</Description>
      <IDL_Type>long</IDL_Type>
      <Units>pixel</Units>
      <Count>8</Count>
    </item>
    <item>
      <EFDB_Name>roiWidth</EFDB_Name>
      <Description>Vector with 8 elements specifying the width (window size in the x-axis) of the guider ROI for each guider sensor. For each valid entry in roiX/roiY (roiX,roiY &gt; 0) width must respect the ROI constrains (see requirement CA-TS-GDR-ICD-0006 in LSE-66).</Description>
      <IDL_Type>long</IDL_Type>
      <Units>pixel</Units>
      <Count>8</Count>
    </item>
    <item>
      <EFDB_Name>roiHeight</EFDB_Name>
      <Description>Vector with 8 elements specifying the height (window size in the y-axis) of the guider ROI for each guider sensor. For each valid entry in roiX/roiY (roiX,roiY &gt; 0) height must respect the ROI constrains (see requirement CA-TS-GDR-ICD-0006 in LSE-66).</Description>
      <IDL_Type>long</IDL_Type>
      <Units>pixel</Units>
      <Count>8</Count>
    </item>
    <item>
      <EFDB_Name>expTime</EFDB_Name>
      <Description>Exposure time in milliseconds. All guider sensors will use the same exposure time (CA-TS-GDR-ICD-0034 LSE-66). Limits must respect detector integration time constrains (see requirement CA-TS-GDR-ICD-0034 in LSE-66).</Description>
      <IDL_Type>float</IDL_Type>
      <Units>milliseconds</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>binning</EFDB_Name>
      <Description>Binnig factor. All guider sensors will use the same binning factor. Limits must respect detector bining constrains (see requirement CA-TS-GDR-ICD-0042 in LSE-66).</Description>
      <IDL_Type>float</IDL_Type>
      <Units>milliseconds</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>status</EFDB_Name>
      <Description>Enumeration with the current guiding status. When guider is not running status will be GuiderStatus_Stopped, this could either be when the guider is first enabled or after a stopGuiding command. When guider is initializing a guider sequence but has not achieved stable guiding operation status will be GuiderStatus_Starting. When stable guiding operation is stabilished, status will be GuiderStatus_Guiding. If an error occurred, and the guider is going to FAULT state, status is GuiderStatus_Error. Information about errors will be available in errorCode topic.</Description>
      <!-- Enumeration: GuiderStatus -->
      <IDL_Type>long</IDL_Type>
      <Units>unitless</Units>
      <Count>8</Count>
    </item>
  </SALEvent>
</SALEventSet>
