=== lsst-ts/ts_xml/schema/SALSubsystemSet.xsd
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
        elementFormDefault="unqualified"
        attributeFormDefault="unqualified">

  <xsd:annotation>
    <xsd:documentation xml:lang="en">
     SAL Subsystem data schema for LSST
    </xsd:documentation>
  </xsd:annotation>

 <xsd:element name="SALSubsystemSet"      type="SubsystemSetType"/>
 <xsd:element name="SALSubsystem"         type="SubsystemType"/>
 
 <xsd:complexType name="SubsystemType">
     <xsd:choice maxOccurs="unbounded">
		<xsd:element name="Name"		minOccurs="1" maxOccurs="1" type="xsd:string"/>
		<xsd:element name="Description"		minOccurs="1" maxOccurs="1" type="xsd:string"/>
		<xsd:element name="IndexEnumeration" 	minOccurs="1" maxOccurs="1" type="xsd:string"/>
		<xsd:element name="Generics" 		minOccurs="1" maxOccurs="1" type="xsd:string"/>
		<xsd:element name="ActiveDevelopers" 	minOccurs="1" maxOccurs="1" type="xsd:string"/>
    <xsd:element name="Github"      	minOccurs="0" maxOccurs="1" type="xsd:anyURI"/>
    <xsd:element name="JenkinsTestResults"  minOccurs="0" maxOccurs="1" type="xsd:anyURI"/>
		<xsd:element name="RubinObsContact" 		minOccurs="1" maxOccurs="1" type="xsd:string"/>
		<xsd:element name="CSCDocs" 		minOccurs="0" maxOccurs="unbounded" type="xsd:string"/>
		<xsd:element name="ProductOwner" 	minOccurs="1" maxOccurs="1" type="xsd:string"/>
		<xsd:element name="RelatedDocuments" 	minOccurs="0" maxOccurs="unbounded" type="xsd:string"/>
		<xsd:element name="SoftwareLanguage" 	minOccurs="1" maxOccurs="1" type="xsd:string"/>
		<xsd:element name="RuntimeLanguages" 	minOccurs="1" maxOccurs="1" type="xsd:string"/>
		<xsd:element name="VendorContact" 		minOccurs="0" maxOccurs="unbounded" type="xsd:string"/>
		<xsd:element name="Simulator" 		minOccurs="1" maxOccurs="1" type="xsd:string"/>
		<xsd:element name="Configuration"	minOccurs="1" maxOccurs="1" type="xsd:string"/>
    </xsd:choice>
 </xsd:complexType>

 <xsd:complexType name="SubsystemSetType">
  <xsd:sequence>
   <xsd:element name="SALSubsystem" minOccurs="1"    maxOccurs="unbounded" type="SubsystemType"/>
  </xsd:sequence>
 </xsd:complexType>

<xsd:simpleType name="yes-no">
  <xsd:annotation>
    <xsd:documentation>The yes-no type is used for boolean-like attributes. We cannot use W3C XML Schema booleans due to their restrictions on expression of boolean values.</xsd:documentation>
  </xsd:annotation>
  <xsd:restriction base="xsd:token">
    <xsd:enumeration value="Yes"/>
    <xsd:enumeration value="No"/>
  </xsd:restriction>
</xsd:simpleType>

 <xsd:attribute name="updateDate"    type="xsd:date"/>

</xsd:schema>

=== lsst-ts/ts_xml/python/lsst/ts/xml/data/sal_interfaces/SALSubsystems.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="http://lsst-sal.tuc.noao.edu/schema/SALSubsystemSet.xsl"?>
<SALSubsystemSet xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://lsst-sal.tuc.noao.edu/schema/SALSubsystemSet.xsd">
  <SALSubsystem>
    <Name>ATSpectrograph</Name>
    <Description>CSC for the Auxiliary Telescope Spectrograph.</Description>
    <IndexEnumeration>no</IndexEnumeration>
    <AddedGenerics>csc, configurable</AddedGenerics>
    <ActiveDevelopers>Tiago Ribeiro</ActiveDevelopers>
    <Github>https://github.com/lsst-ts/ts_atspec</Github>
    <JenkinsTestResults>https://tssw-ci.lsst.org/job/LSST_Telescope-and-Site/job/ts_atspec/</JenkinsTestResults>
    <RubinObsContact>Erik Dennihy</RubinObsContact>
    <CSCDocs/>
    <ProductOwner>Erik Dennihy</ProductOwner>
    <RelatedDocuments>https://ls.st/Document-30997, https://ls.st/LTS-487, https://ls.st/LTS-488</RelatedDocuments>
    <SoftwareLanguage>Python</SoftwareLanguage>
    <RuntimeLanguages>Python</RuntimeLanguages>
    <VendorContact>Astronomical Consulting and Equipment</VendorContact>
    <Simulator>Internal to CSC</Simulator>
    <Configuration>https://github.com/lsst-ts/ts_config_latiss</Configuration>
  </SALSubsystem>
  <SALSubsystem>
    <Name>LEDProjector</Name>
    <Description>CSC for LED Projector</Description>
    <IndexEnumeration>no</IndexEnumeration>
    <AddedGenerics>csc, configurable</AddedGenerics>
    <ActiveDevelopers>Joseph Parsons</ActiveDevelopers>
    <Github>https://github.com/lsst-ts/ts_ledprojector</Github>
    <JenkinsTestResults>https://tssw-ci.lsst.org/job/LSST_Telescope-and-Site/job/ts_ledprojector/</JenkinsTestResults>
    <RubinObsContact>Parker Fagrelius</RubinObsContact>
    <CSCDocs/>
    <ProductOwner>Parker Fagrelius</ProductOwner>
    <RelatedDocuments/>
    <SoftwareLanguage>Python</SoftwareLanguage>
    <RuntimeLanguages>Python</RuntimeLanguages>
    <VendorContact>Astronomical Consulting and Equipment</VendorContact>
    <Simulator>Internal to CSC</Simulator>
    <Configuration>https://github.com/lsst-ts/ts_config_mtcalsys</Configuration>
  </SALSubsystem>
  <SALSubsystem>
    <Name>MTReflector</Name>
    <Description>CSC for MTReflector</Description>
    <IndexEnumeration>no</IndexEnumeration>
    <AddedGenerics>csc, configurable</AddedGenerics>
    <ActiveDevelopers>Joseph Parsons</ActiveDevelopers>
    <Github>https://github.com/lsst-ts/ts_mtreflector</Github>
    <JenkinsTestResults>https://tssw-ci.lsst.org/job/LSST_Telescope-and-Site/job/ts_mtreflector/</JenkinsTestResults>
    <RubinObsContact>Parker Fagrelius</RubinObsContact>
    <CSCDocs/>
    <ProductOwner>Parker Fagrelius</ProductOwner>
    <RelatedDocuments/>
    <SoftwareLanguage>Python</SoftwareLanguage>
    <RuntimeLanguages>Python</RuntimeLanguages>
    <VendorContact>Astronomical Consulting and Equipment</VendorContact>
    <Simulator>Internal to CSC</Simulator>
    <Configuration>https://github.com/lsst-ts/ts_config_mtcalsys</Configuration>
  </SALSubsystem>
  <SALSubsystem>
    <Name>LinearStage</Name>
    <Description>CSC for the Linear Stage</Description>
    <IndexEnumeration>first,second</IndexEnumeration>
    <AddedGenerics>csc, configurable</AddedGenerics>
    <ActiveDevelopers>Eric Coughlin</ActiveDevelopers>
    <Github>https://github.com/lsst-ts/ts_LinearStage</Github>
    <JenkinsTestResults>Not Available</JenkinsTestResults>
    <RubinObsContact>Parker Fagrelius</RubinObsContact>
    <CSCDocs/>
    <ProductOwner>Parker Fagrelius</ProductOwner>
    <RelatedDocuments>https://www.zaber.com/manuals/A-LST</RelatedDocuments>
    <SoftwareLanguage>Python</SoftwareLanguage>
    <RuntimeLanguages>Python</RuntimeLanguages>
    <VendorContact>Zaber</VendorContact>
    <Simulator>Not Provided</Simulator>
    <Configuration>https://github.com/lsst-ts/ts_config_mtcalsys</Configuration>
  </SALSubsystem>
  <SALSubsystem>
    <Name>MTMount</Name>
    <Description>CSC for the Main Telescope Mount</Description>
    <IndexEnumeration>no</IndexEnumeration>
    <AddedGenerics>csc, configurable, logevent_clockOffset</AddedGenerics>
    <ActiveDevelopers>Dave Mills, Te-Wei Tsai</ActiveDevelopers>
    <Github>https://github.com/lsst-ts/ts_MTMount</Github>
    <JenkinsTestResults>Not Available</JenkinsTestResults>
    <RubinObsContact>Jeff Barr</RubinObsContact>
    <CSCDocs>https://ts-mtmount.lsst.io</CSCDocs>
    <ProductOwner>Sandrine Thomas</ProductOwner>
    <RelatedDocuments>https://ls.st/LTS-103, https://ls.st/LTS-150, https://ls.st/LTS-159</RelatedDocuments>
    <SoftwareLanguage>Labview</SoftwareLanguage>
    <RuntimeLanguages>Python,CPP,LabVIEW,Java</RuntimeLanguages>
    <VendorContact>Tekniker</VendorContact>
    <Simulator>https://github.com/lsst-ts/ts_tma</Simulator>
    <Configuration>https://github.com/lsst-ts/ts_config_mttcs</Configuration>
  </SALSubsystem>
  <SALSubsystem>
    <Name>MTOODS</Name>
    <Description>LSSTCam Observatory Operations Data Service</Description>
    <IndexEnumeration>no</IndexEnumeration>
    <AddedGenerics>csc</AddedGenerics>
    <ActiveDevelopers>Stephen R. Pietrowicz</ActiveDevelopers>
    <Github>https://github.com/lsst-dm/ctrl_oods</Github>
    <JenkinsTestResults>Not Available</JenkinsTestResults>
    <RubinObsContact>Michael Reuter</RubinObsContact>
    <CSCDocs/>
    <ProductOwner>Michael Reuter</ProductOwner>
    <RelatedDocuments/>
    <SoftwareLanguage>Python</SoftwareLanguage>
    <RuntimeLanguages>Python</RuntimeLanguages>
    <VendorContact>Not Applicable</VendorContact>
    <Simulator>Not Required</Simulator>
    <Configuration>Not Configurable</Configuration>
  </SALSubsystem>
  <SALSubsystem>
    <Name>CCOODS</Name>
    <Description>ComCam Observatory Operations Data Service</Description>
    <IndexEnumeration>no</IndexEnumeration>
    <AddedGenerics>csc</AddedGenerics>
    <ActiveDevelopers>Stephen R. Pietrowicz</ActiveDevelopers>
    <Github>https://github.com/lsst-dm/ctrl_oods</Github>
    <JenkinsTestResults>Not Available</JenkinsTestResults>
    <RubinObsContact>Michael Reuter</RubinObsContact>
    <CSCDocs/>
    <ProductOwner>Michael Reuter</ProductOwner>
    <RelatedDocuments/>
    <SoftwareLanguage>Python</SoftwareLanguage>
    <RuntimeLanguages>Python</RuntimeLanguages>
    <VendorContact>Not Applicable</VendorContact>
    <Simulator>Not Required</Simulator>
    <Configuration>Not Configurable</Configuration>
  </SALSubsystem>
  <SALSubsystem>
    <Name>ATOODS</Name>
    <Description>LATISS Observatory Operations Data Service</Description>
    <IndexEnumeration>no</IndexEnumeration>
    <AddedGenerics>csc</AddedGenerics>
    <ActiveDevelopers>Stephen R. Pietrowicz</ActiveDevelopers>
    <Github>https://github.com/lsst-dm/ctrl_oods</Github>
    <JenkinsTestResults>Not Available</JenkinsTestResults>
    <RubinObsContact>Michael Reuter</RubinObsContact>
    <CSCDocs/>
    <ProductOwner>Michael Reuter</ProductOwner>
    <RelatedDocuments/>
    <SoftwareLanguage>Python</SoftwareLanguage>
    <RuntimeLanguages>Python</RuntimeLanguages>
    <VendorContact>Not Applicable</VendorContact>
    <Simulator>Not Required</Simulator>
    <Configuration>Not Configurable</Configuration>
  </SALSubsystem>
  <SALSubsystem>
    <Name>WFOODS</Name>
    <Description>LSSTCam Wavefront Observatory Operations Data Service</Description>
    <IndexEnumeration>no</IndexEnumeration>
    <AddedGenerics>csc</AddedGenerics>
    <ActiveDevelopers>Stephen R. Pietrowicz</ActiveDevelopers>
    <Github>https://github.com/lsst-dm/ctrl_oods</Github>
    <JenkinsTestResults>Not Available</JenkinsTestResults>
    <RubinObsContact>Michael Reuter</RubinObsContact>
    <CSCDocs/>
    <ProductOwner>Michael Reuter</ProductOwner>
    <RelatedDocuments/>
    <SoftwareLanguage>Python</SoftwareLanguage>
    <RuntimeLanguages>Python</RuntimeLanguages>
    <VendorContact>Not Applicable</VendorContact>
    <Simulator>Not Required</Simulator>
    <Configuration>Not Configurable</Configuration>
  </SALSubsystem>
  <SALSubsystem>
    <Name>ATAOS</Name>
    <Description>CSC for the Auxiliary Telescope Active Optics System</Description>
    <IndexEnumeration>no</IndexEnumeration>
    <AddedGenerics>csc, configurable</AddedGenerics>
    <ActiveDevelopers>Tiago Ribeiro</ActiveDevelopers>
    <Github>https://github.com/lsst-ts/ts_ataos</Github>
    <JenkinsTestResults>https://tssw-ci.lsst.org/job/LSST_Telescope-and-Site/job/ts_ataos/</JenkinsTestResults>
    <RubinObsContact>Erik Dennihy</RubinObsContact>
    <CSCDocs/>
    <ProductOwner>Erik Dennihy</ProductOwner>
    <RelatedDocuments/>
    <SoftwareLanguage>Python</SoftwareLanguage>
    <RuntimeLanguages>Python</RuntimeLanguages>
    <VendorContact>NA</VendorContact>
    <Simulator>Not Required</Simulator>
    <Configuration>https://github.com/lsst-ts/ts_config_attcs</Configuration>
  </SALSubsystem>
  <SALSubsystem>
    <Name>ATBuilding</Name>
    <Description>CSC for the building housing the Auxiliary Telescope on Callibration Hill</Description>
    <IndexEnumeration>no</IndexEnumeration>
    <AddedGenerics>csc, configurable</AddedGenerics>
    <ActiveDevelopers>Eric Coughlin</ActiveDevelopers>
    <Github>none yet</Github>
    <JenkinsTestResults>Not Available</JenkinsTestResults>
    <RubinObsContact>Erik Dennihy</RubinObsContact>
    <CSCDocs/>
    <ProductOwner>Erik Dennihy</ProductOwner>
    <RelatedDocuments/>
    <SoftwareLanguage/>
    <RuntimeLanguages>Python</RuntimeLanguages>
    <VendorContact>Not Applicable</VendorContact>
    <Simulator>Not Provided</Simulator>
    <Configuration>https://github.com/lsst-ts/ts_config_attcs</Configuration>
  </SALSubsystem>
  <SALSubsystem>
    <Name>DIMM</Name>
    <Description>CSC for the DIMM (Differential Image Motion Monitor) telescope</Description>
    <IndexEnumeration>any</IndexEnumeration>
    <AddedGenerics>csc, configurable</AddedGenerics>
    <ActiveDevelopers>Dave Mills, Wouter van Reeven</ActiveDevelopers>
