=== lsst-ts/ts_xml/schema/SALTelemetrySet.xsd
<xsd:schema attributeFormDefault="unqualified" elementFormDefault="unqualified" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <xsd:annotation>
        <xsd:documentation xml:lang="en">SAL telemetry data item schema for LSST
    </xsd:documentation>
    </xsd:annotation>
    <xsd:element name="SALTelemetrySet" type="telemetrySetType"/>
    <xsd:element name="SALTelemetry" type="telemetryType"/>
    <xsd:element name="SALTelemetryItem" type="telemetryItemType"/>
    <xsd:complexType name="telemetryItemType">
        <xsd:annotation>
            <xsd:documentation>Telemetry items parameters and values</xsd:documentation>
        </xsd:annotation>
        <xsd:choice maxOccurs="unbounded">
            <xsd:element name="EFDB_Name" type="xsd:string">
                <xsd:annotation>
                    <xsd:documentation>Engineering and Facility Database name</xsd:documentation>
                </xsd:annotation>
            </xsd:element>
            <xsd:element name="Description" type="xsd:string">
                <xsd:annotation>
                    <xsd:documentation>Description of telemetry item</xsd:documentation>
                </xsd:annotation>
            </xsd:element>
            <xsd:element maxOccurs="1" minOccurs="0" name="Size_in_bytes" type="xsd:positiveInteger">
                <xsd:annotation>
                    <xsd:documentation>Size of telemetry item in bytes</xsd:documentation>
                </xsd:annotation>
            </xsd:element>
            <xsd:element name="IDL_Type" type="xsd:string">
                <xsd:annotation>
                    <xsd:documentation>IDL type of telemetry item</xsd:documentation>
                </xsd:annotation>
            </xsd:element>
            <xsd:element minOccurs="0" name="IDL_Size" type="xsd:string"/>
            <xsd:element name="Units" type="xsd:string">
                <xsd:annotation>
                    <xsd:documentation>Units (if known)</xsd:documentation>
                </xsd:annotation>
            </xsd:element>
            <xsd:element name="Count" type="xsd:positiveInteger">
                <xsd:annotation>
                    <xsd:documentation>Count</xsd:documentation>
                </xsd:annotation>
            </xsd:element>
            <xsd:element maxOccurs="1" minOccurs="0" name="Enumeration" type="xsd:string"/>
        </xsd:choice>
    </xsd:complexType>
    <xsd:complexType name="telemetryType">
        <xsd:choice maxOccurs="unbounded">
            <xsd:element name="Subsystem" type="xsd:string">
                <xsd:annotation>
                    <xsd:documentation>Subsystem identifier</xsd:documentation>
                </xsd:annotation>
            </xsd:element>
            <xsd:element maxOccurs="1" minOccurs="0" name="Description" type="xsd:string"/>
            <xsd:element name="EFDB_Topic" type="xsd:string">
                <xsd:annotation>
                    <xsd:documentation>Engineering and Facility Database topic</xsd:documentation>
                </xsd:annotation>
            </xsd:element>
            <xsd:element maxOccurs="unbounded" minOccurs="1" name="item" type="telemetryItemType"/>
        </xsd:choice>
    </xsd:complexType>
    <xsd:complexType name="telemetrySetType">
        <xsd:sequence>
            <xsd:element maxOccurs="unbounded" minOccurs="0" name="Enumeration" type="xsd:string"/>
            <xsd:element maxOccurs="unbounded" minOccurs="1" name="SALTelemetry" type="telemetryType"/>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:attribute name="updateDate" type="xsd:date"/>
    <xsd:simpleType name="version">
        <xsd:restriction base="xsd:token">
            <xsd:pattern value="\d+\.\d+(\.\d+)?"/>
        </xsd:restriction>
    </xsd:simpleType>
</xsd:schema>

=== lsst-ts/ts_xml/python/lsst/ts/xml/data/sal_interfaces/Guider/Guider_Telemetry.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="http://lsst-sal.tuc.noao.edu/schema/SALTelemetrySet.xsl"?>
<SALTelemetrySet xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://lsst-sal.tuc.noao.edu/schema/SALTelemetrySet.xsd">
  <SALTelemetry>
    <Subsystem>Guider</Subsystem>
    <EFDB_Topic>Guider_offsets</EFDB_Topic>
    <Description>Computed guider offsets. The values are computed in the instrument reference frame and need to be de-rotated accordingly by the pointing.</Description>
    <item>
      <EFDB_Name>x</EFDB_Name>
      <Description>Guider offset in the (instrument) x-axis direction.</Description>
      <IDL_Type>double</IDL_Type>
      <Units>mm</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>y</EFDB_Name>
      <Description>Guider offset in the (instrument) y-axis direction.</Description>
      <IDL_Type>double</IDL_Type>
      <Units>mm</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>x_err</EFDB_Name>
      <Description>Uncertainty on the guider offset in x (standard error of the mean over the contributing guide sensors).</Description>
      <IDL_Type>double</IDL_Type>
      <Units>mm</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>y_err</EFDB_Name>
      <Description>Uncertainty on the guider offset in y (standard error of the mean over the contributing guide sensors).</Description>
      <IDL_Type>double</IDL_Type>
      <Units>mm</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>rotation</EFDB_Name>
      <Description>Guider rotation offset.</Description>
      <IDL_Type>double</IDL_Type>
      <Units>arcsec</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>n_sensors</EFDB_Name>
      <Description>Number of guide sensors contributing to the combined offset.</Description>
      <IDL_Type>int</IDL_Type>
      <Units>unitless</Units>
      <Count>1</Count>
    </item>
  </SALTelemetry>
</SALTelemetrySet>

=== lsst-ts/ts_xml/sal_interfaces/CatchupArchiver/CatchupArchiver_Telemetry.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="http://project.lsst.org/ts/sal_objects/schema/SALTelemetrySet.xsl"?>
<SALTelemetrySet xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="http://project.lsst.org/ts/sal_objects/schema/SALTelemetrySet.xsd">
<SALTelemetry>
    <Subsystem>CatchupArchiver</Subsystem>
    <Version>3.8</Version>
    <Author></Author>
    <EFDB_Topic>CatchupArchiver_sequencerHeartbeat</EFDB_Topic>
    <item>
        <EFDB_Name>name</EFDB_Name>
        <Description>Entitity name.</Description>
        <IDL_Type>string</IDL_Type>
        <IDL_Size>128</IDL_Size>
        <Units>unitless</Units>
        <Count>1</Count>
    </item>
    <item>
        <EFDB_Name>identifier</EFDB_Name>
        <Description>Entity identifier</Description>
        <IDL_Type>float</IDL_Type>
        <Units>unitless</Units>
        <Count>1</Count>
    </item>
    <item>
        <EFDB_Name>timestamp</EFDB_Name>
        <Description>Timestamp the topic was generated.</Description>
        <IDL_Type>string</IDL_Type>
        <IDL_Size>256</IDL_Size>
        <Units>unitless</Units>
        <Count>1</Count>
    </item>
</SALTelemetry></SALTelemetrySet>

=== lsst-ts/ts_xml/sal_interfaces/EAS/EAS_Telemetry.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="http://lsst-sal.tuc.noao.edu/schema/SALTelemetrySet.xsl"?>
<SALTelemetrySet xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="http://lsst-sal.tuc.noao.edu/schema/SALTelemetrySet.xsd">
<SALTelemetry>
    <Subsystem>EAS</Subsystem>
    <Version>3.8.38</Version>
    <Author></Author>
    <EFDB_Topic>EAS_timestamp</EFDB_Topic>
    <item>
        <EFDB_Name>timestamp</EFDB_Name>
        <Description>The system time (TAI).</Description>
        <IDL_Type>double</IDL_Type>
        <Units></Units>
        <Count>1</Count>
    </item>
</SALTelemetry>
<SALTelemetry>
    <Subsystem>EAS</Subsystem>
    <Version>3.8.38</Version>
    <Author></Author>
    <EFDB_Topic>EAS_loopTime</EFDB_Topic>
    <item>
        <EFDB_Name>loopTime</EFDB_Name>
        <Description>The actual loop time is milliseconds.</Description>
        <IDL_Type>double</IDL_Type>
        <Units></Units>
        <Count>1</Count>
    </item>
</SALTelemetry>
<SALTelemetry>
    <Subsystem>EAS</Subsystem>
    <Version>3.8.38</Version>
    <Author></Author>
    <EFDB_Topic>EAS_airTemperature</EFDB_Topic>
    <item>
        <EFDB_Name>airTemperature</EFDB_Name>
        <Description>Temperature from the air temperature probes inside dome.</Description>
        <IDL_Type>double</IDL_Type>
        <Units></Units>
        <Count>48</Count>
    </item>
</SALTelemetry>
<SALTelemetry>
    <Subsystem>EAS</Subsystem>
    <Version>3.8.38</Version>
    <Author></Author>
    <EFDB_Topic>EAS_surfaceTemperature</EFDB_Topic>
    <item>
        <EFDB_Name>surfaceTemperature</EFDB_Name>
        <Description>Temperature from the major thermal masses dome.</Description>
        <IDL_Type>double</IDL_Type>
        <Units></Units>
        <Count>58</Count>
    </item>
</SALTelemetry>
<SALTelemetry>
    <Subsystem>EAS</Subsystem>
    <Version>3.8.38</Version>
    <Author></Author>
    <EFDB_Topic>EAS_humidity</EFDB_Topic>
    <item>
        <EFDB_Name>humidity</EFDB_Name>
        <Description>probes measuring the water content of the air inside dome.</Description>
        <IDL_Type>double</IDL_Type>
        <Units></Units>
        <Count>5</Count>
    </item>
</SALTelemetry>
<SALTelemetry>
    <Subsystem>EAS</Subsystem>
    <Version>3.8.38</Version>
    <Author></Author>
    <EFDB_Topic>EAS_barometricPressure</EFDB_Topic>
    <item>
        <EFDB_Name>barometricPressure</EFDB_Name>
        <Description>barometric pressure from weather station outside dome.</Description>
        <IDL_Type>double</IDL_Type>
        <Units></Units>
        <Count>1</Count>
    </item>
</SALTelemetry>
<SALTelemetry>
    <Subsystem>EAS</Subsystem>
    <Version>3.8.38</Version>
    <Author></Author>
    <EFDB_Topic>EAS_airflowDynamics</EFDB_Topic>
    <item>
        <EFDB_Name>airflowDynamics</EFDB_Name>
        <Description>amount of air turbulance from 2D anemometers from inside dome.</Description>
        <IDL_Type>double</IDL_Type>
        <Units></Units>
        <Count>18</Count>
    </item>
</SALTelemetry>
<SALTelemetry>
    <Subsystem>EAS</Subsystem>
    <Version>3.8.38</Version>
    <Author></Author>
    <EFDB_Topic>EAS_bulkAirflow</EFDB_Topic>
    <item>
        <EFDB_Name>bulkAirflow</EFDB_Name>
        <Description>measurements of the bulk airflow from the HVAC and downdraft systems.</Description>
        <IDL_Type>double</IDL_Type>
        <Units></Units>
        <Count>15</Count>
    </item>
</SALTelemetry>
<SALTelemetry>
    <Subsystem>EAS</Subsystem>
    <Version>3.8.38</Version>
    <Author></Author>
    <EFDB_Topic>EAS_radioFrequencyInterference</EFDB_Topic>
    <item>
        <EFDB_Name>radioFrequencyInterference</EFDB_Name>
        <Description>spectrum analyzer show radio frequency interference inside dome.</Description>
        <IDL_Type>double</IDL_Type>
        <Units></Units>
        <Count>1</Count>
    </item>
</SALTelemetry>
<SALTelemetry>
    <Subsystem>EAS</Subsystem>
    <Version>3.8.38</Version>
    <Author></Author>
    <EFDB_Topic>EAS_currentLeakage</EFDB_Topic>
    <item>
        <EFDB_Name>currentLeakage</EFDB_Name>
        <Description>main power current leakage from ground.</Description>
        <IDL_Type>double</IDL_Type>
        <Units></Units>
        <Count>1</Count>
    </item>
</SALTelemetry>
<SALTelemetry>
    <Subsystem>EAS</Subsystem>
    <Version>3.8.38</Version>
    <Author></Author>
    <EFDB_Topic>EAS_weatherStation</EFDB_Topic>
    <item>
        <EFDB_Name>weatherStation</EFDB_Name>
        <Description>external environment monitoring (there should be more items here, but I don't know what).</Description>
        <IDL_Type>double</IDL_Type>
        <Units></Units>
        <Count>1</Count>
    </item>
</SALTelemetry>
<SALTelemetry>
    <Subsystem>EAS</Subsystem>
    <Version>3.8.38</Version>
    <Author></Author>
    <EFDB_Topic>EAS_accelrometers</EFDB_Topic>
    <item>
        <EFDB_Name>accelrometers</EFDB_Name>
        <Description>measuring vibrations inside dome.</Description>
        <IDL_Type>double</IDL_Type>
        <Units></Units>
        <Count>10</Count>
    </item>
</SALTelemetry>
<SALTelemetry>
    <Subsystem>EAS</Subsystem>
    <Version>3.8.38</Version>
    <Author></Author>
    <EFDB_Topic>EAS_interiorAcoustics</EFDB_Topic>
    <item>
        <EFDB_Name></EFDB_Name>
        <Description>current volume of noise inside dome.</Description>
        <IDL_Type>double</IDL_Type>
        <Units></Units>
        <Count>1</Count>
    </item>
</SALTelemetry>
<SALTelemetry>
    <Subsystem>EAS</Subsystem>
    <Version>3.8.38</Version>
    <Author></Author>
    <EFDB_Topic>EAS_sonicAnemometers</EFDB_Topic>
    <item>
        <EFDB_Name>sonicAnemometers</EFDB_Name>
        <Description>3D sonic anemoeters measuring air turbulence inside dome.</Description>
        <IDL_Type>double</IDL_Type>
        <Units></Units>
        <Count>12</Count>
    </item>
</SALTelemetry>
</SALTelemetrySet>

=== lsst-ts/ts_xml/sal_interfaces/calibrationElectrometer/calibrationElectrometer_Telemetry.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="http://lsst-sal.tuc.noao.edu/schema/SALTelemetrySet.xsl"?>
<SALTelemetrySet xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="http://lsst-sal.tuc.noao.edu/schema/SALTelemetrySet.xsd">
<SALTelemetry>
    <Subsystem>calibrationElectrometer</Subsystem>
    <Version>3.7.1</Version>
    <Author></Author>
    <EFDB_Topic>calibrationElectrometer_loopTime</EFDB_Topic>
    <item>
        <EFDB_Name>loopTime</EFDB_Name>
        <Description>The actual loop time is ms.
</Description>
        <IDL_Type>double</IDL_Type>
        <Units></Units>
        <Count>1</Count>
    </item>
    <item>
        <EFDB_Name>electId</EFDB_Name>
        <Description></Description>
        <IDL_Type>string</IDL_Type>
        <IDL_Size>256</IDL_Size>
        <Units></Units>
        <Count>1</Count>
    </item>
</SALTelemetry>
<SALTelemetry>
    <Subsystem>calibrationElectrometer</Subsystem>
    <Version>3.7.1</Version>
    <Author></Author>
    <EFDB_Topic>calibrationElectrometer_timestamp</EFDB_Topic>
    <item>
        <EFDB_Name>timestamp</EFDB_Name>
        <Description>The system time (TAI).</Description>
        <IDL_Type>double</IDL_Type>
        <Units></Units>
        <Count>1</Count>
    </item>
    <item>
        <EFDB_Name>electId</EFDB_Name>
        <Description></Description>
        <IDL_Type>string</IDL_Type>
        <IDL_Size>256</IDL_Size>
        <Units></Units>
        <Count>1</Count>
    </item>
</SALTelemetry></SALTelemetrySet>

=== lsst-ts/ts_xml/sal_interfaces/PMD/PMD_Telemetry.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="http://lsst-sal.tuc.noao.edu/schema/SALTelemetrySet.xsl"?>
<SALTelemetrySet xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://lsst-sal.tuc.noao.edu/schema/SALTelemetrySet.xsd">
  <SALTelemetry>
    <Subsystem>PMD</Subsystem>
    <EFDB_Topic>PMD_position</EFDB_Topic>
    <item>
      <EFDB_Name>position</EFDB_Name>
      <Description>The position of the device.</Description>
      <IDL_Type>double</IDL_Type>
      <Units>millimeter</Units>
      <Count>1</Count>
    </item>
  </SALTelemetry>
</SALTelemetrySet>

=== lsst-ts/ts_xml/python/lsst/ts/xml/data/sal_interfaces/DSM/DSM_Telemetry.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="http://lsst-sal.tuc.noao.edu/schema/SALTelemetrySet.xsl"?>
<SALTelemetrySet xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://lsst-sal.tuc.noao.edu/schema/SALTelemetrySet.xsd">
  <SALTelemetry>
    <Subsystem>DSM</Subsystem>
    <EFDB_Topic>DSM_domeSeeing</EFDB_Topic>
    <Description>Measured quantities associated with dome seeing from a DSM device.</Description>
    <item>
      <EFDB_Name>dsmIndex</EFDB_Name>
      <Description>The index of the DSM unit.</Description>
      <IDL_Type>long</IDL_Type>
      <Units>unitless</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>timestampCurrent</EFDB_Name>
      <Description>The TAI timestamp of the current buffer measurement.</Description>
      <IDL_Type>double</IDL_Type>
      <Units>second</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>timestampFirstMeasurement</EFDB_Name>
      <Description>The TAI timestamp of the first measurement in the buffer.</Description>
      <IDL_Type>double</IDL_Type>
      <Units>second</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>timestampLastMeasurement</EFDB_Name>
      <Description>The TAI timestamp of the last measurement in the buffer.</Description>
      <IDL_Type>double</IDL_Type>
      <Units>second</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>rmsX</EFDB_Name>
      <Description>The standard deviation of the buffer centroids in the X direction.</Description>
      <IDL_Type>double</IDL_Type>
      <Units>arcsec</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>rmsY</EFDB_Name>
      <Description>The standard deviation of the buffer centroids in the Y direction.</Description>
      <IDL_Type>double</IDL_Type>
      <Units>arcsec</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>centroidX</EFDB_Name>
      <Description>The average spot position of the buffer centroids in the X direction.</Description>
      <IDL_Type>double</IDL_Type>
      <Units>pixel</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>centroidY</EFDB_Name>
      <Description>The average spot position of the buffer centroids in the Y direction.</Description>
      <IDL_Type>double</IDL_Type>
      <Units>pixel</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>flux</EFDB_Name>
      <Description>The average of the frame fluxes (ADU) in the buffer tracking the centroids.</Description>
      <IDL_Type>double</IDL_Type>
      <Units>unitless</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>maxADC</EFDB_Name>
      <Description>The average of the frame maximum ADC values in the buffer tracking the centroids.</Description>
      <IDL_Type>double</IDL_Type>
      <Units>unitless</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>fwhm</EFDB_Name>
      <Description>The average of the spot full-width, half-maxes in the buffer tracking the centroids.</Description>
      <IDL_Type>double</IDL_Type>
      <Units>pixel</Units>
      <Count>1</Count>
    </item>
  </SALTelemetry>
</SALTelemetrySet>

=== lsst-ts/ts_xml/sal_interfaces/dmHeaderService/dmHeaderService_Telemetry.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="http://lsst-sal.tuc.noao.edu/schema/SALTelemetrySet.xsl"?>
<SALTelemetrySet xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="http://lsst-sal.tuc.noao.edu/schema/SALTelemetrySet.xsd">
<SALTelemetry>
    <Subsystem>dmHeaderService</Subsystem>
    <Version>3.5.1</Version>
    <Author>aanania</Author>
    <EFDB_Topic>dmHeaderService_LoopTime_ms</EFDB_Topic>
    <item>
        <EFDB_Name>loopTime_ms</EFDB_Name>
        <Description>The actual loop time is ms.
</Description>
        <IDL_Type>double</IDL_Type>
        <Units></Units>
        <Count>1</Count>
    </item>
</SALTelemetry>
<SALTelemetry>
    <Subsystem>dmHeaderService</Subsystem>
    <Version>3.5.1</Version>
    <Author>aanania</Author>
    <EFDB_Topic>dmHeaderService_Timestamp</EFDB_Topic>
    <item>
        <EFDB_Name>timestamp</EFDB_Name>
        <Description>The system time (TAI).</Description>
        <IDL_Type>double</IDL_Type>
        <Units></Units>
        <Count>1</Count>
    </item>
</SALTelemetry></SALTelemetrySet>

=== lsst-ts/ts_xml/sal_interfaces/MTAlignment/MTAlignment_Telemetry.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="http://lsst-sal.tuc.noao.edu/schema/SALTelemetrySet.xsl"?>
<SALTelemetrySet xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="http://lsst-sal.tuc.noao.edu/schema/SALTelemetrySet.xsd">
<SALTelemetry>
    <Subsystem>MTAlignment</Subsystem>
    <Version>3.7.1</Version>
    <Author>Colin Winslow</Author>
    <EFDB_Topic>MTAlignment_trackertemp</EFDB_Topic>
    <item>
        <EFDB_Name>temperature</EFDB_Name>
        <Description>current temperature reported by the tracker sensor</Description>
        <IDL_Type>double</IDL_Type>
        <Units>deg_C</Units>
        <Count>1</Count>
    </item>
</SALTelemetry>
</SALTelemetrySet>
