=== lsst-ts/ts_xml/schema/SALTelemetrySet.xsd
<xsd:schema attributeFormDefault="unqualified" elementFormDefault="unqualified" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <xsd:annotation>
        <xsd:documentation xml:lang="en">SAL telemetry data item schema for LSST
    </xsd:documentation>
    </xsd:annotation>
    <xsd:element name="SALTelemetrySet" type="telemetrySetType"/>
    <xsd:element name="SALTelemetry" type="telemetryType"/>
    <xsd:element name="SALTelemetryItem" type="telemetryItemType"/>
    <xsd:complexType name="telemetryItemType">
        <xsd:annotation>
            <xsd:documentation>Telemetry items parameters and values</xsd:documentation>
        </xsd:annotation>
        <xsd:choice maxOccurs="unbounded">
            <xsd:element name="EFDB_Name" type="xsd:string">
                <xsd:annotation>
                    <xsd:documentation>Engineering and Facility Database name</xsd:documentation>
                </xsd:annotation>
            </xsd:element>
            <xsd:element name="Description" type="xsd:string">
                <xsd:annotation>
                    <xsd:documentation>Description of telemetry item</xsd:documentation>
                </xsd:annotation>
            </xsd:element>
            <xsd:element maxOccurs="1" minOccurs="0" name="Size_in_bytes" type="xsd:positiveInteger">
                <xsd:annotation>
                    <xsd:documentation>Size of telemetry item in bytes</xsd:documentation>
                </xsd:annotation>
            </xsd:element>
            <xsd:element name="IDL_Type" type="xsd:string">
                <xsd:annotation>
                    <xsd:documentation>IDL type of telemetry item</xsd:documentation>
                </xsd:annotation>
            </xsd:element>
            <xsd:element minOccurs="0" name="IDL_Size" type="xsd:string"/>
            <xsd:element name="Units" type="xsd:string">
                <xsd:annotation>
                    <xsd:documentation>Units (if known)</xsd:documentation>
                </xsd:annotation>
            </xsd:element>
            <xsd:element name="Count" type="xsd:positiveInteger">
                <xsd:annotation>
                    <xsd:documentation>Count</xsd:documentation>
                </xsd:annotation>
            </xsd:element>
            <xsd:element maxOccurs="1" minOccurs="0" name="Enumeration" type="xsd:string"/>
        </xsd:choice>
    </xsd:complexType>
    <xsd:complexType name="telemetryType">
        <xsd:choice maxOccurs="unbounded">
            <xsd:element name="Subsystem" type="xsd:string">
                <xsd:annotation>
                    <xsd:documentation>Subsystem identifier</xsd:documentation>
                </xsd:annotation>
            </xsd:element>
            <xsd:element maxOccurs="1" minOccurs="0" name="Description" type="xsd:string"/>
            <xsd:element name="EFDB_Topic" type="xsd:string">
                <xsd:annotation>
                    <xsd:documentation>Engineering and Facility Database topic</xsd:documentation>
                </xsd:annotation>
            </xsd:element>
            <xsd:element maxOccurs="unbounded" minOccurs="1" name="item" type="telemetryItemType"/>
        </xsd:choice>
    </xsd:complexType>
    <xsd:complexType name="telemetrySetType">
        <xsd:sequence>
            <xsd:element maxOccurs="unbounded" minOccurs="0" name="Enumeration" type="xsd:string"/>
            <xsd:element maxOccurs="unbounded" minOccurs="1" name="SALTelemetry" type="telemetryType"/>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:attribute name="updateDate" type="xsd:date"/>
    <xsd:simpleType name="version">
        <xsd:restriction base="xsd:token">
            <xsd:pattern value="\d+\.\d+(\.\d+)?"/>
        </xsd:restriction>
    </xsd:simpleType>
</xsd:schema>

=== lsst-ts/ts_xml/sal_interfaces/IOTA/IOTA_Telemetry.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="http://lsst-sal.tuc.noao.edu/schema/SALTelemetrySet.xsl"?>
<SALTelemetrySet xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://lsst-sal.tuc.noao.edu/schema/SALTelemetrySet.xsd">
  <SALTelemetry>
    <Subsystem>IOTA</Subsystem>
    <Version>3.8.31</Version>
    <Author/>
    <EFDB_Topic>IOTA_timestamp</EFDB_Topic>
    <item>
      <EFDB_Name>timestamp</EFDB_Name>
      <Description>The system time (TAI).</Description>
      <IDL_Type>double</IDL_Type>
      <Units>second</Units>
      <Count>1</Count>
    </item>
  </SALTelemetry>
  <SALTelemetry>
    <Subsystem>IOTA</Subsystem>
    <Version>3.8.31</Version>
    <Author/>
    <EFDB_Topic>IOTA_loopTime</EFDB_Topic>
    <item>
      <EFDB_Name>loopTime</EFDB_Name>
      <Description>The actual loop time is milliseconds.</Description>
      <IDL_Type>double</IDL_Type>
      <Units>second</Units>
      <Count>1</Count>
    </item>
  </SALTelemetry>
</SALTelemetrySet>

=== lsst-ts/ts_xml/sal_interfaces/Guider/Guider_Telemetry.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="http://lsst-sal.tuc.noao.edu/schema/SALTelemetrySet.xsl"?>
<SALTelemetrySet xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://lsst-sal.tuc.noao.edu/schema/SALTelemetrySet.xsd">
  <SALTelemetry>
    <Subsystem>Guider</Subsystem>
    <EFDB_Topic>Guider_offsets</EFDB_Topic>
    <Description>Computed guider offsets. The values are computed in the instrument reference frame and need to be de-rotated accordingly by the pointing.</Description>
    <item>
      <EFDB_Name>x</EFDB_Name>
      <Description>Guider offset in the (instrument) x-axis direction.</Description>
      <IDL_Type>double</IDL_Type>
      <Units>arcsec</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>y</EFDB_Name>
      <Description>Guider offset in the (instrument) y-axis direction.</Description>
      <IDL_Type>double</IDL_Type>
      <Units>arcsec</Units>
      <Count>1</Count>
    </item>
  </SALTelemetry>
</SALTelemetrySet>

=== lsst-ts/ts_xml/sal_interfaces/AdamSensors/AdamSensors_Telemetry.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="http://lsst-sal.tuc.noao.edu/schema/SALTelemetrySet.xsl"?>
<SALTelemetrySet xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://lsst-sal.tuc.noao.edu/schema/SALTelemetrySet.xsd">
  <SALTelemetry>
    <Subsystem>AdamSensors</Subsystem>
    <Version>3.8.2</Version>
    <Description>Temperature readings from sensors connected to an ADAM-6024</Description>
    <EFDB_Topic>AdamSensors_temperature</EFDB_Topic>
    <item>
      <EFDB_Name>temp_ch0</EFDB_Name>
      <Description>Temperature reading on ADAM Analog Input 0</Description>
      <IDL_Type>float</IDL_Type>
      <Units>deg_C</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>temp_ch1</EFDB_Name>
      <Description>Temperature reading on ADAM Analog Input 1</Description>
      <IDL_Type>float</IDL_Type>
      <Units>deg_C</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>temp_ch2</EFDB_Name>
      <Description>Temperature reading on ADAM Analog Input 2</Description>
      <IDL_Type>float</IDL_Type>
      <Units>deg_C</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>temp_ch3</EFDB_Name>
      <Description>Temperature reading on ADAM Analog Input 3</Description>
      <IDL_Type>float</IDL_Type>
      <Units>deg_C</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>temp_ch4</EFDB_Name>
      <Description>Temperature reading on ADAM Analog Input 4</Description>
      <IDL_Type>float</IDL_Type>
      <Units>deg_C</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>temp_ch5</EFDB_Name>
      <Description>Temperature reading on ADAM Analog Input 5</Description>
      <IDL_Type>float</IDL_Type>
      <Units>deg_C</Units>
      <Count>1</Count>
    </item>
  </SALTelemetry>
  <SALTelemetry>
    <Subsystem>AdamSensors</Subsystem>
    <Version>3.8.2</Version>
    <Description>Pressure readings from sensors connected to an ADAM 6024</Description>
    <EFDB_Topic>AdamSensors_pressure</EFDB_Topic>
    <item>
      <EFDB_Name>pressure_ch0</EFDB_Name>
      <Description>Pressure reading on ADAM Analog Input 0</Description>
      <IDL_Type>float</IDL_Type>
      <Units>Pa</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>pressure_ch1</EFDB_Name>
      <Description>Pressure reading on ADAM Analog Input 1</Description>
      <IDL_Type>float</IDL_Type>
      <Units>Pa</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>pressure_ch2</EFDB_Name>
      <Description>Pressure reading on ADAM Analog Input 2</Description>
      <IDL_Type>float</IDL_Type>
      <Units>Pa</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>pressure_ch3</EFDB_Name>
      <Description>Pressure reading on ADAM Analog Input 3</Description>
      <IDL_Type>float</IDL_Type>
      <Units>Pa</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>pressure_ch4</EFDB_Name>
      <Description>Pressure reading on ADAM Analog Input 4</Description>
      <IDL_Type>float</IDL_Type>
      <Units>Pa</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>pressure_ch5</EFDB_Name>
      <Description>Pressure reading on ADAM Analog Input 5</Description>
      <IDL_Type>float</IDL_Type>
      <Units>Pa</Units>
      <Count>1</Count>
    </item>
  </SALTelemetry>
</SALTelemetrySet>

=== lsst-ts/ts_xml/sal_interfaces/LinearStage/LinearStage_Telemetry.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="http://lsst-sal.tuc.noao.edu/schema/SALTelemetrySet.xsl"?>
<SALTelemetrySet xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://lsst-sal.tuc.noao.edu/schema/SALTelemetrySet.xsd">
  <SALTelemetry>
    <Subsystem>LinearStage</Subsystem>
    <Version>3.7.1</Version>
    <Author>ecoughlin</Author>
    <EFDB_Topic>LinearStage_position</EFDB_Topic>
    <item>
      <EFDB_Name>position</EFDB_Name>
      <Description>The position of the linear stage along the track</Description>
      <IDL_Type>float</IDL_Type>
      <Units>millimeter</Units>
      <Count>1</Count>
    </item>
  </SALTelemetry>
</SALTelemetrySet>

=== lsst-ts/ts_xml/sal_interfaces/ATBuilding/ATBuilding_Telemetry.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="http://lsst-sal.tuc.noao.edu/schema/SALTelemetrySet.xsl"?>
<SALTelemetrySet xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="http://lsst-sal.tuc.noao.edu/schema/SALTelemetrySet.xsd">
<SALTelemetry>
    <Subsystem>ATBuilding</Subsystem>
    <Version>3.8.31</Version>
    <Author></Author>
    <EFDB_Topic>ATBuilding_timestamp</EFDB_Topic>
    <item>
        <EFDB_Name>timestamp</EFDB_Name>
        <Description>The system time (TAI).</Description>
        <IDL_Type>double</IDL_Type>
        <Units>unitless</Units>
        <Count>1</Count>
    </item>
</SALTelemetry>
<SALTelemetry>
    <Subsystem>ATBuilding</Subsystem>
    <Version>3.8.31</Version>
    <Author></Author>
    <EFDB_Topic>ATBuilding_loopTime</EFDB_Topic>
    <item>
        <EFDB_Name>loopTime</EFDB_Name>
        <Description>The actual loop time is milliseconds.</Description>
        <IDL_Type>double</IDL_Type>
        <Units>unitless</Units>
        <Count>1</Count>
    </item>
</SALTelemetry></SALTelemetrySet>

=== lsst-ts/ts_xml/sal_interfaces/PromptProcessing/PromptProcessing_Telemetry.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="http://project.lsst.org/ts/sal_objects/schema/SALTelemetrySet.xsl"?>
<SALTelemetrySet xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://project.lsst.org/ts/sal_objects/schema/SALTelemetrySet.xsd">
  <SALTelemetry>
    <Subsystem>PromptProcessing</Subsystem>
    <Version>3.8</Version>
    <Author/>
    <EFDB_Topic>PromptProcessing_sequencerHeartbeat</EFDB_Topic>
    <item>
      <EFDB_Name>name</EFDB_Name>
      <Description>Name of the entity to startup.</Description>
      <IDL_Type>string</IDL_Type>
      <IDL_Size>256</IDL_Size>
      <Units>unitless</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>identifier</EFDB_Name>
      <Description>Entity identifier.</Description>
      <IDL_Type>double</IDL_Type>
      <Units>unitless</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>timestamp</EFDB_Name>
      <Description>Timestamp the event data was generated.</Description>
      <IDL_Type>string</IDL_Type>
      <IDL_Size>256</IDL_Size>
      <Units>second</Units>
      <Count>1</Count>
    </item>
  </SALTelemetry>
</SALTelemetrySet>

=== lsst-ts/ts_xml/sal_interfaces/CBP/CBP_Telemetry.xml
<?xml version="1.0" encoding="UTF-8" ?>
<?xml-stylesheet type="text/xsl" href="http://lsst-sal.tuc.noao.edu/schema/SALTelemetrySet.xsl"?>
<SALTelemetrySet xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://lsst-sal.tuc.noao.edu/schema/SALTelemetrySet.xsd">
    <SALTelemetry>
        <Subsystem>CBP</Subsystem>
        <Version>3.8</Version>
        <Author>ecoughlin</Author>
        <EFDB_Topic>CBP_status</EFDB_Topic>
        <item>
            <EFDB_Name>panic</EFDB_Name>
            <Description>The status of the CBP.</Description>
            <IDL_Type>float</IDL_Type>
            <Units>unitless</Units>
            <Count>1</Count>
        </item>
        <item>
            <EFDB_Name>azimuth</EFDB_Name>
            <Description>The status of the azimuth motor.</Description>
            <IDL_Type>float</IDL_Type>
            <Units>unitless</Units>
            <Count>1</Count>
        </item>
        <item>
            <EFDB_Name>altitude</EFDB_Name>
            <Description>The status of the altitude motor</Description>
            <IDL_Type>float</IDL_Type>
            <Units>unitless</Units>
            <Count>1</Count>
        </item>
        <item>
            <EFDB_Name>mask</EFDB_Name>
            <Description>The status of the mask encoder</Description>
            <IDL_Type>float</IDL_Type>
            <Units>unitless</Units>
            <Count>1</Count>
        </item>
        <item>
            <EFDB_Name>mask_rotation</EFDB_Name>
            <Description>The status of the mask rotation motor</Description>
            <IDL_Type>float</IDL_Type>
            <Units>unitless</Units>
            <Count>1</Count>
        </item>
        <item>
            <EFDB_Name>focus</EFDB_Name>
            <Description>The status of the focus encoder</Description>
            <IDL_Type>float</IDL_Type>
            <Units>unitless</Units>
            <Count>1</Count>
        </item>
    </SALTelemetry>
    <SALTelemetry>
        <Subsystem>CBP</Subsystem>
        <Version>3.8</Version>
        <Author>ecoughlin</Author>
        <EFDB_Topic>CBP_mask</EFDB_Topic>
        <item>
            <EFDB_Name>mask</EFDB_Name>
            <Description>The mask of the CBP.</Description>
            <IDL_Type>string</IDL_Type>
            <Units>unitless</Units>
            <Count>1</Count>
        </item>
        <item>
            <EFDB_Name>mask_rotation</EFDB_Name>
            <Description>The mask rotation of the CBP.</Description>
            <IDL_Type>float</IDL_Type>
            <Units>degree</Units>
            <Count>1</Count>
        </item>
    </SALTelemetry>
    <SALTelemetry>
        <Subsystem>CBP</Subsystem>
        <Version>3.8</Version>
        <Author>ecoughlin</Author>
        <EFDB_Topic>CBP_azimuth</EFDB_Topic>
        <item>
            <EFDB_Name>azimuth</EFDB_Name>
            <Description>The azimuth of the CBP.</Description>
            <IDL_Type>float</IDL_Type>
            <Units>degree</Units>
            <Count>1</Count>
        </item>
    </SALTelemetry>
    <SALTelemetry>
        <Subsystem>CBP</Subsystem>
        <Version>3.8</Version>
        <Author>ecoughlin</Author>
        <EFDB_Topic>CBP_altitude</EFDB_Topic>
        <item>
            <EFDB_Name>altitude</EFDB_Name>
            <Description>The altitude of the CBP</Description>
            <IDL_Type>float</IDL_Type>
            <Units>degree</Units>
            <Count>1</Count>
        </item>
    </SALTelemetry>
    <SALTelemetry>
        <Subsystem>CBP</Subsystem>
        <Version>3.8</Version>
        <Author>ecoughlin</Author>
        <EFDB_Topic>CBP_focus</EFDB_Topic>
        <item>
            <EFDB_Name>focus</EFDB_Name>
            <Description>The focus of the CBP.</Description>
            <IDL_Type>float</IDL_Type>
            <Units>millimeter</Units>
            <Count>1</Count>
        </item>
    </SALTelemetry>
    <SALTelemetry>
        <Subsystem>CBP</Subsystem>
        <Version>3.8</Version>
        <Author>ecoughlin</Author>
        <EFDB_Topic>CBP_parked</EFDB_Topic>
        <item>
            <EFDB_Name>autoparked</EFDB_Name>
            <Description>Whether the CBP has been autoparked or not.</Description>
            <IDL_Type>float</IDL_Type>
            <Units>unitless</Units>
            <Count>1</Count>
        </item>
        <item>
            <EFDB_Name>parked</EFDB_Name>
            <Description>Whether the CBP is parked or not.</Description>
            <IDL_Type>float</IDL_Type>
            <Units>unitless</Units>
            <Count>1</Count>
        </item>
    </SALTelemetry>
</SALTelemetrySet>

=== lsst-ts/ts_xml/sal_interfaces/MTAirCompressor/MTAirCompressor_Telemetry.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="http://lsst-sal.tuc.noao.edu/schema/SALTelemetrySet.xsl"?>
<SALTelemetrySet xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://lsst-sal.tuc.noao.edu/schema/SALTelemetrySet.xsd">
  <SALTelemetry>
    <Subsystem>MTAirCompressor</Subsystem>
    <EFDB_Topic>MTAirCompressor_analogData</EFDB_Topic>
    <Description>Compressor analog data.</Description>
    <item>
      <EFDB_Name>waterLevel</EFDB_Name>
      <Description>Compressor water level.</Description>
      <IDL_Type>int</IDL_Type>
      <Units>%</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>targetSpeed</EFDB_Name>
      <Description>Compressor speed target.</Description>
      <IDL_Type>int</IDL_Type>
      <Units>RPM</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>motorCurrent</EFDB_Name>
      <Description>Motor current.</Description>
      <IDL_Type>float</IDL_Type>
      <Units>A</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>heatsinkTemperature</EFDB_Name>
      <Description>Heatsink temperature.</Description>
      <IDL_Type>float</IDL_Type>
      <Units>deg_C</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>dclinkVoltage</EFDB_Name>
      <Description>DC link voltage.</Description>
      <IDL_Type>float</IDL_Type>
      <Units>V</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>motorSpeedPercentage</EFDB_Name>
      <Description>Motor speed (%).</Description>
      <IDL_Type>float</IDL_Type>
      <Units>%</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>motorSpeedRPM</EFDB_Name>
      <Description>Motor speed (RPM).</Description>
      <IDL_Type>int</IDL_Type>
      <Units>RPM</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>motorInput</EFDB_Name>
      <Description>Motor powr input.</Description>
      <IDL_Type>float</IDL_Type>
      <Units>kW</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>compressorPowerConsumption</EFDB_Name>
      <Description>Compressor power consumption.</Description>
      <IDL_Type>float</IDL_Type>
      <Units>kW</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>compressorVolumePercentage</EFDB_Name>
      <Description>Compressor volume (%).</Description>
      <IDL_Type>int</IDL_Type>
      <Units>%</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>compressorVolume</EFDB_Name>
      <Description>Compressor volume (m3/min).</Description>
      <IDL_Type>float</IDL_Type>
      <Units>m3/min</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>groupVolume</EFDB_Name>
      <Description>Group volume.</Description>
      <IDL_Type>float</IDL_Type>
      <Units>m3/min</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>stage1OutputPressure</EFDB_Name>
      <Description>Stage 1 output pressure.</Description>
      <IDL_Type>int</IDL_Type>
      <Units>mbar</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>linePressure</EFDB_Name>
      <Description>Line pressure.</Description>
      <IDL_Type>int</IDL_Type>
      <Units>mbar</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>stage1OutputTemperature</EFDB_Name>
      <Description>Stage 1 output temperature.</Description>
      <IDL_Type>float</IDL_Type>
      <Units>deg_C</Units>
      <Count>1</Count>
    </item>
  </SALTelemetry>
</SALTelemetrySet>
