=== lsst-ts/ts_xml/schema/SALTelemetrySet.xsd
<xsd:schema attributeFormDefault="unqualified" elementFormDefault="unqualified" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <xsd:annotation>
        <xsd:documentation xml:lang="en">SAL telemetry data item schema for LSST
    </xsd:documentation>
    </xsd:annotation>
    <xsd:element name="SALTelemetrySet" type="telemetrySetType"/>
    <xsd:element name="SALTelemetry" type="telemetryType"/>
    <xsd:element name="SALTelemetryItem" type="telemetryItemType"/>
    <xsd:complexType name="telemetryItemType">
        <xsd:annotation>
            <xsd:documentation>Telemetry items parameters and values</xsd:documentation>
        </xsd:annotation>
        <xsd:choice maxOccurs="unbounded">
            <xsd:element name="EFDB_Name" type="xsd:string">
                <xsd:annotation>
                    <xsd:documentation>Engineering and Facility Database name</xsd:documentation>
                </xsd:annotation>
            </xsd:element>
            <xsd:element name="Description" type="xsd:string">
                <xsd:annotation>
                    <xsd:documentation>Description of telemetry item</xsd:documentation>
                </xsd:annotation>
            </xsd:element>
            <xsd:element maxOccurs="1" minOccurs="0" name="Size_in_bytes" type="xsd:positiveInteger">
                <xsd:annotation>
                    <xsd:documentation>Size of telemetry item in bytes</xsd:documentation>
                </xsd:annotation>
            </xsd:element>
            <xsd:element name="IDL_Type" type="xsd:string">
                <xsd:annotation>
                    <xsd:documentation>IDL type of telemetry item</xsd:documentation>
                </xsd:annotation>
            </xsd:element>
            <xsd:element minOccurs="0" name="IDL_Size" type="xsd:string"/>
            <xsd:element name="Units" type="xsd:string">
                <xsd:annotation>
                    <xsd:documentation>Units (if known)</xsd:documentation>
                </xsd:annotation>
            </xsd:element>
            <xsd:element name="Count" type="xsd:positiveInteger">
                <xsd:annotation>
                    <xsd:documentation>Count</xsd:documentation>
                </xsd:annotation>
            </xsd:element>
            <xsd:element maxOccurs="1" minOccurs="0" name="Enumeration" type="xsd:string"/>
        </xsd:choice>
    </xsd:complexType>
    <xsd:complexType name="telemetryType">
        <xsd:choice maxOccurs="unbounded">
            <xsd:element name="Subsystem" type="xsd:string">
                <xsd:annotation>
                    <xsd:documentation>Subsystem identifier</xsd:documentation>
                </xsd:annotation>
            </xsd:element>
            <xsd:element maxOccurs="1" minOccurs="0" name="Description" type="xsd:string"/>
            <xsd:element name="EFDB_Topic" type="xsd:string">
                <xsd:annotation>
                    <xsd:documentation>Engineering and Facility Database topic</xsd:documentation>
                </xsd:annotation>
            </xsd:element>
            <xsd:element maxOccurs="unbounded" minOccurs="1" name="item" type="telemetryItemType"/>
        </xsd:choice>
    </xsd:complexType>
    <xsd:complexType name="telemetrySetType">
        <xsd:sequence>
            <xsd:element maxOccurs="unbounded" minOccurs="0" name="Enumeration" type="xsd:string"/>
            <xsd:element maxOccurs="unbounded" minOccurs="1" name="SALTelemetry" type="telemetryType"/>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:attribute name="updateDate" type="xsd:date"/>
    <xsd:simpleType name="version">
        <xsd:restriction base="xsd:token">
            <xsd:pattern value="\d+\.\d+(\.\d+)?"/>
        </xsd:restriction>
    </xsd:simpleType>
</xsd:schema>

=== lsst-ts/ts_xml/sal_interfaces/ESS/ESS_Telemetry.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="http://lsst-sal.tuc.noao.edu/schema/SALTelemetrySet.xsl"?>
<SALTelemetrySet xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://lsst-sal.tuc.noao.edu/schema/SALTelemetrySet.xsd">
  <SALTelemetry>
    <Subsystem>ESS</Subsystem>
    <EFDB_Topic>ESS_airTurbulence</EFDB_Topic>
    <Description>Air Turbulence Instrument - CSAT3B (Tri-Axial).</Description>
    <item>
      <EFDB_Name>sensorName</EFDB_Name>
      <Description>The name of the sensor.</Description>
      <IDL_Type>string</IDL_Type>
      <Units>unitless</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>timestamp</EFDB_Name>
      <Description>Time at which the data was determined (TAI unix seconds).</Description>
      <IDL_Type>double</IDL_Type>
      <Units>second</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>ux</EFDB_Name>
      <Description>x-axis wind speed.</Description>
      <IDL_Type>float</IDL_Type>
      <Units>m/s</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>uy</EFDB_Name>
      <Description>y-axis wind speed.</Description>
      <IDL_Type>float</IDL_Type>
      <Units>m/s</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>uz</EFDB_Name>
      <Description>z-axis wind speed.</Description>
      <IDL_Type>float</IDL_Type>
      <Units>m/s</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>ts</EFDB_Name>
      <Description>Sonic temperature.</Description>
      <IDL_Type>float</IDL_Type>
      <Units>unitless</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>diagWord</EFDB_Name>
      <Description>Diagnostic word.</Description>
      <IDL_Type>short</IDL_Type>
      <Units>unitless</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>recordCounter</EFDB_Name>
      <Description>Record counter (0-63).</Description>
      <IDL_Type>short</IDL_Type>
      <Units>unitless</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>location</EFDB_Name>
      <Description>The location of the sensor.</Description>
      <IDL_Type>string</IDL_Type>
      <Units>unitless</Units>
      <Count>1</Count>
    </item>
  </SALTelemetry>
  <SALTelemetry>
    <EFDB_Topic>ESS_airFlow</EFDB_Topic>
    <Description>AirFlow Sensor - Windsonic1-L (Bi-axial).</Description>
    <item>
      <EFDB_Name>sensorName</EFDB_Name>
      <Description>The name of the sensor.</Description>
      <IDL_Type>string</IDL_Type>
      <Units>unitless</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>timestamp</EFDB_Name>
      <Description>Time at which the data was determined (TAI unix seconds).</Description>
      <IDL_Type>double</IDL_Type>
      <Units>second</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>direction</EFDB_Name>
      <Description>Wind direction.</Description>
      <IDL_Type>short</IDL_Type>
      <Units>unitless</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>speed</EFDB_Name>
      <Description>Wind speed.</Description>
      <IDL_Type>float</IDL_Type>
      <Units>m/s</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>status</EFDB_Name>
      <Description>Status Code.</Description>
      <IDL_Type>unsigned short</IDL_Type>
      <Units>unitless</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>location</EFDB_Name>
      <Description>The location of the sensor.</Description>
      <IDL_Type>string</IDL_Type>
      <Units>unitless</Units>
      <Count>1</Count>
    </item>
  </SALTelemetry>
  <SALTelemetry>
    <EFDB_Topic>ESS_temperature</EFDB_Topic>
    <Description>Temperature Sensors with up to 16 channels.</Description>
    <item>
      <EFDB_Name>sensorName</EFDB_Name>
      <Description>The name of the sensor.</Description>
      <IDL_Type>string</IDL_Type>
      <Units>unitless</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>timestamp</EFDB_Name>
      <Description>Time at which the data was determined (TAI unix seconds).</Description>
      <IDL_Type>double</IDL_Type>
      <Units>second</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>numChannels</EFDB_Name>
      <Description>The number of channels (minimum 1 and maximum 16).</Description>
      <IDL_Type>short</IDL_Type>
      <Units>unitless</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>temperature</EFDB_Name>
      <Description>The temperatures.</Description>
      <IDL_Type>float</IDL_Type>
      <Units>deg_C</Units>
      <Count>16</Count>
    </item>
    <item>
      <EFDB_Name>location</EFDB_Name>
      <Description>Comma-separated string with the locations of the sensors for each channel.</Description>
      <IDL_Type>string</IDL_Type>
      <Units>unitless</Units>
      <Count>1</Count>
    </item>
  </SALTelemetry>
  <SALTelemetry>
    <EFDB_Topic>ESS_cloudRainLight</EFDB_Topic>
    <Description>Cloud Rain Light Sensors.</Description>
    <item>
      <EFDB_Name>sensorName</EFDB_Name>
      <Description>The name of the sensor.</Description>
      <IDL_Type>string</IDL_Type>
      <Units>unitless</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>timestamp</EFDB_Name>
      <Description>Time at which the data was determined (TAI unix seconds).</Description>
      <IDL_Type>double</IDL_Type>
      <Units>second</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>ambientTemperature</EFDB_Name>
      <Description>Ambient Temperature Sensor.</Description>
      <IDL_Type>float</IDL_Type>
      <Units>deg_C</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>skyTemperature</EFDB_Name>
      <Description>Sky Temperature Sensor.</Description>
      <IDL_Type>float</IDL_Type>
      <Units>deg_C</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>lightLevel</EFDB_Name>
      <Description>Light Level.</Description>
      <IDL_Type>float</IDL_Type>
      <Units>unitless</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>rainLevel</EFDB_Name>
      <Description>Rain Level.</Description>
      <IDL_Type>float</IDL_Type>
      <Units>mm</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>location</EFDB_Name>
      <Description>The location of the sensor.</Description>
      <IDL_Type>string</IDL_Type>
      <Units>unitless</Units>
      <Count>1</Count>
    </item>
  </SALTelemetry>
  <SALTelemetry>
    <EFDB_Topic>ESS_hx85a</EFDB_Topic>
    <Description>Omega HX85A Humidity, Temperature and Dew Point Sensor.</Description>
    <item>
      <EFDB_Name>sensorName</EFDB_Name>
      <Description>The name of the sensor.</Description>
      <IDL_Type>string</IDL_Type>
      <Units>unitless</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>timestamp</EFDB_Name>
      <Description>Time at which the data was determined (TAI unix seconds).</Description>
      <IDL_Type>double</IDL_Type>
      <Units>second</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>relativeHumidity</EFDB_Name>
      <Description>Relative Humidity.</Description>
      <IDL_Type>float</IDL_Type>
      <Units>%</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>temperature</EFDB_Name>
      <Description>Air Temperature.</Description>
      <IDL_Type>float</IDL_Type>
      <Units>deg_C</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>dewPoint</EFDB_Name>
      <Description>Dew Point.</Description>
      <IDL_Type>float</IDL_Type>
      <Units>deg_C</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>location</EFDB_Name>
      <Description>The location of the sensor.</Description>
      <IDL_Type>string</IDL_Type>
      <Units>unitless</Units>
      <Count>1</Count>
    </item>
  </SALTelemetry>
  <SALTelemetry>
    <EFDB_Topic>ESS_hx85ba</EFDB_Topic>
    <Description>Omega HX85BA Humidity, Temperature and Pressure Sensor.</Description>
    <item>
      <EFDB_Name>sensorName</EFDB_Name>
      <Description>The name of the sensor.</Description>
      <IDL_Type>string</IDL_Type>
      <Units>unitless</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>timestamp</EFDB_Name>
      <Description>Time at which the data was determined (TAI unix seconds).</Description>
      <IDL_Type>double</IDL_Type>
      <Units>second</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>relativeHumidity</EFDB_Name>
      <Description>Relative Humidity.</Description>
      <IDL_Type>float</IDL_Type>
      <Units>%</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>temperature</EFDB_Name>
      <Description>Air Temperature.</Description>
      <IDL_Type>float</IDL_Type>
      <Units>deg_C</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>barometricPressure</EFDB_Name>
      <Description>Barometric Pressure.</Description>
      <IDL_Type>float</IDL_Type>
      <Units>mbar</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>location</EFDB_Name>
      <Description>The location of the sensor.</Description>
      <IDL_Type>string</IDL_Type>
      <Units>unitless</Units>
      <Count>1</Count>
    </item>
  </SALTelemetry>
</SALTelemetrySet>

=== lsst-ts/ts_xml/sal_interfaces/ATWhiteLight/ATWhiteLight_Telemetry.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="http://lsst-sal.tuc.noao.edu/schema/SALTelemetrySet.xsl"?>
<SALTelemetrySet xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="http://lsst-sal.tuc.noao.edu/schema/SALTelemetrySet.xsd">
<SALTelemetry>
    <Subsystem>ATWhiteLight</Subsystem>
    <Version>3.7.1</Version>
    <Author>Colin Winslow</Author>
    <EFDB_Topic>ATWhiteLight_timestamp</EFDB_Topic>
    <item>
        <EFDB_Name>timestamp</EFDB_Name>
        <Description>The system time (TAI).</Description>
        <IDL_Type>double</IDL_Type>
        <Units>seconds</Units>
        <Count>1</Count>
    </item>
</SALTelemetry>
<SALTelemetry>
    <Subsystem>ATWhiteLight</Subsystem>
    <Version>3.7.1</Version>
    <Author>Colin Winslow</Author>
    <EFDB_Topic>ATWhiteLight_loopTime</EFDB_Topic>
    <item>
        <EFDB_Name>loopTime</EFDB_Name>
        <Description>The actual loop time is milliseconds.</Description>
        <IDL_Type>double</IDL_Type>
        <Units>seconds</Units>
        <Count>1</Count>
    </item>
</SALTelemetry>
<SALTelemetry>
    <Subsystem>ATWhiteLight</Subsystem>
    <Version>3.7.1</Version>
    <Author>Colin Winslow</Author>
    <EFDB_Topic>ATWhiteLight_bulbHours</EFDB_Topic>
    <item>
        <EFDB_Name>bulbHours</EFDB_Name>
        <Description>The uptime of the WLS bulb</Description>
        <IDL_Type>double</IDL_Type>
        <Units>hours</Units>
        <Count>1</Count>
    </item>
</SALTelemetry>
<SALTelemetry>
    <Subsystem>ATWhiteLight</Subsystem>
    <Version>3.7.1</Version>
    <Author>Colin Winslow</Author>
    <EFDB_Topic>ATWhiteLight_bulbWattHours</EFDB_Topic>
    <item>
        <EFDB_Name>bulbHours</EFDB_Name>
        <Description>The uptime in watt-hours of the WLS bulb</Description>
        <IDL_Type>double</IDL_Type>
        <Units>watt hours</Units>
        <Count>1</Count>
    </item>
</SALTelemetry>
<SALTelemetry>
    <Subsystem>ATWhiteLight</Subsystem>
    <Version>3.8.2</Version>
    <Author>Colin Winslow</Author>
    <EFDB_Topic>ATWhiteLight_chillerFansSpeed</EFDB_Topic>
    <item>
        <EFDB_Name>fan1Speed</EFDB_Name>
        <Description>fan 1 speed</Description>
        <IDL_Type>long</IDL_Type>
        <Units>Hz</Units>
        <Count>1</Count>
    </item>
    <item>
        <EFDB_Name>fan2Speed</EFDB_Name>
        <Description>fan 2 speed</Description>
        <IDL_Type>long</IDL_Type>
        <Units>Hz</Units>
        <Count>1</Count>
    </item>
    <item>
        <EFDB_Name>fan3Speed</EFDB_Name>
        <Description>fan 3 speed</Description>
        <IDL_Type>long</IDL_Type>
        <Units>Hz</Units>
        <Count>1</Count>
    </item>
    <item>
        <EFDB_Name>fan4Speed</EFDB_Name>
        <Description>fan 4 speed</Description>
        <IDL_Type>long</IDL_Type>
        <Units>Hz</Units>
        <Count>1</Count>
    </item>
    <item>
        <EFDB_Name>timestamp</EFDB_Name>
        <Description>time stamp</Description>
        <IDL_Type>double</IDL_Type>
        <Units>seconds</Units>
        <Count>1</Count>
    </item>
</SALTelemetry>
<SALTelemetry>
    <Subsystem>ATWhiteLight</Subsystem>
    <Version>3.8.2</Version>
    <Author>Colin Winslow</Author>
    <EFDB_Topic>ATWhiteLight_chillerUpTime</EFDB_Topic>
    <item>
        <EFDB_Name>upTime</EFDB_Name>
        <Description>chiller uptime</Description>
        <IDL_Type>long</IDL_Type>
        <Units>Minutes</Units>
        <Count>1</Count>
    </item>
    <item>
        <EFDB_Name>timestamp</EFDB_Name>
        <Description>time stamp</Description>
        <IDL_Type>double</IDL_Type>
        <Units>seconds</Units>
        <Count>1</Count>
    </item>
</SALTelemetry>
<SALTelemetry>
    <Subsystem>ATWhiteLight</Subsystem>
    <Version>3.8.2</Version>
    <Author>Colin Winslow</Author>
    <EFDB_Topic>ATWhiteLight_chillerTempSensors</EFDB_Topic>
    <item>
        <EFDB_Name>setTemperature</EFDB_Name>
        <Description>the temperature we currently targetting</Description>
        <IDL_Type>float</IDL_Type>
        <Units>DegC</Units>
        <Count>1</Count>
    </item>
    <item>
        <EFDB_Name>supplyTemperature</EFDB_Name>
        <Description>the temperature of the coolant supply</Description>
        <IDL_Type>float</IDL_Type>
        <Units>DegC</Units>
        <Count>1</Count>
    </item>
    <item>
        <EFDB_Name>returnTemperature</EFDB_Name>
        <Description>the return temperature of coolant</Description>
        <IDL_Type>float</IDL_Type>
        <Units>DegC</Units>
        <Count>1</Count>
    </item>
    <item>
        <EFDB_Name>ambientTemperature</EFDB_Name>
        <Description>ambient temperature</Description>
        <IDL_Type>float</IDL_Type>
        <Units>DegC</Units>
        <Count>1</Count>
    </item>
    <item>
        <EFDB_Name>timestamp</EFDB_Name>
        <Description>timestamp</Description>
        <IDL_Type>double</IDL_Type>
        <Units>seconds</Units>
        <Count>1</Count>
    </item>
</SALTelemetry>
<SALTelemetry>
    <Subsystem>ATWhiteLight</Subsystem>
    <Version>3.8.2</Version>
    <Author>Colin Winslow</Author>
    <EFDB_Topic>ATWhiteLight_chillerProcessFlow</EFDB_Topic>
    <item>
        <EFDB_Name>flow</EFDB_Name>
        <Description>flow rate in liters/min</Description>
        <IDL_Type>float</IDL_Type>
        <Units>lpm</Units>
        <Count>1</Count>
    </item>
    <item>
        <EFDB_Name>timestamp</EFDB_Name>
        <Description>timestamp</Description>
        <IDL_Type>double</IDL_Type>
        <Units>seconds</Units>
        <Count>1</Count>
    </item>
</SALTelemetry>
<SALTelemetry>
    <Subsystem>ATWhiteLight</Subsystem>
    <Version>3.8.2</Version>
    <Author>Colin Winslow</Author>
    <EFDB_Topic>ATWhiteLight_chillerTECBankCurrent</EFDB_Topic>
    <item>
        <EFDB_Name>bank1Current</EFDB_Name>
        <Description>DC Amps bank 1</Description>
        <IDL_Type>float</IDL_Type>
        <Units>ADC</Units>
        <Count>1</Count>
    </item>
    <item>
        <EFDB_Name>bank2Current</EFDB_Name>
        <Description>DC Amps bank 2</Description>
        <IDL_Type>float</IDL_Type>
        <Units>ADC</Units>
        <Count>1</Count>
    </item>
    <item>
        <EFDB_Name>timestamp</EFDB_Name>
        <Description>timestamp</Description>
        <IDL_Type>double</IDL_Type>
        <Units>seconds</Units>
        <Count>1</Count>
    </item>
</SALTelemetry>
<SALTelemetry>
    <Subsystem>ATWhiteLight</Subsystem>
    <Version>3.8.2</Version>
    <Author>Colin Winslow</Author>
    <EFDB_Topic>ATWhiteLight_chillerTEDriveLevel</EFDB_Topic>
    <item>
        <EFDB_Name>chillerTEDriveLevel</EFDB_Name>
        <Description>thermo electric drive level</Description>
        <IDL_Type>float</IDL_Type>
        <Units>percent</Units>
        <Count>1</Count>
    </item>
    <item>
        <EFDB_Name>timestamp</EFDB_Name>
        <Description>timestamp</Description>
        <IDL_Type>double</IDL_Type>
        <Units>seconds</Units>
        <Count>1</Count>
    </item>
</SALTelemetry></SALTelemetrySet>
